import * as fs from 'fs';
import { QuizQuestion } from '../src/types';
import { MATEMATIK_TAHUN_4_KBAT_QUESTIONS } from '../src/data/matematikTahun4Kbat';
import { SAINS_TAHUN_4_QUESTIONS } from '../src/data/sainsTahun4';
import { ENGLISH_TAHUN_4_QUESTIONS } from '../src/data/englishTahun4';

// =========================================================================
// 1. EXPAND MATEMATIK TAHUN 4 (+5 questions per topic = +30 questions)
// =========================================================================
const matExtra: QuizQuestion[] = [
  // Topik 1: Nombor hingga 100,000
  {
    id: 't4-mat-topik1-11',
    year: 4,
    subject: 'Matematik',
    topic: 'Nombor hingga 100,000',
    subtopic: 'Pembundaran Nombor',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Sebuah kilang mencetak 68,472 naskhah majalah. Bundarkan nombor tersebut kepada puluh ribu yang terdekat.',
    options: { A: '70,000', B: '68,000', C: '60,000', D: '69,000' },
    correctAnswer: 'A',
    explanation: 'Digit ribu ialah 8 (≥ 5), maka digit puluh ribu 6 ditambah 1 menjadi 70,000.',
    learningStandard: 'SK 1.4 Pembundaran',
  },
  {
    id: 't4-mat-topik1-12',
    year: 4,
    subject: 'Matematik',
    topic: 'Nombor hingga 100,000',
    subtopic: 'Pola Nombor',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Kenal pasti nombor seterusnya dalam pola: 23,400, 23,450, 23,500, _______.',
    options: { A: '23,550', B: '23,600', C: '24,000', D: '23,520' },
    correctAnswer: 'A',
    explanation: 'Pola nombor bertambah sebanyak 50 setiap langkah: 23,500 + 50 = 23,550.',
    learningStandard: 'SK 1.5 Pola Nombor',
  },
  {
    id: 't4-mat-topik1-13',
    year: 4,
    subject: 'Matematik',
    topic: 'Nombor hingga 100,000',
    subtopic: 'Penyelesaian Masalah Tambah Tolak',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Pusat Edaran A mempunyai 52,000 buku teks. Sebanyak 18,450 naskhah dihantar ke Zon Utara dan 14,200 naskhah dihantar ke Zon Selatan. Berapakah baki buku di pusat tersebut?',
    options: { A: '19,350', B: '20,350', C: '18,350', D: '21,350' },
    correctAnswer: 'A',
    explanation: '52,000 - (18,450 + 14,200) = 52,000 - 32,650 = 19,350.',
    learningStandard: 'SK 1.6 Penyelesaian Masalah',
  },
  {
    id: 't4-mat-topik1-14',
    year: 4,
    subject: 'Matematik',
    topic: 'Nombor hingga 100,000',
    subtopic: 'Pendaraban Nombor Besar',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebuah syarikat mengeksport 125 kotak biskut setiap hari. Setiap kotak mengandungi 48 bungkus biskut. Berapakah jumlah bungkus biskut dieksport setiap hari?',
    options: { A: '6,000', B: '5,500', C: '6,200', D: '7,000' },
    correctAnswer: 'A',
    explanation: '125 × 48 = 6,000 bungkus biskut.',
    learningStandard: 'SK 1.6 Operasi Darab',
  },
  {
    id: 't4-mat-topik1-15',
    year: 4,
    subject: 'Matematik',
    topic: 'Nombor hingga 100,000',
    subtopic: 'Pembahagian dan Baki',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebanyak 34,560 kilogram beras dibungkus sama banyak ke dalam 100 guni besar. Berapakah baki beras yang tinggal selepas pengagihan penuh?',
    options: { A: '60 kg', B: '56 kg', C: '0 kg', D: '34 kg' },
    correctAnswer: 'A',
    explanation: '34,560 ÷ 100 = 345 guni dengan baki 60 kg.',
    learningStandard: 'SK 1.6 Operasi Bahagi',
  },

  // Topik 2: Pecahan, Perpuluhan & Peratus
  {
    id: 't4-mat-topik2-11',
    year: 4,
    subject: 'Matematik',
    topic: 'Pecahan, Perpuluhan & Peratus',
    subtopic: 'Pecahan Tak Wajar kepada Nombor Bercampur',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Tukarkan pecahan tak wajar 17/5 kepada nombor bercampur.',
    options: { A: '3 2/5', B: '3 1/5', C: '2 3/5', D: '3 4/5' },
    correctAnswer: 'A',
    explanation: '17 ÷ 5 = 3 baki 2, maka 17/5 = 3 2/5.',
    learningStandard: 'SK 2.1 Pecahan',
  },
  {
    id: 't4-mat-topik2-12',
    year: 4,
    subject: 'Matematik',
    topic: 'Pecahan, Perpuluhan & Peratus',
    subtopic: 'Penolakan Pecahan Berbeza Penyebut',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Hitung nilai bagi 7/8 - 1/4.',
    options: { A: '5/8', B: '6/8', C: '3/8', D: '1/2' },
    correctAnswer: 'A',
    explanation: 'Samakan penyebut: 1/4 = 2/8. Maka 7/8 - 2/8 = 5/8.',
    learningStandard: 'SK 2.1 Operasi Tolak Pecahan',
  },
  {
    id: 't4-mat-topik2-13',
    year: 4,
    subject: 'Matematik',
    topic: 'Pecahan, Perpuluhan & Peratus',
    subtopic: 'Pendaraban Perpuluhan',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Hitung 4.25 × 6.',
    options: { A: '25.50', B: '24.30', C: '25.25', D: '26.00' },
    correctAnswer: 'A',
    explanation: '4.25 × 6 = 25.50.',
    learningStandard: 'SK 2.2 Perpuluhan',
  },
  {
    id: 't4-mat-topik2-14',
    year: 4,
    subject: 'Matematik',
    topic: 'Pecahan, Perpuluhan & Peratus',
    subtopic: 'Penukaran Pecahan kepada Peratus',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Tukarkan 3/4 kepada bentuk peratusan.',
    options: { A: '75%', B: '70%', C: '80%', D: '60%' },
    correctAnswer: 'A',
    explanation: '3/4 × 100% = 75%.',
    learningStandard: 'SK 2.3 Peratus',
  },
  {
    id: 't4-mat-topik2-15',
    year: 4,
    subject: 'Matematik',
    topic: 'Pecahan, Perpuluhan & Peratus',
    subtopic: 'Penyelesaian Masalah Peratus',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Daripada 80 orang murid, 25% menyertai persatuan pengakap. Berapakah bilangan murid yang menyertai pengakap?',
    options: { A: '20 orang', B: '25 orang', C: '16 orang', D: '30 orang' },
    correctAnswer: 'A',
    explanation: '25/100 × 80 = 1/4 × 80 = 20 orang.',
    learningStandard: 'SK 2.3 Peratusan Kuantiti',
  },

  // Topik 3: Wang hingga RM100,000 & Pengurusan Wang
  {
    id: 't4-mat-topik3-11',
    year: 4,
    subject: 'Matematik',
    topic: 'Wang hingga RM100,000 & Pengurusan Wang',
    subtopic: 'Operasi Bergabung Wang',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Hitung: RM45,600 + RM12,350 - RM8,900.',
    options: { A: 'RM49,050', B: 'RM48,950', C: 'RM50,050', D: 'RM47,850' },
    correctAnswer: 'A',
    explanation: 'RM45,600 + RM12,350 = RM57,950. RM57,950 - RM8,900 = RM49,050.',
    learningStandard: 'SK 3.1 Operasi Bergabung Wang',
  },
  {
    id: 't4-mat-topik3-12',
    year: 4,
    subject: 'Matematik',
    topic: 'Wang hingga RM100,000 & Pengurusan Wang',
    subtopic: 'Pendaraban Nilai Wang',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebuah kedai komputer menjual 15 unit komputer riba dengan harga RM2,400 seunit. Berapakah jumlah jualan keseluruhan?',
    options: { A: 'RM36,000', B: 'RM34,000', C: 'RM38,000', D: 'RM35,500' },
    correctAnswer: 'A',
    explanation: '15 × RM2,400 = RM36,000.',
    learningStandard: 'SK 3.1 Pendaraban Wang',
  },
  {
    id: 't4-mat-topik3-13',
    year: 4,
    subject: 'Matematik',
    topic: 'Wang hingga RM100,000 & Pengurusan Wang',
    subtopic: 'Mata Wang Utama Dunia',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Mata wang rasmi bagi negara Jepun ialah:',
    options: { A: 'Yen', B: 'Won', C: 'Dollar', D: 'Baht' },
    correctAnswer: 'A',
    explanation: 'Mata wang rasmi Jepun ialah Yen (¥).',
    learningStandard: 'SK 3.3 Mata Wang Asing',
  },
  {
    id: 't4-mat-topik3-14',
    year: 4,
    subject: 'Matematik',
    topic: 'Wang hingga RM100,000 & Pengurusan Wang',
    subtopic: 'Instrumen Pembayaran',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Kaedah pembayaran tanpa tunai menggunakan kad bank yang memotong wang terus daripada akaun simpanan dipanggil:',
    options: { A: 'Kad Debit', B: 'Kad Kredit', C: 'Cek Tertunda', D: 'Wang Pos' },
    correctAnswer: 'A',
    explanation: 'Kad debit memotong baki akaun simpanan pemilik secara langsung semasa transaksi.',
    learningStandard: 'SK 3.2 Instrumen Pembayaran',
  },
  {
    id: 't4-mat-topik3-15',
    year: 4,
    subject: 'Matematik',
    topic: 'Wang hingga RM100,000 & Pengurusan Wang',
    subtopic: 'Belanjawan Kewangan KBAT',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Gaji bulanan Encik Faizal ialah RM4,500. Dia menyimpan 15% daripada gajinya untuk simpanan kecemasan setiap bulan. Berapakah wang simpanannya sebulan?',
    options: { A: 'RM675', B: 'RM650', C: 'RM700', D: 'RM625' },
    correctAnswer: 'A',
    explanation: '15/100 × RM4,500 = RM675 sebulan.',
    learningStandard: 'SK 3.4 Pengurusan Kewangan',
  },

  // Topik 4: Masa, Waktu & Perkaitan Abad/Dekad
  {
    id: 't4-mat-topik4-11',
    year: 4,
    subject: 'Matematik',
    topic: 'Masa, Waktu & Perkaitan Abad/Dekad',
    subtopic: 'Sistem 24 Jam',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Tukarkan pukul 9:45 malam kepada sistem 24 jam.',
    options: { A: 'Jam 2145', B: 'Jam 0945', C: 'Jam 2045', D: 'Jam 2245' },
    correctAnswer: 'A',
    explanation: 'Pukul 9:45 p.m. + 12 jam = Jam 2145.',
    learningStandard: 'SK 4.1 Sistem 24 Jam',
  },
  {
    id: 't4-mat-topik4-12',
    year: 4,
    subject: 'Matematik',
    topic: 'Masa, Waktu & Perkaitan Abad/Dekad',
    subtopic: 'Perkaitan Abad dan Tahun',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Sebuah monumen bersejarah telah berusia 3 abad 45 tahun. Berapakah usia monumen itu dalam tahun?',
    options: { A: '345 tahun', B: '3045 tahun', C: '75 tahun', D: '3450 tahun' },
    correctAnswer: 'A',
    explanation: '1 abad = 100 tahun. 3 abad 45 tahun = (3 × 100) + 45 = 345 tahun.',
    learningStandard: 'SK 4.2 Perkaitan Masa Abad dan Tahun',
  },
  {
    id: 't4-mat-topik4-13',
    year: 4,
    subject: 'Matematik',
    topic: 'Masa, Waktu & Perkaitan Abad/Dekad',
    subtopic: 'Penolakan Masa Dekad dan Tahun',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Hitung: 6 dekad 2 tahun - 2 dekad 7 tahun.',
    options: { A: '3 dekad 5 tahun', B: '3 dekad 7 tahun', C: '4 dekad 5 tahun', D: '3 dekad 3 tahun' },
    correctAnswer: 'A',
    explanation: 'Pinjam 1 dekad (10 tahun): 5 dekad 12 tahun - 2 dekad 7 tahun = 3 dekad 5 tahun.',
    learningStandard: 'SK 4.3 Operasi Tolak Masa',
  },
  {
    id: 't4-mat-topik4-14',
    year: 4,
    subject: 'Matematik',
    topic: 'Masa, Waktu & Perkaitan Abad/Dekad',
    subtopic: 'Pendaraban Masa',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Hitung: 4 × 2 hari 8 jam.',
    options: { A: '9 hari 8 jam', B: '8 hari 32 jam', C: '9 hari 4 jam', D: '10 hari 2 jam' },
    correctAnswer: 'A',
    explanation: '4 × 2 hari = 8 hari. 4 × 8 jam = 32 jam = 1 hari 8 jam. Jumlah = 9 hari 8 jam.',
    learningStandard: 'SK 4.3 Pendaraban Masa',
  },
  {
    id: 't4-mat-topik4-15',
    year: 4,
    subject: 'Matematik',
    topic: 'Masa, Waktu & Perkaitan Abad/Dekad',
    subtopic: 'Tempoh Masa Perjalanan',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebuah bas bertolak dari Melaka pada Jam 0830 dan tiba di Ipoh pada Jam 1415 hari yang sama. Berapakah tempoh masa perjalanannya?',
    options: { A: '5 jam 45 minit', B: '5 jam 15 minit', C: '6 jam 15 minit', D: '5 jam 30 minit' },
    correctAnswer: 'A',
    explanation: 'Dari 0830 hingga 1415 = (1415 - 0830) = 5 jam 45 minit.',
    learningStandard: 'SK 4.4 Tempoh Masa',
  },

  // Topik 5: Panjang, Jisim & Isi Padu Cecair
  {
    id: 't4-mat-topik5-11',
    year: 4,
    subject: 'Matematik',
    topic: 'Panjang, Jisim & Isi Padu Cecair',
    subtopic: 'Penukaran Kilometer dan Meter',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Tukarkan 4.85 kilometer kepada meter.',
    options: { A: '4,850 m', B: '485 m', C: '48,500 m', D: '4.85 m' },
    correctAnswer: 'A',
    explanation: '1 km = 1,000 m. 4.85 × 1,000 = 4,850 m.',
    learningStandard: 'SK 5.1 Unit Panjang',
  },
  {
    id: 't4-mat-topik5-12',
    year: 4,
    subject: 'Matematik',
    topic: 'Panjang, Jisim & Isi Padu Cecair',
    subtopic: 'Penolakan Jisim',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Seketul daging seberat 3 kg 450 g dipotong 1 kg 800 g untuk dimasak rendang. Berapakah baki berat daging?',
    options: { A: '1 kg 650 g', B: '1 kg 750 g', C: '2 kg 650 g', D: '1 kg 550 g' },
    correctAnswer: 'A',
    explanation: '3,450 g - 1,800 g = 1,650 g = 1 kg 650 g.',
    learningStandard: 'SK 5.2 Operasi Jisim',
  },
  {
    id: 't4-mat-topik5-13',
    year: 4,
    subject: 'Matematik',
    topic: 'Panjang, Jisim & Isi Padu Cecair',
    subtopic: 'Pendaraban Isi Padu',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebuah botol mengandungi 750 mℓ air mineral. Berapakah jumlah isi padu bagi 8 botol yang sama dalam liter?',
    options: { A: '6 ℓ', B: '5.5 ℓ', C: '6.5 ℓ', D: '7 ℓ' },
    correctAnswer: 'A',
    explanation: '750 mℓ × 8 = 6,000 mℓ = 6 ℓ.',
    learningStandard: 'SK 5.3 Isi Padu Cecair',
  },
  {
    id: 't4-mat-topik5-14',
    year: 4,
    subject: 'Matematik',
    topic: 'Panjang, Jisim & Isi Padu Cecair',
    subtopic: 'Pembahagian Panjang',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Segulung dawai sepanjang 18 m 40 cm dipotong kepada 4 bahagian sama panjang. Berapakah panjang setiap bahagian?',
    options: { A: '4 m 60 cm', B: '4 m 40 cm', C: '4 m 80 cm', D: '5 m 10 cm' },
    correctAnswer: 'A',
    explanation: '18 m 40 cm = 1,840 cm ÷ 4 = 460 cm = 4 m 60 cm.',
    learningStandard: 'SK 5.1 Pembahagian Panjang',
  },
  {
    id: 't4-mat-topik5-15',
    year: 4,
    subject: 'Matematik',
    topic: 'Panjang, Jisim & Isi Padu Cecair',
    subtopic: 'Penyelesaian Masalah Gabungan',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebuah tangki mengandungi 25 ℓ air. Sebanyak 14 ℓ 350 mℓ digunakan untuk menyiram pokok dan 3 ℓ 800 mℓ untuk mencuci kereta. Berapakah baki air di dalam tangki?',
    options: { A: '6 ℓ 850 mℓ', B: '7 ℓ 150 mℓ', C: '6 ℓ 250 mℓ', D: '7 ℓ 850 mℓ' },
    correctAnswer: 'A',
    explanation: 'Jumlah guna: 14 ℓ 350 mℓ + 3 ℓ 800 mℓ = 18 ℓ 150 mℓ. Baki: 25 ℓ - 18 ℓ 150 mℓ = 6 ℓ 850 mℓ.',
    learningStandard: 'SK 5.3 Penyelesaian Masalah Isi Padu',
  },

  // Topik 6: Koordinat, Nisbah & Kadaran
  {
    id: 't4-mat-topik6-11',
    year: 4,
    subject: 'Matematik',
    topic: 'Koordinat, Nisbah & Kadaran',
    subtopic: 'Membaca Koordinat Satah Cartes',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Titik A berada 3 unit ke kanan dari asalan dan 5 unit ke atas. Apakah koordinat titik A?',
    options: { A: '(3, 5)', B: '(5, 3)', C: '(0, 3)', D: '(5, 0)' },
    correctAnswer: 'A',
    explanation: 'Koordinat ditulis sebagai (x, y). Maka titik A ialah (3, 5).',
    learningStandard: 'SK 7.1 Koordinat Satah Cartes',
  },
  {
    id: 't4-mat-topik6-12',
    year: 4,
    subject: 'Matematik',
    topic: 'Koordinat, Nisbah & Kadaran',
    subtopic: 'Jarak Mengufuk dan Mencancang',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Titik P mempunyai koordinat (2, 1) dan titik Q mempunyai koordinat (7, 5). Berapakah jarak mengufuk dan jarak mencancang dari P ke Q?',
    options: { A: '5 unit mengufuk, 4 unit mencancang', B: '4 unit mengufuk, 5 unit mencancang', C: '7 unit mengufuk, 5 unit mencancang', D: '2 unit mengufuk, 1 unit mencancang' },
    correctAnswer: 'A',
    explanation: 'Jarak mengufuk: 7 - 2 = 5 unit. Jarak mencancang: 5 - 1 = 4 unit.',
    learningStandard: 'SK 7.1 Jarak Koordinat',
  },
  {
    id: 't4-mat-topik6-13',
    year: 4,
    subject: 'Matematik',
    topic: 'Koordinat, Nisbah & Kadaran',
    subtopic: 'Konsep Asas Nisbah',
    difficulty: 'KBAT (Aras Rendah)',
    question: 'Di dalam sebuah bakul terdapat 4 biji epal hijau dan 7 biji epal merah. Apakah nisbah bilangan epal hijau kepada bilangan epal merah?',
    options: { A: '4 : 7', B: '7 : 4', C: '4 : 11', D: '7 : 11' },
    correctAnswer: 'A',
    explanation: 'Nisbah epal hijau kepada epal merah ialah 4 : 7.',
    learningStandard: 'SK 7.2 Nisbah',
  },
  {
    id: 't4-mat-topik6-14',
    year: 4,
    subject: 'Matematik',
    topic: 'Koordinat, Nisbah & Kadaran',
    subtopic: 'Nisbah Bahagian kepada Keseluruhan',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Sebuah kelas mempunyai 12 orang murid lelaki dan 18 orang murid perempuan. Apakah nisbah termudah bilangan murid lelaki kepada jumlah keseluruhan murid?',
    options: { A: '2 : 5', B: '3 : 5', C: '2 : 3', D: '12 : 18' },
    correctAnswer: 'A',
    explanation: 'Jumlah murid = 12 + 18 = 30. Nisbah lelaki kepada jumlah = 12 : 30 = 2 : 5.',
    learningStandard: 'SK 7.2 Nisbah Termudah',
  },
  {
    id: 't4-mat-topik6-15',
    year: 4,
    subject: 'Matematik',
    topic: 'Koordinat, Nisbah & Kadaran',
    subtopic: 'Kadaran Kaedah Unitari',
    difficulty: 'KBAT (Aras Sederhana)',
    question: 'Harga bagi 5 batang pen ialah RM15. Berapakah harga bagi 9 batang pen yang sama?',
    options: { A: 'RM27', B: 'RM25', C: 'RM30', D: 'RM24' },
    correctAnswer: 'A',
    explanation: 'Harga sebatang pen: RM15 ÷ 5 = RM3. Harga 9 batang: 9 × RM3 = RM27.',
    learningStandard: 'SK 7.3 Kadaran Unitari',
  },
];

const allMat4 = [...MATEMATIK_TAHUN_4_KBAT_QUESTIONS, ...matExtra];
fs.writeFileSync('src/data/matematikTahun4Kbat.ts', `import { QuizQuestion } from '../types';\n\nexport const MATEMATIK_TAHUN_4_KBAT_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allMat4, null, 2)};\n`, 'utf8');
console.log(`Updated Matematik Tahun 4: total ${allMat4.length} questions.`);

// =========================================================================
// 2. EXPAND SAINS TAHUN 4 (+5 questions per topic = +30 questions)
// =========================================================================
const snExtra: QuizQuestion[] = [
  // Topik 1: Kemahiran Saintifik
  {
    id: 't4-sn-kemahiran-11',
    year: 4,
    subject: 'Sains',
    topic: 'Kemahiran Saintifik (Pemboleh Ubah & Hipotesis)',
    difficulty: 'Sederhana',
    question: 'Dalam suatu penyiasatan sains, pemboleh ubah yang ditetapkan sepanjang eksperimen untuk memastikan ujian yang adil dinamakan:',
    options: { A: 'Pemboleh ubah dimalarkan (PMal)', B: 'Pemboleh ubah dimanipulasi (PM)', C: 'Pemboleh ubah bergerak balas (PB)', D: 'Pemboleh ubah luaran' },
    correctAnswer: 'A',
    explanation: 'Pemboleh ubah dimalarkan mesti dikekalkan sama sepanjang eksperimen bagi menjamin keadilan ujian.',
    learningStandard: 'SK 1.1 Kemahiran Proses Sains',
  },
  {
    id: 't4-sn-kemahiran-12',
    year: 4,
    subject: 'Sains',
    topic: 'Kemahiran Saintifik (Pemboleh Ubah & Hipotesis)',
    difficulty: 'Sederhana',
    question: 'Pilih pernyataan hipotesis yang betul bagi hubungan antara haba dan kadar penyejatan air.',
    options: { A: 'Semakin tinggi suhu persekitaran, semakin cepat kadar penyejatan air', B: 'Suhu air tidak berubah', C: 'Air menyejat pada waktu malam sahaja', D: 'Warna air mempengaruhi suhunya' },
    correctAnswer: 'A',
    explanation: 'Hipotesis mengaitkan pemboleh ubah dimanipulasi (suhu) dan bergerak balas (kadar penyejatan).',
    learningStandard: 'SK 1.1 Membuat Hipotesis',
  },
  {
    id: 't4-sn-kemahiran-13',
    year: 4,
    subject: 'Sains',
    topic: 'Kemahiran Saintifik (Pemboleh Ubah & Hipotesis)',
    difficulty: 'Mudah',
    question: 'Alat pengukur yang paling tepat digunakan untuk mengukur isi padu cecair dengan kejituan tinggi di makmal ialah:',
    options: { A: 'Silinder penyukat', B: 'Bikar kaca', C: 'Pembaris meter', D: 'Neraca tuas' },
    correctAnswer: 'A',
    explanation: 'Silinder penyukat direka dengan senggatan tepat untuk mengukur isi padu cecair.',
    learningStandard: 'SK 1.1 Mengukur dan Menggunakan Nombor',
  },
  {
    id: 't4-sn-kemahiran-14',
    year: 4,
    subject: 'Sains',
    topic: 'Kemahiran Saintifik (Pemboleh Ubah & Hipotesis)',
    difficulty: 'Sederhana',
    question: 'Mata pemerhati semasa membaca paras meniskus air pada silinder penyukat mestilah berada:',
    options: { A: 'Aras dengan dasar meniskus cecair', B: 'Di atas permukaan cecair', C: 'Di bawah dasar silinder', D: 'Dari arah serong sisi' },
    correctAnswer: 'A',
    explanation: 'Kedudukan mata mesti selaras dengan dasar meniskus melengkung untuk mengelakkan ralat paralaks.',
    learningStandard: 'SK 1.1 Kemahiran Manipulatif',
  },
  {
    id: 't4-sn-kemahiran-15',
    year: 4,
    subject: 'Sains',
    topic: 'Kemahiran Saintifik (Pemboleh Ubah & Hipotesis)',
    difficulty: 'Sukar',
    question: 'Apakah kesimpulan yang tepat jika pemerhatian menunjukkan anak benih tanpa air layu dan mati selepas 5 hari?',
    options: { A: 'Tumbuhan memerlukan air untuk terus hidup', B: 'Anak benih tidak memerlukan tanah', C: 'Semua tumbuhan boleh hidup dalam gelap', D: 'Air menyebabkan akar pokok reput' },
    correctAnswer: 'A',
    explanation: 'Eksperimen membuktikan air adalah keperluan asas mutlak percambahan dan kehidupan tumbuhan.',
    learningStandard: 'SK 1.1 Membuat Kesimpulan',
  },

  // Topik 2: Manusia (Pernafasan, Perkumuhan & Rangsangan)
  {
    id: 't4-sn-manusia-11',
    year: 4,
    subject: 'Sains',
    topic: 'Manusia (Pernafasan, Perkumuhan & Rangsangan)',
    difficulty: 'Mudah',
    question: 'Apakah organ perkumuhan yang menyingkirkan karbon dioksida dan wap air daripada badan?',
    options: { A: 'Peparu', B: 'Kulit', C: 'Ginjal', D: 'Jantung' },
    correctAnswer: 'A',
    explanation: 'Peparu menyingkirkan gas karbon dioksida dan wap air semasa proses hembusan nafas.',
    learningStandard: 'SK 2.2 Perkumuhan Manusia',
  },
  {
    id: 't4-sn-manusia-12',
    year: 4,
    subject: 'Sains',
    topic: 'Manusia (Pernafasan, Perkumuhan & Rangsangan)',
    difficulty: 'Mudah',
    question: 'Air kencing dihasilkan oleh organ perkumuhan iaitu:',
    options: { A: 'Ginjal', B: 'Hati', C: 'Perut', D: 'Pundi hempedu' },
    correctAnswer: 'A',
    explanation: 'Ginjal menapis darah dan menyingkirkan urea, air berlebihan serta garam mineral sebagai air kencing.',
    learningStandard: 'SK 2.2 Fungsi Ginjal',
  },
  {
    id: 't4-sn-manusia-13',
    year: 4,
    subject: 'Sains',
    topic: 'Manusia (Pernafasan, Perkumuhan & Rangsangan)',
    difficulty: 'Mudah',
    question: 'Kulit menyingkirkan bahan kumuh dalam bentuk:',
    options: { A: 'Peluh', B: 'Air kencing', C: 'Tinja', D: 'Karbon dioksida' },
    correctAnswer: 'A',
    explanation: 'Kelenjar peluh pada kulit merembeskan peluh untuk menyejukkan badan dan membuang sisa garam.',
    learningStandard: 'SK 2.2 Perkumuhan Kulit',
  },
  {
    id: 't4-sn-manusia-14',
    year: 4,
    subject: 'Sains',
    topic: 'Manusia (Pernafasan, Perkumuhan & Rangsangan)',
    difficulty: 'Sederhana',
    question: 'Tangan terangkat secara spontan apabila tersentuh cerek panas. Tindakan ini dinamakan gerak balas terhadap:',
    options: { A: 'Rangsangan haba/panas', B: 'Rangsangan bau', C: 'Rangsangan bunyi', D: 'Rangsangan cahaya' },
    correctAnswer: 'A',
    explanation: 'Tindakan refleks menarik tangan melindungi badan daripada kecederaan akibat haba panas.',
    learningStandard: 'SK 2.3 Gerak Balas terhadap Rangsangan',
  },
  {
    id: 't4-sn-manusia-15',
    year: 4,
    subject: 'Sains',
    topic: 'Manusia (Pernafasan, Perkumuhan & Rangsangan)',
    difficulty: 'Sukar',
    question: 'Apakah tabiat buruk yang boleh melambatkan gerak balas manusia terhadap rangsangan kecemasan?',
    options: { A: 'Mengambil minuman beralkohol dan penyalahgunaan dadah', B: 'Bersenam secara kerap', C: 'Minum banyak air mineral', D: 'Tidur lapan jam sehari' },
    correctAnswer: 'A',
    explanation: 'Alkohol dan dadah menjejaskan fungsi sistem saraf pusat dan melambatkan masa tindak balas.',
    learningStandard: 'SK 2.3 Tabiat Menjejaskan Gerak Balas',
  },

  // Topik 3: Haiwan (Organ Pernafasan & Pengelasan Vertebrata)
  {
    id: 't4-sn-haiwan-11',
    year: 4,
    subject: 'Sains',
    topic: 'Haiwan (Organ Pernafasan & Pengelasan Vertebrata)',
    difficulty: 'Mudah',
    question: 'Belalang dan rama-rama bernafas menggunakan struktur khas pada sisi badannya yang dipanggil:',
    options: { A: 'Spirakel', B: 'Insang', C: 'Kulit lembap', D: 'Peparu' },
    correctAnswer: 'A',
    explanation: 'Serangga bernafas melalui liang halus pada abdomen yang disebut spirakel.',
    learningStandard: 'SK 3.1 Organ Pernafasan Haiwan',
  },
  {
    id: 't4-sn-haiwan-12',
    year: 4,
    subject: 'Sains',
    topic: 'Haiwan (Organ Pernafasan & Pengelasan Vertebrata)',
    difficulty: 'Mudah',
    question: 'Cacing tanah dan lintah bernafas melalui:',
    options: { A: 'Kulit lembap', B: 'Insang', C: 'Spirakel', D: 'Peparu buku' },
    correctAnswer: 'A',
    explanation: 'Cacing tanah menyerap oksigen terus melalui permukaan kulit yang sentiasa lembap.',
    learningStandard: 'SK 3.1 Haiwan Kulit Lembap',
  },
  {
    id: 't4-sn-haiwan-13',
    year: 4,
    subject: 'Sains',
    topic: 'Haiwan (Organ Pernafasan & Pengelasan Vertebrata)',
    difficulty: 'Sederhana',
    question: 'Haiwan amfibia seperti katak dewasa bernafas menggunakan:',
    options: { A: 'Peparu dan kulit lembap', B: 'Insang sahaja', C: 'Spirakel sahaja', D: 'Sirip dan ekor' },
    correctAnswer: 'A',
    explanation: 'Katak dewasa bernafas menggunakan peparu di darat dan kulit lembap semasa berada di dalam air.',
    learningStandard: 'SK 3.1 Haiwan Berbilang Organ Pernafasan',
  },
  {
    id: 't4-sn-haiwan-14',
    year: 4,
    subject: 'Sains',
    topic: 'Haiwan (Organ Pernafasan & Pengelasan Vertebrata)',
    difficulty: 'Mudah',
    question: 'Apakah ciri utama kumpulan haiwan vertebrata?',
    options: { A: 'Mempunyai tulang belakang', B: 'Mempunyai cangkerang keras', C: 'Berdarah sejuk sahaja', D: 'Tidak mempunyai kaki' },
    correctAnswer: 'A',
    explanation: 'Vertebrata ialah haiwan yang memiliki struktur tulang belakang.',
    learningStandard: 'SK 3.2 Pengelasan Vertebrata',
  },
  {
    id: 't4-sn-haiwan-15',
    year: 4,
    subject: 'Sains',
    topic: 'Haiwan (Organ Pernafasan & Pengelasan Vertebrata)',
    difficulty: 'Sukar',
    question: 'Paus dan lumba-lumba dikelaskan sebagai mamalia dan bukannya ikan kerana:',
    options: { A: 'Melahirkan anak, menyusukan anak dan bernafas melalui peparu', B: 'Berenang menggunakan sirip', C: 'Tinggal di lautan luas', D: 'Mempunyai sisik berkilat' },
    correctAnswer: 'A',
    explanation: 'Paus ialah mamalia akuatik berdarah panas yang bernafas melalui peparu dan menyusukan anaknya.',
    learningStandard: 'SK 3.2 Ciri Khas Mamalia Akuatik',
  },

  // Topik 4: Tumbuh-tumbuhan (Gerak Balas & Fotosintesis)
  {
    id: 't4-sn-tumbuhan-11',
    year: 4,
    subject: 'Sains',
    topic: 'Tumbuh-tumbuhan (Gerak Balas & Fotosintesis)',
    difficulty: 'Mudah',
    question: 'Pucuk dan daun tumbuhan tumbuh membengkok ke arah:',
    options: { A: 'Cahaya matahari', B: 'Tarikan graviti', C: 'Kegelapan', D: 'Bawah tanah' },
    correctAnswer: 'A',
    explanation: 'Pucuk tumbuhan menunjukkan fototropisme positif dengan tumbuh ke arah sumber cahaya matahari.',
    learningStandard: 'SK 4.1 Gerak Balas Tumbuhan',
  },
  {
    id: 't4-sn-tumbuhan-12',
    year: 4,
    subject: 'Sains',
    topic: 'Tumbuh-tumbuhan (Gerak Balas & Fotosintesis)',
    difficulty: 'Mudah',
    question: 'Akar tumbuhan sentiasa tumbuh ke bawah tanah mengikut gerak balas terhadap:',
    options: { A: 'Tarikan graviti dan sumber air', B: 'Cahaya lampu', C: 'Bunyi bising', D: 'Hembusan angin' },
    correctAnswer: 'A',
    explanation: 'Akar menunjukkan geotropisme dan hidrotropisme positif untuk menyerap air.',
    learningStandard: 'SK 4.1 Gerak Balas Akar',
  },
  {
    id: 't4-sn-tumbuhan-13',
    year: 4,
    subject: 'Sains',
    topic: 'Tumbuh-tumbuhan (Gerak Balas & Fotosintesis)',
    difficulty: 'Mudah',
    question: 'Daun pokok semalu menguncup apabila disentuh. Ini adalah gerak balas terhadap:',
    options: { A: 'Sentuhan', B: 'Graviti', C: 'Cahaya', D: 'Air' },
    correctAnswer: 'A',
    explanation: 'Pokok semalu bergerak balas dengan segera menguncupkan daunnya apabila disentuh.',
    learningStandard: 'SK 4.1 Gerak Balas Sentuhan',
  },
  {
    id: 't4-sn-tumbuhan-14',
    year: 4,
    subject: 'Sains',
    topic: 'Tumbuh-tumbuhan (Gerak Balas & Fotosintesis)',
    difficulty: 'Sederhana',
    question: 'Pigmen hijau di dalam daun yang berfungsi menyerap tenaga cahaya matahari dinamakan:',
    options: { A: 'Klorofil', B: 'Stoma', C: 'Glukosa', D: 'Oksigen' },
    correctAnswer: 'A',
    explanation: 'Klorofil ialah pigmen hijau yang menangkap tenaga cahaya untuk proses fotosintesis.',
    learningStandard: 'SK 4.2 Fotosintesis',
  },
  {
    id: 't4-sn-tumbuhan-15',
    year: 4,
    subject: 'Sains',
    topic: 'Tumbuh-tumbuhan (Gerak Balas & Fotosintesis)',
    difficulty: 'Sukar',
    question: 'Dua hasil utama proses fotosintesis yang sangat penting kepada hidupan di Bumi ialah:',
    options: { A: 'Glukosa (makanan/kanji) dan gas oksigen', B: 'Karbon dioksida dan air', C: 'Baja dan tanah hitam', D: 'Klorofil dan racun serangga' },
    correctAnswer: 'A',
    explanation: 'Fotosintesis menghasilkan glukosa untuk makanan dan membebaskan oksigen untuk pernafasan.',
    learningStandard: 'SK 4.2 Hasil Fotosintesis',
  },

  // Topik 5: Sifat Cahaya (Pantulan & Pembiasan)
  {
    id: 't4-sn-cahaya-11',
    year: 4,
    subject: 'Sains',
    topic: 'Sifat Cahaya (Pantulan & Pembiasan)',
    difficulty: 'Mudah',
    question: 'Cahaya bergerak mengikut:',
    options: { A: 'Garis lurus', B: 'Garis bengkak-bengkok', C: 'Bulatan spiral', D: 'Gelombang melengkung' },
    correctAnswer: 'A',
    explanation: 'Sifat utama cahaya ialah bergerak dalam garis lurus.',
    learningStandard: 'SK 5.1 Pergerakan Cahaya',
  },
  {
    id: 't4-sn-cahaya-12',
    year: 4,
    subject: 'Sains',
    topic: 'Sifat Cahaya (Pantulan & Pembiasan)',
    difficulty: 'Mudah',
    question: 'Pembentukan bayang-bayang berlaku apabila:',
    options: { A: 'Cahaya yang bergerak lurus dihalang oleh objek legap atau separa lut sinar', B: 'Cahaya dibiaskan dalam cermin', C: 'Cahaya hilang di dalam air', D: 'Objek mengeluarkan api' },
    correctAnswer: 'A',
    explanation: 'Apabila pancaran cahaya terhalang oleh objek yang tidak dapat ditembusi, kawasan gelap bayang-bayang terbentuk.',
    learningStandard: 'SK 5.1 Pembentukan Bayang-bayang',
  },
  {
    id: 't4-sn-cahaya-13',
    year: 4,
    subject: 'Sains',
    topic: 'Sifat Cahaya (Pantulan & Pembiasan)',
    difficulty: 'Mudah',
    question: 'Cermin sisi kereta menggunakan prinsip:',
    options: { A: 'Pantulan cahaya', B: 'Pembiasan cahaya', C: 'Penyerapan cahaya', D: 'Penyerakan cahaya' },
    correctAnswer: 'A',
    explanation: 'Cermin sisi kereta memantulkan imej kenderaan di belakang ke mata pemandu.',
    learningStandard: 'SK 5.2 Pantulan Cahaya',
  },
  {
    id: 't4-sn-cahaya-14',
    year: 4,
    subject: 'Sains',
    topic: 'Sifat Cahaya (Pantulan & Pembiasan)',
    difficulty: 'Sederhana',
    question: 'Batang penyedut minuman kelihatan bengkok apabila diletakkan di dalam gelas berisi air kerana:',
    options: { A: 'Pembiasan cahaya apabila bergerak melalui dua medium berbeza', B: 'Air mencairkan plastik', C: 'Pantulan cahaya dari dasar gelas', D: 'Cahaya bergerak lebih perlahan di udara' },
    correctAnswer: 'A',
    explanation: 'Pembiasan cahaya berlaku apabila arah perambatan cahaya membengkok semasa merentasi medium udara dan air.',
    learningStandard: 'SK 5.3 Pembiasan Cahaya',
  },
  {
    id: 't4-sn-cahaya-15',
    year: 4,
    subject: 'Sains',
    topic: 'Sifat Cahaya (Pantulan & Pembiasan)',
    difficulty: 'Sukar',
    question: 'Alat periskop pada kapal selam membolehkan kelasi melihat objek di permukaan laut dengan menggabungkan dua keping cermin yang dipasang pada sudut:',
    options: { A: '45 darjah', B: '90 darjah', C: '180 darjah', D: '30 darjah' },
    correctAnswer: 'A',
    explanation: 'Dua cermin satah condong 45° memantulkan sinar cahaya dua kali masuk ke mata pemerhati.',
    learningStandard: 'SK 5.2 Aplikasi Pantulan Cahaya',
  },

  // Topik 6: Tenaga & Mesin Ringkas (Perubahan Tenaga & Tuas)
  {
    id: 't4-sn-tenaga-11',
    year: 4,
    subject: 'Sains',
    topic: 'Tenaga & Mesin Ringkas (Perubahan Tenaga & Tuas)',
    difficulty: 'Mudah',
    question: 'Sumber tenaga utama yang membekalkan cahaya dan haba kepada Bumi ialah:',
    options: { A: 'Matahari', B: 'Arang batu', C: 'Bateri', D: 'Angin' },
    correctAnswer: 'A',
    explanation: 'Matahari adalah sumber tenaga primer dan terbesar di Sistem Suria.',
    learningStandard: 'SK 6.1 Sumber Tenaga',
  },
  {
    id: 't4-sn-tenaga-12',
    year: 4,
    subject: 'Sains',
    topic: 'Tenaga & Mesin Ringkas (Perubahan Tenaga & Tuas)',
    difficulty: 'Mudah',
    question: 'Apakah perubahan bentuk tenaga yang berlaku apabila televisyen dihidupkan?',
    options: { A: 'Tenaga elektrik → Tenaga cahaya + Tenaga bunyi', B: 'Tenaga kimia → Tenaga kinetik', C: 'Tenaga keupayaan → Tenaga haba', D: 'Tenaga suria → Tenaga nuklear' },
    correctAnswer: 'A',
    explanation: 'Televisyen menukar tenaga elektrik kepada paparan skrin (cahaya) dan pembesar suara (bunyi).',
    learningStandard: 'SK 6.1 Perubahan Bentuk Tenaga',
  },
  {
    id: 't4-sn-tenaga-13',
    year: 4,
    subject: 'Sains',
    topic: 'Tenaga & Mesin Ringkas (Perubahan Tenaga & Tuas)',
    difficulty: 'Mudah',
    question: 'Antara sumber tenaga berikut, yang manakah merupakan Sumber Tenaga Boleh Baharu?',
    options: { A: 'Tenaga suria, angin dan hidro', B: 'Petroleum dan gas asli', C: 'Arang batu', D: 'Uranium' },
    correctAnswer: 'A',
    explanation: 'Tenaga boleh baharu seperti matahari, angin dan air terjun tidak akan habis diguna.',
    learningStandard: 'SK 6.1 Tenaga Boleh Baharu',
  },
  {
    id: 't4-sn-tenaga-14',
    year: 4,
    subject: 'Sains',
    topic: 'Tenaga & Mesin Ringkas (Perubahan Tenaga & Tuas)',
    difficulty: 'Sederhana',
    question: 'Tiga komponen utama dalam sistem tuas ialah:',
    options: { A: 'Fulkrum, beban dan daya', B: 'Roda, gandar dan gear', C: 'Tali, takal dan paku', D: 'Skru, baji dan satah' },
    correctAnswer: 'A',
    explanation: 'Sistem tuas terdiri daripada fulkrum (titik sokongan), beban dan daya.',
    learningStandard: 'SK 7.1 Sistem Tuas',
  },
  {
    id: 't4-sn-tenaga-15',
    year: 4,
    subject: 'Sains',
    topic: 'Tenaga & Mesin Ringkas (Perubahan Tenaga & Tuas)',
    difficulty: 'Sukar',
    question: 'Semakin dekat kedudukan fulkrum dengan beban, semakin:',
    options: { A: 'Sedikit daya yang diperlukan untuk mengangkat beban tersebut', B: 'Banyak daya yang diperlukan', C: 'Berat beban menjadi berlipat ganda', D: 'Sukar tuas digerakkan' },
    correctAnswer: 'A',
    explanation: 'Mendekatkan fulkrum kepada beban memanjangkan lengan daya, membolehkan beban diangkat dengan daya yang minimum.',
    learningStandard: 'SK 7.1 Prinsip Kerja Tuas',
  },
];

const allSn4 = [...SAINS_TAHUN_4_QUESTIONS, ...snExtra];
fs.writeFileSync('src/data/sainsTahun4.ts', `import { QuizQuestion } from '../types';\n\nexport const SAINS_TAHUN_4_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allSn4, null, 2)};\n`, 'utf8');
console.log(`Updated Sains Tahun 4: total ${allSn4.length} questions.`);

// =========================================================================
// 3. EXPAND ENGLISH TAHUN 4 (+5 questions per topic = +20 questions)
// =========================================================================
const biExtra: QuizQuestion[] = [
  // Topik 1: Past Simple Tense
  {
    id: 't4-bi-topik1-11',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Past Simple Tense (Regular & Irregular)',
    subtopic: 'Irregular Past Tense',
    difficulty: 'Mudah',
    question: 'Last Friday, our teacher _______ us an exciting story about Hang Tuah.',
    options: { A: 'told', B: 'tells', C: 'telling', D: 'tell' },
    correctAnswer: 'A',
    explanation: 'The past tense of "tell" is the irregular form "told".',
    learningStandard: 'CEFR A2 Irregular Verbs',
  },
  {
    id: 't4-bi-topik1-12',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Past Simple Tense (Regular & Irregular)',
    subtopic: 'Negative Past Simple',
    difficulty: 'Sederhana',
    question: 'Adam _______ eat any spicy curry last night because he had a tummy ache.',
    options: { A: 'didn\'t', B: 'doesn\'t', C: 'don\'t', D: 'wasn\'t' },
    correctAnswer: 'A',
    explanation: 'Use "didn\'t" + base form verb ("eat") for negative past simple statements.',
    learningStandard: 'CEFR A2 Negative Past Simple',
  },
  {
    id: 't4-bi-topik1-13',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Past Simple Tense (Regular & Irregular)',
    subtopic: 'Past Question Formation',
    difficulty: 'Sederhana',
    question: '"Did you _______ your bicycle in the park yesterday?" "Yes, I did."',
    options: { A: 'ride', B: 'rode', C: 'riding', D: 'rides' },
    correctAnswer: 'A',
    explanation: 'After the auxiliary "Did", use the base form of the main verb ("ride").',
    learningStandard: 'CEFR A2 Past Simple Questions',
  },
  {
    id: 't4-bi-topik1-14',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Past Simple Tense (Regular & Irregular)',
    subtopic: 'Past of Buy (Bought)',
    difficulty: 'Mudah',
    question: 'Aunt Salmah _______ a new dictionary for her daughter yesterday.',
    options: { A: 'bought', B: 'buyed', C: 'buys', D: 'buying' },
    correctAnswer: 'A',
    explanation: 'The past simple of "buy" is "bought".',
    learningStandard: 'CEFR A2 Irregular Verbs',
  },
  {
    id: 't4-bi-topik1-15',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Past Simple Tense (Regular & Irregular)',
    subtopic: 'Past Narrative Context KBAT',
    difficulty: 'Sukar',
    question: 'When the loud thunderstorm started, the frightened kitten quickly _______ under the wooden sofa.',
    options: { A: 'hid', B: 'hides', C: 'hide', D: 'hiding' },
    correctAnswer: 'A',
    explanation: '"Hid" is the past tense form of "hide", matching the past narrative context ("started").',
    learningStandard: 'CEFR A2 Narrative Tenses',
  },

  // Topik 2: Comparatives & Superlatives
  {
    id: 't4-bi-topik2-11',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Comparatives & Superlatives',
    subtopic: 'Comparative with -er',
    difficulty: 'Mudah',
    question: 'Mount Kinabalu is _______ than Mount Ledang.',
    options: { A: 'higher', B: 'highest', C: 'more high', D: 'high' },
    correctAnswer: 'A',
    explanation: 'When comparing two mountains with short adjective "high", add -er: higher than.',
    learningStandard: 'CEFR A2 Comparatives',
  },
  {
    id: 't4-bi-topik2-12',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Comparatives & Superlatives',
    subtopic: 'Superlative with -est',
    difficulty: 'Mudah',
    question: 'The cheetah is the _______ land animal in the entire world.',
    options: { A: 'fastest', B: 'faster', C: 'more fast', D: 'most fast' },
    correctAnswer: 'A',
    explanation: 'Use "the" + superlative with -est ("the fastest") for the maximum of all.',
    learningStandard: 'CEFR A2 Superlatives',
  },
  {
    id: 't4-bi-topik2-13',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Comparatives & Superlatives',
    subtopic: 'Comparative with "more"',
    difficulty: 'Sederhana',
    question: 'Travelling by aeroplane is _______ expensive than taking a long-distance bus.',
    options: { A: 'more', B: 'most', C: 'much', D: 'as' },
    correctAnswer: 'A',
    explanation: 'For multi-syllable adjectives like "expensive", use "more expensive than".',
    learningStandard: 'CEFR A2 Multi-syllable Comparatives',
  },
  {
    id: 't4-bi-topik2-14',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Comparatives & Superlatives',
    subtopic: 'Irregular Comparative (Good/Better)',
    difficulty: 'Mudah',
    question: 'Farhan\'s exam result this semester is _______ than last year.',
    options: { A: 'better', B: 'gooder', C: 'best', D: 'more good' },
    correctAnswer: 'A',
    explanation: 'The comparative form of "good" is the irregular form "better".',
    learningStandard: 'CEFR A2 Irregular Comparatives',
  },
  {
    id: 't4-bi-topik2-15',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Comparatives & Superlatives',
    subtopic: 'Comparative Evaluation KBAT',
    difficulty: 'Sukar',
    question: 'Plastic bottles take hundreds of years to decompose, making them _______ harmful to our ocean wildlife than biodegradable paper bags.',
    options: { A: 'far more', B: 'far most', C: 'least', D: 'much less' },
    correctAnswer: 'A',
    explanation: '"Far more harmful" emphasizes the severe comparative impact of plastic over paper.',
    learningStandard: 'CEFR A2 Degrees of Comparison',
  },

  // Topik 3: Modals & Sentence Connectors
  {
    id: 't4-bi-topik3-11',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Modals & Sentence Connectors',
    subtopic: 'Modal Should for Advice',
    difficulty: 'Mudah',
    question: 'You look very pale and tired. You _______ drink plenty of warm water and rest.',
    options: { A: 'should', B: 'mustn\'t', C: 'shouldn\'t', D: 'can\'t' },
    correctAnswer: 'A',
    explanation: '"Should" is used to give friendly advice or recommendations.',
    learningStandard: 'CEFR A2 Modals for Advice',
  },
  {
    id: 't4-bi-topik3-12',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Modals & Sentence Connectors',
    subtopic: 'Connector "Although"',
    difficulty: 'Sederhana',
    question: '_______ it was raining heavily outside, the football match continued.',
    options: { A: 'Although', B: 'Because', C: 'So', D: 'Therefore' },
    correctAnswer: 'A',
    explanation: '"Although" introduces a contrast or concession between two clauses.',
    learningStandard: 'CEFR A2 Sentence Connectors',
  },
  {
    id: 't4-bi-topik3-13',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Modals & Sentence Connectors',
    subtopic: 'Connector "Because" vs "So"',
    difficulty: 'Mudah',
    question: 'Lina woke up late this morning, _______ she missed the yellow school bus.',
    options: { A: 'so', B: 'because', C: 'although', D: 'since' },
    correctAnswer: 'A',
    explanation: '"So" introduces the result of waking up late.',
    learningStandard: 'CEFR A2 Connectors of Result',
  },
  {
    id: 't4-bi-topik3-14',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Modals & Sentence Connectors',
    subtopic: 'Modal "May" for Polite Request',
    difficulty: 'Mudah',
    question: '"Excuse me teacher, _______ I please go to the washroom?" asked Hakimi politely.',
    options: { A: 'may', B: 'must', C: 'should', D: 'would' },
    correctAnswer: 'A',
    explanation: '"May I" is the standard polite modal expression for asking permission.',
    learningStandard: 'CEFR A2 Polite Requests',
  },
  {
    id: 't4-bi-topik3-15',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Modals & Sentence Connectors',
    subtopic: 'Logical Reasoning Connectors KBAT',
    difficulty: 'Sukar',
    question: 'We must switch off electrical appliances when not in use _______ we can save energy and reduce electric bills.',
    options: { A: 'so that', B: 'although', C: 'unless', D: 'however' },
    correctAnswer: 'A',
    explanation: '"So that" indicates purpose (tujuan) for turning off appliances.',
    learningStandard: 'CEFR A2 Complex Connectors',
  },

  // Topik 4: Reading Comprehension
  {
    id: 't4-bi-topik4-11',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Reading Comprehension (Passages)',
    subtopic: 'Main Idea in Wildlife Passage',
    difficulty: 'Mudah',
    question: 'Read the short text: "Malayan tigers are endangered animals found in dense tropical jungles. They are solitary creatures and hunt deer and wild boars." What do Malayan tigers eat?',
    options: { A: 'Deer and wild boars', B: 'Grass and leaves', C: 'Fruits and berries', D: 'Small insects only' },
    correctAnswer: 'A',
    explanation: 'The passage clearly states that they hunt deer and wild boars.',
    learningStandard: 'CEFR A2 Reading Details',
  },
  {
    id: 't4-bi-topik4-12',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Reading Comprehension (Passages)',
    subtopic: 'Vocabulary in Context',
    difficulty: 'Sederhana',
    question: 'In the sentence: "The brave firefighters extinguished the blazing fire within thirty minutes," what does "extinguished" mean?',
    options: { A: 'Put out the fire', B: 'Started the fire', C: 'Watched the fire', D: 'Ran away from the fire' },
    correctAnswer: 'A',
    explanation: '"Extinguished" means putting out or stopping a fire.',
    learningStandard: 'CEFR A2 Contextual Clues',
  },
  {
    id: 't4-bi-topik4-13',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Reading Comprehension (Passages)',
    subtopic: 'Chronological Sequence',
    difficulty: 'Sederhana',
    question: 'Read the recipe steps: "First, wash the fresh lettuce. Next, slice the tomatoes into rings. Then, add a spoonful of olive oil. Finally, toss everything in a salad bowl." What is the second step?',
    options: { A: 'Slice the tomatoes into rings', B: 'Wash the lettuce', C: 'Add olive oil', D: 'Toss the salad' },
    correctAnswer: 'A',
    explanation: '"Next, slice the tomatoes into rings" is explicitly the second step.',
    learningStandard: 'CEFR A2 Sequence of Events',
  },
  {
    id: 't4-bi-topik4-14',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Reading Comprehension (Passages)',
    subtopic: 'Identifying Moral Value',
    difficulty: 'Mudah',
    question: 'In a story, Amin finds a dropped wallet with money and immediately hands it to the police station. What value does Amin demonstrate?',
    options: { A: 'Honesty and integrity', B: 'Greed', C: 'Curiosity', D: 'Bravery in battle' },
    correctAnswer: 'A',
    explanation: 'Returning lost money shows honesty and integrity.',
    learningStandard: 'CEFR A2 Character and Values',
  },
  {
    id: 't4-bi-topik4-15',
    year: 4,
    subject: 'Bahasa Inggeris',
    topic: 'Reading Comprehension (Passages)',
    subtopic: 'Deduction and Inference KBAT',
    difficulty: 'Sukar',
    question: 'Text: "Dark storm clouds gathered rapidly. Birds flew back to their nests and people hurried to fold their umbrellas and find shelter." What is most likely about to happen?',
    options: { A: 'A heavy rainstorm is about to start', B: 'The sun will shine very brightly', C: 'It will start snowing', D: 'The school bell is ringing' },
    correctAnswer: 'A',
    explanation: 'Dark clouds, birds seeking nests, and people taking shelter indicate imminent heavy rain.',
    learningStandard: 'CEFR A2 Drawing Conclusions',
  },
];

const allBi4 = [...ENGLISH_TAHUN_4_QUESTIONS, ...biExtra];
fs.writeFileSync('src/data/englishTahun4.ts', `import { QuizQuestion } from '../types';\n\nexport const ENGLISH_TAHUN_4_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allBi4, null, 2)};\n`, 'utf8');
console.log(`Updated English Tahun 4: total ${allBi4.length} questions.`);
