import * as fs from 'fs';
import { QuizQuestion } from '../src/types';

// ==========================================
// 1. BAHASA MELAYU TAHUN 3 (4 topics x 15 = 60 questions)
// ==========================================
const bmTopics = [
  'Tatabahasa & Golongan Kata',
  'Imbuhan & Pembentukan Kata',
  'Simpulan Bahasa & Seni Bahasa',
  'Pemahaman Petikan & Ayat',
];
const bmQuestions: QuizQuestion[] = [];
function addBM(t: number, q: number, sub: string, diff: 'Mudah' | 'Sederhana' | 'Sukar', quest: string, opt: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  bmQuestions.push({
    id: `bm3-t${t + 1}-${String(q).padStart(2, '0')}`,
    year: 3,
    subject: 'Bahasa Melayu',
    topic: bmTopics[t],
    subtopic: sub,
    difficulty: diff,
    question: quest,
    options: opt,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Tatabahasa & Golongan Kata
addBM(0, 1, 'Kata Ganti Nama Diri Pertama', 'Mudah', '"_______ akan menelaah pelajaran di perpustakaan bersama kawan-kawan," kata Farhan.', { A: 'Saya', B: 'Dia', C: 'Mereka', D: 'Beliau' }, 'A', '"Saya" digunakan untuk merujuk diri sendiri yang sedang bertutur.', '5.1.1 Kata ganti nama diri');
addBM(0, 2, 'Kata Ganti Nama Diri Ketiga Hormat', 'Mudah', 'Guru besar baru sahaja tiba di dewan. ________ disambut oleh guru penolong kanan.', { A: 'Beliau', B: 'Dia', C: 'Kamu', D: 'Awak' }, 'A', '"Beliau" digunakan untuk orang yang dihormati seperti guru besar.', '5.1.1 Kata ganti nama diri');
addBM(0, 3, 'Kata Ganti Nama Istana', 'Sederhana', '"_______ berasa amat sukacita melihat kemakmuran negeri ini," titah Sultan kepada para pembesar.', { A: 'Beta', B: 'Patik', C: 'Hamba', D: 'Baginda' }, 'A', '"Beta" ialah kata ganti nama diri pertama yang digunakan oleh raja atau sultan.', '5.1.1 Kata ganti nama istana');
addBM(0, 4, 'Kata Nama Khas', 'Mudah', 'Pilih ayat yang mengandungi Kata Nama Khas yang dieja dengan betul.', { A: 'Keluarga Imran bercuti di Pulau Langkawi.', B: 'Keluarga imran bercuti di pulau langkawi.', C: 'Keluarga Imran bercuti di pulau Langkawi.', D: 'Keluarga Imran bercuti di Pulau langkawi.' }, 'A', 'Kata nama khas bagi orang dan tempat mesti ditulis dengan huruf besar pada setiap perkataan.', '5.1.1 Kata nama khas');
addBM(0, 5, 'Kata Adjektif Sifat', 'Mudah', 'Murid yang ________ selalu mengulang kaji pelajaran sehingga mendapat keputusan cemerlang.', { A: 'rajin', B: 'malas', C: 'lemah', D: 'lalai' }, 'A', '"Rajin" menggambarkan sifat tekun dan bersungguh-sungguh.', '5.1.3 Kata adjektif sifat');
addBM(0, 6, 'Kata Adjektif Pancaindera Bau', 'Mudah', 'Ibu menanak nasi lemak yang mengeluarkan bau sangat ________.', { A: 'wangi', B: 'bising', C: 'kasar', D: 'kelat' }, 'A', '"Wangi" ialah kata adjektif pancaindera bau bagi makanan yang enak.', '5.1.3 Kata adjektif pancaindera');
addBM(0, 7, 'Kata Adjektif Pancaindera Rasa', 'Mudah', 'Mangga muda yang dipetik oleh ayah di belakang rumah itu berasa ________.', { A: 'masam', B: 'pahit', C: 'manis', D: 'pedas' }, 'A', 'Mangga muda mempunyai rasa masam.', '5.1.3 Kata adjektif rasa');
addBM(0, 8, 'Kata Sendi Nama "di"', 'Mudah', 'Pak Cik Razak sedang berkebun ________ tepi rumahnya.', { A: 'di', B: 'ke', C: 'dari', D: 'daripada' }, 'A', 'Kata sendi "di" menunjukkan tempat berada.', '5.1.4 Kata sendi nama');
addBM(0, 9, 'Kata Sendi Nama "dari" dan "daripada"', 'Sederhana', 'Puan Maria menerima bungkusan hadiah itu ________ kakaknya di Sarawak.', { A: 'daripada', B: 'dari', C: 'pada', D: 'kepada' }, 'A', '"Daripada" digunakan untuk punca orang, institusi, atau perbandingan.', '5.1.4 Kata sendi nama daripada');
addBM(0, 10, 'Kata Hubung Gabungan', 'Mudah', 'Hakim suka bermain badminton ________ adiknya gemar berenang.', { A: 'tetapi', B: 'atau', C: 'kerana', D: 'supaya' }, 'A', '"Tetapi" menghubungkan dua maklumat yang bertentangan.', '5.1.4 Kata hubung gabungan');
addBM(0, 11, 'Kata Hubung Pancangan', 'Sederhana', 'Kita mesti mencuci tangan dengan sabun ________ terhindar daripada kuman.', { A: 'supaya', B: 'sambil', C: 'lalu', D: 'tetapi' }, 'A', '"Supaya" menyatakan tujuan sesuatu tindakan dilakukan.', '5.1.4 Kata hubung pancangan keterangan');
addBM(0, 12, 'Kata Tanya', 'Mudah', '"________ nama kucing comel berbulu putih itu?" tanya Dania kepada Aina.', { A: 'Siapakah', B: 'Apakah', C: 'Berapakah', D: 'Bagaimanakah' }, 'B', '"Apakah" digunakan untuk bertanyakan nama binatang atau benda.', '5.1.4 Kata tanya');
addBM(0, 13, 'Penjodoh Bilangan', 'Mudah', 'Ibu menghidangkan beberapa ________ kek coklat untuk tetamu yang hadir.', { A: 'potong', B: 'biji', C: 'keping', D: 'batang' }, 'A', '"Potong" ialah penjodoh bilangan untuk benda yang dipotong daripada saiz besar.', '5.1.1 Penjodoh bilangan');
addBM(0, 14, 'Penjodoh Bilangan "utas"', 'Sederhana', 'Ayah menghadiahkan se________ rantai emas sempena hari lahir ibu.', { A: 'utas', B: 'keping', C: 'pucuk', D: 'bentuk' }, 'A', '"Utas" digunakan untuk benda yang panjang dan berurai seperti rantai atau tali.', '5.1.1 Penjodoh bilangan');
addBM(0, 15, 'Sintaksis Ayat KBAT', 'Sukar', 'Pilih ayat majmuk yang gramatis berdasarkan situasi amalan menjaga kebersihan.', { A: 'Murid-murid membersihkan kelas supaya persekitaran pembelajaran menjadi selesa.', B: 'Murid-murid membersihkan kelas tetapi persekitaran pembelajaran menjadi selesa.', C: 'Murid-murid membersihkan kelas atau persekitaran pembelajaran menjadi selesa.', D: 'Murid-murid membersihkan kelas lalu persekitaran pembelajaran menjadi selesa.' }, 'A', 'Kata hubung "supaya" menghubungkan tindakan dan tujuan dengan tepat.', '5.3.1 Membina ayat majmuk');

// Topic 2: Imbuhan & Pembentukan Kata
addBM(1, 1, 'Awalan meN- (me-)', 'Mudah', 'Pilih perkataan berimbuhan awalan yang betul bagi kata dasar "lukis":', { A: 'melukis', B: 'menlukis', C: 'memlukis', D: 'menglukis' }, 'A', 'Kata dasar bermula huruf "l" menerima awalan "me-" menjadi "melukis".', '5.2.1 Imbuhan awalan meN-');
addBM(1, 2, 'Awalan meN- (mem-)', 'Mudah', 'Kata dasar "bantu" apabila menerima awalan meN- menjadi:', { A: 'membantu', B: 'menbantu', C: 'mebantu', D: 'mengbantu' }, 'A', 'Kata dasar huruf "b" bergabung dengan awalan "mem-" menjadi "membantu".', '5.2.1 Imbuhan awalan mem-');
addBM(1, 3, 'Awalan meN- (men-)', 'Mudah', 'Ayah sedang ________ pokok bunga yang rimbun di hadapan rumah.', { A: 'mencantas', B: 'mecantas', C: 'mengcantas', D: 'memcantas' }, 'A', 'Kata dasar "cantas" (huruf c) bergabung dengan awalan "men-".', '5.2.1 Imbuhan awalan men-');
addBM(1, 4, 'Awalan meN- (meng-)', 'Mudah', 'Ibu ________ air di dalam cerek elektrik di dapur.', { A: 'memasak', B: 'menmasak', C: 'mememasak', D: 'mengmasak' }, 'A', 'Kata dasar "masak" menerima awalan "me-" menjadi "memasak".', '5.2.1 Imbuhan awalan me-');
addBM(1, 5, 'Awalan meN- (meny-)', 'Sederhana', 'Kata dasar "sapu" menerima awalan meN- berubah menjadi:', { A: 'menyapu', B: 'mensapu', C: 'memsapu', D: 'mesapu' }, 'A', 'Huruf "s" pada kata dasar luluh dan digantikan dengan "meny-".', '5.2.1 Imbuhan awalan meny-');
addBM(1, 6, 'Awalan beR-', 'Mudah', 'Adik suka ________ kemeja berwarna biru.', { A: 'berbaju', B: 'membaju', C: 'terbaju', D: 'dibaju' }, 'A', 'Awalan "ber-" membawa maksud memakai atau memiliki: berbaju.', '5.2.1 Imbuhan awalan ber-');
addBM(1, 7, 'Awalan teR-', 'Sederhana', 'Kotak berat itu tidak ________ oleh adik yang masih kecil.', { A: 'terangkat', B: 'berangkat', C: 'mengangkat', D: 'diangkat' }, 'A', '"Terangkat" bermaksud keupayaan untuk mengangkat.', '5.2.1 Imbuhan awalan ter-');
addBM(1, 8, 'Awalan peN-', 'Sederhana', 'Orang yang memandu kenderaan bas atau kereta dipanggil:', { A: 'pemandu', B: 'pememandu', C: 'penmandu', D: 'terpandu' }, 'A', 'Awalan "pe-" pada "pandu" menghasilkan kata nama "pemandu".', '5.2.1 Imbuhan peN-');
addBM(1, 9, 'Akhiran -an', 'Mudah', 'Pilih perkataan berimbuhan akhiran -an yang betul:', { A: 'makanan', B: 'memakan', C: 'termakan', D: 'pemakan' }, 'A', 'Kata dasar "makan" + akhiran "-an" = "makanan".', '5.2.1 Imbuhan akhiran -an');
addBM(1, 10, 'Akhiran -kan', 'Mudah', '"Tolong ________ pintu bilik itu perlahan-lahan," pesan abang.', { A: 'tutupkan', B: 'penutup', C: 'tertutup', D: 'berpenutup' }, 'A', '"Tutupkan" ialah kata kerja perintah berakhiran "-kan".', '5.2.1 Imbuhan akhiran -kan');
addBM(1, 11, 'Kata Ganda Penuh', 'Mudah', 'Taman rekreasi itu dipenuhi oleh kanak-kanak yang riang berkejaran bersama ________.', { A: 'kawan-kawan', B: 'kawan-kawanan', C: 'berkawan-kawan', D: 'kekawan' }, 'A', '"Kawan-kawan" ialah kata ganda penuh yang menunjukkan maksud ramai.', '5.2.2 Kata ganda penuh');
addBM(1, 12, 'Kata Ganda Separa', 'Sederhana', 'Apakah kata ganda separa bagi kata dasar "kuda"?', { A: 'kekuda', B: 'kuda-kuda', C: 'kuda-kudaan', D: 'berkuda' }, 'A', 'Kata ganda separa bagi "kuda" ialah "kekuda".', '5.2.2 Kata ganda separa');
addBM(1, 13, 'Kata Majmuk Bebas', 'Mudah', 'Pilih kata majmuk yang tergolong dalam jenis kata majmuk mantap:', { A: 'kerjasama', B: 'beg sekolah', C: 'papan tulis', D: 'buku latihan' }, 'A', '"Kerjasama" ialah kata majmuk yang dieja secara bercantum (mantap).', '5.2.3 Kata majmuk');
addBM(1, 14, 'Imbuhan Apitan', 'Sederhana', 'Penduduk kampung bekerjasama untuk ________ jambatan kayu yang reput itu.', { A: 'membaiki', B: 'membaikkan', C: 'perbaiki', D: 'terbaiki' }, 'A', 'Kata kerja terbitan yang tepat ialah "membaiki".', '5.2.1 Imbuhan awalan mem-');
addBM(1, 15, 'Membina Kata Terbitan KBAT', 'Sukar', 'Pilih padanan imbuhan awalan yang betul bagi kata dasar "kunci" dan fungsinya dalam ayat pasif.', { A: 'Pintu pagar itu sudah dikunci oleh ayah sebelum tidur.', B: 'Pintu pagar itu sudah berkunci oleh ayah sebelum tidur.', C: 'Pintu pagar itu sudah mengunci oleh ayah sebelum tidur.', D: 'Pintu pagar itu sudah terkuncikan oleh ayah sebelum tidur.' }, 'A', 'Awalan "di-" digunakan untuk kata kerja pasif dengan pelaku ketiga: "dikunci oleh ayah".', '5.2.1 Imbuhan awalan pasif');

// Topic 3: Simpulan Bahasa & Seni Bahasa
addBM(2, 1, 'Ringan Tulang', 'Mudah', 'Siti sangat disukai oleh jiran tetangganya kerana dia seorang yang ringan tulang. "Ringan tulang" bermaksud:', { A: 'Rajin bekerja atau menolong', B: 'Tulang yang tidak berat', C: 'Kurus dan lemah', D: 'Cepat berasa letih' }, 'A', '"Ringan tulang" bermaksud rajin dan suka membantu orang lain.', '4.1.1 Simpulan bahasa');
addBM(2, 2, 'Berat Mulut', 'Mudah', 'Aiman seorang yang pendiam dan jarang bercakap dengan orang baharu dikenali. Sikap Aiman dipanggil:', { A: 'Berat mulut', B: 'Mulut tempayan', C: 'Ringan mulut', D: 'Kaki ayam' }, 'A', '"Berat mulut" bermaksud orang yang pendiam dan sukar diajak bercakap.', '4.1.1 Simpulan bahasa');
addBM(2, 3, 'Buah Tangan', 'Mudah', 'Ibu membawa pelbagai jenis kuih-muih sebagai buah tangan ketika menziarahi Mak Long. "Buah tangan" bermaksud:', { A: 'Hadiah atau cenderamata yang dibawa semasa melawat', B: 'Buah-buahan yang dipetik dengan tangan', C: 'Lukisan pada tapak tangan', D: 'Barang yang rosak' }, 'A', '"Buah tangan" bermaksud pemberian atau cenderahati semasa berkunjung.', '4.1.1 Simpulan bahasa');
addBM(2, 4, 'Hati Waja', 'Sederhana', 'Walaupun menghadapi kesukaran semasa mendaki bukit, para pengakap tetap berhati waja. "Hati waja" bermaksud:', { A: 'Mempunyai semangat kental dan tidak mudah putus asa', B: 'Hati yang keras seperti besi', C: 'Sombong dan tidak mendengar nasihat', D: 'Cepat marah dan merajuk' }, 'A', '"Hati waja" bermaksud bersemangat tinggi dan tabah menghadapi cabaran.', '4.1.1 Simpulan bahasa');
addBM(2, 5, 'Kaki Ayam', 'Mudah', 'Adik ditegur oleh ibu kerana berjalan di halaman rumah tanpa memakai selipar seperti kaki ayam. "Kaki ayam" bermaksud:', { A: 'Tidak memakai kasut atau selipar', B: 'Kaki yang mempunyai cakar', C: 'Pandai bermain bola sepak', D: 'Berjalan dengan sangat laju' }, 'A', '"Kaki ayam" bermaksud berjalan tanpa alas kaki atau kasut.', '4.1.1 Simpulan bahasa');
addBM(2, 6, 'Mandi Peluh', 'Mudah', 'Para petani bekerja sehingga mandi peluh di bendang sawah. "Mandi peluh" bermaksud:', { A: 'Bekerja dengan bersungguh-sungguh dan kuat', B: 'Mandi air telaga yang panas', C: 'Badan yang kotor dengan lumpur', D: 'Berenang di dalam sungai' }, 'A', '"Mandi peluh" bermaksud basah kuyup akibat bekerja dengan gigih.', '4.1.1 Simpulan bahasa');
addBM(2, 7, 'Ulat Buku', 'Mudah', 'Haziq menghabiskan cuti hujung minggunya dengan membaca pelbagai ensiklopedia di bilik bacaan. Haziq digelar:', { A: 'Ulat buku', B: 'Kaki bangku', C: 'Kera sumbang', D: 'Telinga kuali' }, 'A', '"Ulat buku" bermaksud orang yang amat gemar membaca buku.', '4.1.1 Simpulan bahasa');
addBM(2, 8, 'Hidung Tinggi', 'Mudah', 'Sikap hidung tinggi hendaklah dijauhi kerana dibenci oleh rakan-rakan. "Hidung tinggi" bermaksud:', { A: 'Sombong atau meninggi diri', B: 'Hidung yang mancung', C: 'Suka berlagak pandai', D: 'Mudah menghidu bau' }, 'A', '"Hidung tinggi" bermaksud sombong dan angkuh.', '4.1.1 Simpulan bahasa');
addBM(2, 9, 'Pantun Nasihat 4 Kerat', 'Sederhana', 'Lengkapkan rima pembayang pantun nasihat berikut:\nPulau Pandan jauh ke tengah,\nGunung Daik bercabang tiga;\nHancur badan dikandung tanah,\n____________________', { A: 'Budi yang baik dikenang juga', B: 'Hati susah menjadi gembira', C: 'Mari kita belajar bersama', D: 'Pohon mangga berbuah lebat' }, 'A', 'Pantun empat kerat klasik: "Budi yang baik dikenang juga" berima sama dengan baris kedua "tiga".', '4.2.1 Melafazkan pantun 4 kerat');
addBM(2, 10, 'Ciri Rima Pantun', 'Sederhana', 'Apakah skema rima akhir yang betul bagi pantun empat kerat?', { A: 'a-b-a-b', B: 'a-a-a-a', C: 'a-b-b-a', D: 'a-a-b-b' }, 'A', 'Pantun empat kerat tradisional mempunyai skema rima akhir berselang iaitu a-b-a-b.', '4.2.1 Ciri-ciri pantun');
addBM(2, 11, 'Maksud Syair', 'Sederhana', 'Syair yang melagukan nasihat berguna tentang adab belajar bertujuan untuk:', { A: 'Memberi pengajaran dan teladan yang baik kepada murid', B: 'Menakut-nakutkan pendengar', C: 'Menghiburkan haiwan peliharaan', D: 'Menyanyi tanpa irama' }, 'A', 'Syair nasihat menyampaikan mesej teladan dan nilai murni secara berlagu.', '4.2.2 Melagukan syair');
addBM(2, 12, 'Simpulan Bahasa "Kaki Bangku"', 'Mudah', 'Seseorang yang tidak pandai atau kekok bermain bola sepak digelar:', { A: 'Kaki bangku', B: 'Kaki botol', C: 'Kaki ayam', D: 'Kaki lima' }, 'A', '"Kaki bangku" merujuk kepada orang yang tidak tahu bermain bola.', '4.1.1 Simpulan bahasa');
addBM(2, 13, 'Ambil Berat', 'Mudah', 'Cikgu Rahman selalu mengambil berat tentang kebajikan murid-muridnya. "Ambil berat" bermaksud:', { A: 'Memberi perhatian dan kasih sayang', B: 'Menimbang berat badan', C: 'Membawa barang yang berat', D: 'Mendenda murid yang lewat' }, 'A', '"Ambil berat" bermaksud prihatin dan memberi perhatian.', '4.1.1 Simpulan bahasa');
addBM(2, 14, 'Cahaya Mata', 'Mudah', 'Puan Rohani baru sahaja melahirkan seorang cahaya mata lelaki. "Cahaya mata" bermaksud:', { A: 'Anak kandung', B: 'Cermin mata', C: 'Lampu suluh', D: 'Biji mata' }, 'A', '"Cahaya mata" ialah simpulan bahasa untuk anak.', '4.1.1 Simpulan bahasa');
addBM(2, 15, 'Aplikasi Simpulan Bahasa KBAT', 'Sukar', 'Amirul tidak berkecil hati walaupun kalah dalam pertandingan bercerita, sebaliknya dia berlatih lebih gigih. Sikap Amirul menunjukkan dia:', { A: 'Berjiwa besar dan tidak mudah berputus asa', B: 'Bermuka dua di hadapan guru', C: 'Keras kepala dan enggan mengaku kalah', D: 'Makan angin bersama keluarganya' }, 'A', '"Berjiwa besar" menunjukkan sikap matang, reda dan gigih berusaha.', '4.1.1 Aplikasi simpulan bahasa');

// Topic 4: Pemahaman Petikan & Ayat
addBM(3, 1, 'Petikan Gotong-royong', 'Mudah', 'Petikan: "Pada hari Ahad yang lalu, penduduk Kampung Indah mengadakan aktiviti gotong-royong. Mereka membersihkan longkang dan menebas semak-samun."\nApakah aktiviti yang dijalankan oleh penduduk Kampung Indah?', { A: 'Aktiviti gotong-royong membersihkan kawasan kampung', B: 'Pertandingan memasak kuih tradisional', C: 'Hari sukaneka sekolah', D: 'Majlis jamuan hari raya' }, 'A', 'Petikan dengan jelas menyatakan penduduk mengadakan aktiviti gotong-royong.', '2.2.1 Membaca dan memahami maklumat');
addBM(3, 2, 'Tujuan Gotong-royong', 'Mudah', 'Mengapakah longkang dan semak-samun dibersihkan oleh penduduk kampung?', { A: 'Untuk memusnahkan tempat pembiakan nyamuk aedes dan menjaga kebersihan', B: 'Supaya rumput tumbuh lebih tinggi', C: 'Untuk menangkap ikan sungai', D: 'Kerana tiada kerja lain di rumah' }, 'A', 'Membersihkan persekitaran mengelakkan nyamuk aedes membiak dan mencegah demam denggi.', '2.2.1 Menjana idea tersirat');
addBM(3, 3, 'Hari Aktiviti', 'Mudah', 'Bilakah aktiviti gotong-royong tersebut diadakan?', { A: 'Hari Ahad yang lalu', B: 'Hari Isnin', C: 'Hari Jumaat', D: 'Hari Sabtu malam' }, 'A', 'Petikan menyebut: "Pada hari Ahad yang lalu...".', '2.2.1 Membaca maklumat tersurat');
addBM(3, 4, 'Petikan Kesihatan Diri', 'Mudah', 'Petikan: "Kita perlu tidur sekurang-kurangnya lapan jam sehari. Tidur yang cukup membolehkan badan kita berehat dan kembali segar untuk belajar keesokan harinya."\nBerapakah tempoh masa tidur yang disarankan?', { A: 'Sekurang-kurangnya lapan jam sehari', B: 'Dua jam sehari', C: 'Dua belas jam tanpa henti', D: 'Hanya pada waktu petang' }, 'A', 'Berdasarkan petikan, manusia disarankan tidur sekurang-kurangnya 8 jam.', '2.2.1 Membaca petikan prosa');
addBM(3, 5, 'Kebaikan Tidur Cukup', 'Mudah', 'Apakah faedah tidur yang mencukupi menurut petikan?', { A: 'Badan berehat dan kembali segar untuk belajar', B: 'Mendapat banyak mimpi indah', C: 'Boleh bangun lewat ke sekolah', D: 'Menjadikan badan cepat gemuk' }, 'A', 'Tidur cukup memulihkan tenaga fizikal dan kecergasan minda murid.', '2.2.1 Mengesan idea utama');
addBM(3, 6, 'Menyusun Urutan Peristiwa', 'Sederhana', 'Susun urutan amalan kebersihan sebelum makan dengan betul:\n(I) Mengelap tangan dengan tuala kering\n(II) Membaca doa sebelum makan\n(III) Membasuh tangan menggunakan sabun', { A: '(III), (I), (II)', B: '(I), (II), (III)', C: '(II), (III), (I)', D: '(III), (II), (I)' }, 'A', 'Basuh tangan dulu, keringkan dengan tuala, kemudian baca doa sebelum makan.', '3.2.1 Menyusun urutan idea');
addBM(3, 7, 'Nilai Murni Kerjasama', 'Mudah', 'Nilai murni yang ditunjukkan apabila masyarakat bekerjasama membersihkan balai raya ialah:', { A: 'Kerjasama dan perpaduan', B: 'Keberanian', C: 'Berjimat cermat', D: 'Kejujuran' }, 'A', 'Bekerjasama bergotong-royong mencerminkan nilai kerjasama dan perpaduan kaum.', '2.3.1 Menyatakan nilai murni');
addBM(3, 8, 'Ayat Tunggal Pola FN+FK', 'Sederhana', 'Antara ayat berikut, yang manakah merupakan pola Frasa Nama + Frasa Kerja (FN + FK)?', { A: 'Kakak sedang menjahit baju kurung.', B: 'Baju kurung itu sangat cantik.', C: 'Ibu saya seorang jururawat.', D: 'Rumah nenek di tepi sawah.' }, 'A', '"Kakak" (FN) + "sedang menjahit baju kurung" (FK).', '5.3.1 Pola ayat dasar');
addBM(3, 9, 'Tanda Seru (!)', 'Mudah', 'Pilih ayat seruan yang menggunakan tanda baca dengan betul:', { A: 'Wah, cantiknya pemandangan di atas bukit ini!', B: 'Wah cantiknya pemandangan di atas bukit ini?', C: 'Wah, cantiknya pemandangan di atas bukit ini.', D: 'Wah cantiknya pemandangan di atas bukit ini:' }, 'A', 'Ayat seruan bermula kata seru, diikuti tanda koma dan diakhiri tanda seru (!).', '5.1.4 Tanda seru');
addBM(3, 10, 'Tanda Tanya (?)', 'Mudah', 'Pilih ayat tanya yang tepat dengan tanda baca yang betul:', { A: 'Di manakah kamu meletakkan kamus Dewan itu?', B: 'Di manakah kamu meletakkan kamus Dewan itu.', C: 'Di manakah kamu meletakkan kamus Dewan itu!', D: 'Di manakah kamu meletakkan kamus Dewan itu,' }, 'A', 'Ayat tanya diakhiri dengan tanda soal (?).', '5.1.4 Tanda baca ayat tanya');
addBM(3, 11, 'Kosa Kata Sinar Suria', 'Mudah', 'Perkataan "suria" dalam frasa "cahaya suria yang terang" membawa maksud:', { A: 'Matahari', B: 'Bulan', C: 'Bintang', D: 'Awan' }, 'A', '"Suria" ialah perkataan puitis yang bermaksud matahari.', '2.1.2 Kosa kata');
addBM(3, 12, 'Kosa Kata Fauna', 'Mudah', '"Fauna" di dalam hutan merujuk kepada kumpulan hidupan:', { A: 'Haiwan', B: 'Tumbuh-tumbuhan', C: 'Batuan', D: 'Sungai' }, 'A', '"Fauna" bermaksud dunia haiwan, manakala "flora" ialah tumbuhan.', '2.1.2 Kosa kata sains dalam BM');
addBM(3, 13, 'Nilai Kasih Sayang', 'Mudah', 'Sikap Aiman yang memelihara anak kucing terbiar dan memberinya makanan menunjukkan nilai:', { A: 'Kasih sayang dan belas kasihan terhadap haiwan', B: 'Berani mencuba', C: 'Keadilan', D: 'Berdikari' }, 'A', 'Menyayangi binatang ialah amalan nilai kasih sayang terpuji.', '2.3.1 Nilai murni');
addBM(3, 14, 'Ayat Majmuk Kompleks', 'Sederhana', 'Pilih ayat majmuk yang paling tepat untuk menggabungkan dua ayat ini:\n"Farid mengemas beg sekolahnya."\n"Farid masuk tidur."', { A: 'Farid mengemas beg sekolahnya sebelum dia masuk tidur.', B: 'Farid mengemas beg sekolahnya tetapi dia masuk tidur.', C: 'Farid mengemas beg sekolahnya jika dia masuk tidur.', D: 'Farid mengemas beg sekolahnya atau dia masuk tidur.' }, 'A', 'Kata hubung "sebelum" menunjukkan urutan masa aktiviti yang logik.', '5.3.1 Membina ayat majmuk');
addBM(3, 15, 'Menganalisis Petikan KBAT', 'Sukar', 'Petikan: "Kempen Kitar Semula di Sekolah Kebangsaan Melati berjaya mengumpulkan lebih 500 kilogram surat khabar lama dan botol plastik dalam masa seminggu."\nApakah kesimpulan yang boleh dibuat tentang warga sekolah tersebut?', { A: 'Warga sekolah mempunyai kesedaran tinggi terhadap pemeliharaan alam sekitar', B: 'Warga sekolah gemar mengumpul sampah di dalam kelas', C: 'Warga sekolah kehabisan buku teks untuk dibaca', D: 'Warga sekolah ingin menjual surat khabar untuk membeli makanan ringan' }, 'A', 'Kejayaan mengumpul 500kg bahan kitar semula membuktikan komitmen tinggi warga sekolah.', '2.2.1 KBAT membuat kesimpulan petikan');

fs.writeFileSync('src/data/bahasaMelayuTahun3.ts', `import { QuizQuestion } from '../types';\n\nexport const BAHASA_MELAYU_TAHUN_3_QUESTIONS: QuizQuestion[] = ${JSON.stringify(bmQuestions, null, 2)};\n`, 'utf8');
console.log(`Generated ${bmQuestions.length} questions for Bahasa Melayu Tahun 3.`);
