import * as fs from 'fs';
import { QuizQuestion } from '../src/types';

// ==========================================
// 1. SAINS TAHUN 3 (5 topics x 15 = 75 questions)
// ==========================================
const snT3Topics = [
  'Manusia (Gigi & Pencernaan)',
  'Haiwan & Tabiat Pemakanan',
  'Tumbuhan & Cara Pembiakan',
  'Ketumpatan, Asid & Alkali',
  'Sistem Suria & Takal',
];

const snT3Questions: QuizQuestion[] = [];
function addSn3(topicIdx: number, qIdx: number, subtopic: string, difficulty: 'Mudah' | 'Sederhana' | 'Sukar', question: string, options: { A: string; B: string; C: string; D: string }, correctAnswer: 'A' | 'B' | 'C' | 'D', explanation: string, learningStandard: string) {
  snT3Questions.push({
    id: `sn3-t${topicIdx + 1}-${String(qIdx).padStart(2, '0')}`,
    year: 3,
    subject: 'Sains',
    topic: snT3Topics[topicIdx],
    subtopic,
    difficulty,
    question,
    options,
    correctAnswer,
    explanation,
    learningStandard,
  });
}

// Topic 1: Manusia (Gigi & Pencernaan)
addSn3(0, 1, 'Jenis Gigi', 'Mudah', 'Apakah fungsi utama gigi kacip pada manusia?', { A: 'Memotong makanan', B: 'Mengoyak makanan', C: 'Melumatkan makanan', D: 'Menghancurkan tulang' }, 'A', 'Gigi kacip berbentuk pipih tajam dan berfungsi memotong makanan.', 'SK 3.1 Jenis dan fungsi gigi');
addSn3(0, 2, 'Gigi Taring', 'Mudah', 'Gigi yang berbentuk runcing dan tajam untuk mengoyak daging ialah:', { A: 'Gigi taring', B: 'Gigi kacip', C: 'Gigi geraham kecil', D: 'Gigi geraham besar' }, 'A', 'Gigi taring berfungsi mengoyak makanan.', 'SK 3.1 Fungsi gigi taring');
addSn3(0, 3, 'Gigi Geraham', 'Mudah', 'Fungsi gigi geraham adalah untuk:', { A: 'Melumat dan menghancurkan makanan', B: 'Mengoyak makanan', C: 'Memotong makanan', D: 'Menghisap makanan' }, 'A', 'Gigi geraham mempunyai permukaan lebar untuk menghancurkan makanan.', 'SK 3.1 Fungsi gigi geraham');
addSn3(0, 4, 'Struktur Gigi', 'Mudah', 'Lapisan paling luar gigi yang paling keras berwarna putih dinamakan:', { A: 'Enamel', B: 'Dentin', C: 'Gusi', D: 'Saraf' }, 'A', 'Enamel adalah lapisan terluar gigi dan bahan terkeras dalam tubuh.', 'SK 3.1 Struktur gigi');
addSn3(0, 5, 'Bahagian Dalam Gigi', 'Sederhana', 'Bahagian gigi yang mengandungi salur darah dan saraf ialah:', { A: 'Pulpa', B: 'Enamel', C: 'Dentin', D: 'Gusi' }, 'A', 'Pulpa terletak di pusat gigi mengandungi saraf dan salur darah.', 'SK 3.1 Struktur gigi');
addSn3(0, 6, 'Set Gigi Susu', 'Mudah', 'Berapakah jumlah bilangan gigi dalam set gigi susu kanak-kanak?', { A: '20 batang gigi', B: '32 batang gigi', C: '28 batang gigi', D: '16 batang gigi' }, 'A', 'Set gigi susu mempunyai 20 batang gigi.', 'SK 3.1 Perbandingan set gigi');
addSn3(0, 7, 'Set Gigi Kekal', 'Mudah', 'Berapakah jumlah bilangan gigi dalam set gigi kekal orang dewasa?', { A: '32 batang gigi', B: '20 batang gigi', C: '30 batang gigi', D: '36 batang gigi' }, 'A', 'Set gigi kekal yang lengkap mempunyai 32 batang gigi.', 'SK 3.1 Set gigi kekal');
addSn3(0, 8, 'Kesihatan Gigi', 'Mudah', 'Apakah amalan harian yang terbaik untuk mencegah kerosakan gigi?', { A: 'Menggosok gigi sekurang-kurangnya dua kali sehari', B: 'Makan banyak gula-gula manis', C: 'Minum minuman berkarbonat setiap malam', D: 'Mengorek gigi dengan pencungkil tajam' }, 'A', 'Menggosok gigi dengan ubat gigi berfluorida membuang plak dan sisa makanan.', 'SK 3.1 Penjagaan kesihatan gigi');
addSn3(0, 9, 'Pencernaan Makanan', 'Mudah', 'Di manakah proses pencernaan makanan bermula?', { A: 'Mulut', B: 'Perut', C: 'Esofagus', D: 'Usus kecil' }, 'A', 'Pencernaan bermula di mulut di mana makanan dikunyah dan dicampur air liur.', 'SK 3.2 Proses pencernaan manusia');
addSn3(0, 10, 'Laluan Makanan', 'Sederhana', 'Tiub otot yang menghubungkan mulut ke perut dinamakan:', { A: 'Esofagus', B: 'Trakea', C: 'Usus besar', D: 'Dubur' }, 'A', 'Esofagus menolak makanan dari mulut ke dalam perut melalui pengecutan otot.', 'SK 3.2 Laluan pencernaan');
addSn3(0, 11, 'Fungsi Perut', 'Sederhana', 'Apakah peranan perut dalam sistem pencernaan?', { A: 'Mencerna makanan menjadi separa cecair dengan asid dan enzim', B: 'Menyerap air daripada sisa makanan', C: 'Mengeluarkan tinja ke luar tubuh', D: 'Memotong makanan menjadi kepingan' }, 'A', 'Perut menghadamkan makanan menggunakan jus gastrik berasid.', 'SK 3.2 Fungsi organ pencernaan');
addSn3(0, 12, 'Penyerapan Nutrien', 'Sederhana', 'Nutrien makanan yang telah dicerna diserap ke dalam salur darah di:', { A: 'Usus kecil', B: 'Mulut', C: 'Perut', D: 'Esofagus' }, 'A', 'Usus kecil menyerap nutrien daripada makanan yang tercerna.', 'SK 3.2 Penyerapan nutrien');
addSn3(0, 13, 'Penyingkiran Tinja', 'Mudah', 'Sisa makanan yang tidak tercerna keluar daripada badan melalui:', { A: 'Dubur', B: 'Mulut', C: 'Usus kecil', D: 'Pundi kencing' }, 'A', 'Sisa pepejal (tinja) disingkirkan melalui dubur.', 'SK 3.2 Penyahtinjaan');
addSn3(0, 14, 'Urutan Sistem Pencernaan', 'Sederhana', 'Susun urutan aliran makanan dalam sistem pencernaan dengan betul:', { A: 'Mulut → Esofagus → Perut → Usus kecil → Usus besar → Dubur', B: 'Mulut → Perut → Esofagus → Dubur', C: 'Mulut → Esofagus → Usus besar → Perut → Dubur', D: 'Mulut → Usus kecil → Perut → Dubur' }, 'A', 'Urutan aliran: Mulut, Esofagus, Perut, Usus kecil, Usus besar, Dubur.', 'SK 3.2 Aliran makanan semasa pencernaan');
addSn3(0, 15, 'Kesan Mengunyah Cepat KBAT', 'Sukar', 'Apakah yang akan berlaku sekiranya seseorang menelan makanan tanpa mengunyahnya dengan lumat?', { A: 'Perut terpaksa bekerja lebih keras dan boleh menyebabkan senak perut', B: 'Makanan akan dicerna lebih cepat', C: 'Gigi geraham akan cepat rosak', D: 'Nutrien diserap secara berlebihan' }, 'A', 'Mengunyah makanan secara lumat membolehkan perut mencerna makanan dengan lancar tanpa senak.', 'SK 3.2 Amalan pemakanan sihat');

// Topic 2: Haiwan & Tabiat Pemakanan
addSn3(1, 1, 'Pengelasan Herbivor', 'Mudah', 'Haiwan yang hanya makan tumbuh-tumbuhan dikelaskan sebagai:', { A: 'Herbivor', B: 'Karnivor', C: 'Omnivor', D: 'Insektivor' }, 'A', 'Herbivor ialah pemakan tumbuhan sahaja seperti lembu dan arnab.', 'SK 4.1 Tabiat pemakanan haiwan');
addSn3(1, 2, 'Contoh Karnivor', 'Mudah', 'Antara haiwan berikut, yang manakah merupakan haiwan karnivor?', { A: 'Harimau', B: 'Kambing', C: 'Gajah', D: 'Kuda' }, 'A', 'Harimau memakan daging haiwan lain, maka ia karnivor.', 'SK 4.1 Pengelasan haiwan karnivor');
addSn3(1, 3, 'Ciri Omnivor', 'Mudah', 'Haiwan omnivor ialah haiwan yang memakan:', { A: 'Tumbuh-tumbuhan dan haiwan lain', B: 'Tumbuh-tumbuhan sahaja', C: 'Bangkai sahaja', D: 'Daging sahaja' }, 'A', 'Omnivor makan kedua-dua tumbuhan dan haiwan lain seperti ayam dan beruang.', 'SK 4.1 Tabiat pemakanan omnivor');
addSn3(1, 4, 'Kegigian Herbivor', 'Sederhana', 'Haiwan herbivor seperti lembu mempunyai gigi yang khusus iaitu:', { A: 'Gigi kacip dan geraham yang berkembang untuk memotong dan mengisar rumput', B: 'Gigi taring yang sangat panjang dan tajam', C: 'Tiada sebarang gigi di dalam mulut', D: 'Hanya gigi taring sahaja' }, 'A', 'Herbivor memerlukan gigi kacip memotong rumput dan geraham mengisar.', 'SK 4.1 Kegigian haiwan');
addSn3(1, 5, 'Kegigian Karnivor', 'Sederhana', 'Haiwan karnivor seperti singa mempunyai gigi taring yang tajam dan melengkung untuk:', { A: 'Mengoyak daging mangsa', B: 'Mengisar daun hijau', C: 'Mengunyah biji benih', D: 'Menghisap nektar bunga' }, 'A', 'Gigi taring tajam berfungsi mencengkam dan mengoyak daging.', 'SK 4.1 Kegigian karnivor');
addSn3(1, 6, 'Kegigian Omnivor', 'Sederhana', 'Kera dan beruang mempunyai ketiga-tiga jenis gigi (kacip, taring, geraham) kerana:', { A: 'Memakan kedua-dua tumbuhan dan haiwan', B: 'Hanya minum susu', C: 'Memakan serangga halus sahaja', D: 'Gigi tidak berubah seumur hidup' }, 'A', 'Omnivor mempunyai struktur gigi seimbang untuk diet tumbuhan dan daging.', 'SK 4.1 Kegigian omnivor');
addSn3(1, 7, 'Tabiat Monyet', 'Mudah', 'Monyet memakan buah-buahan dan serangga kecil. Apakah kelas pemakanannya?', { A: 'Omnivor', B: 'Herbivor', C: 'Karnivor', D: 'Autotrof' }, 'A', 'Monyet makan tumbuhan dan haiwan kecil, jadi ia omnivor.', 'SK 4.1 Pengelasan pemakanan');
addSn3(1, 8, 'Tabiat Burung Helang', 'Mudah', 'Burung helang memburu anak ayam, tikus dan ikan. Burung helang ialah:', { A: 'Karnivor', B: 'Herbivor', C: 'Omnivor', D: 'Pengurai' }, 'A', 'Helang ialah pemangsa karnivor.', 'SK 4.1 Haiwan karnivor');
addSn3(1, 9, 'Tabiat Gajah', 'Mudah', 'Gajah memakan rumput, daun pokok dan buah-buahan. Gajah ialah haiwan:', { A: 'Herbivor', B: 'Karnivor', C: 'Omnivor', D: 'Pengguna tertier' }, 'A', 'Gajah ialah herbivor darat terbesar.', 'SK 4.1 Haiwan herbivor');
addSn3(1, 10, 'Perubahan Tabiat Semulajadi', 'Sederhana', 'Apakah yang akan berlaku kepada beruang kutub jika kawasan kutub kehabisan anjing laut?', { A: 'Beruang terpaksa mencari sumber makanan lain seperti bangkai ikan atau tumbuhan', B: 'Beruang akan terus membesar', C: 'Beruang tidak perlu makan lagi', D: 'Gigi beruang akan bertukar menjadi gigi kacip lembu' }, 'A', 'Haiwan mungkin mengubah diet secara oportunis demi kelangsungan hidup.', 'SK 4.1 Penyesuaian tabiat makan');
addSn3(1, 11, 'Tabiat Ayam', 'Mudah', 'Ayam mematuk bijirin jagung dan juga memakan cacing tanah. Ayam ialah:', { A: 'Omnivor', B: 'Herbivor', C: 'Karnivor', D: 'Parasit' }, 'A', 'Ayam memakan bijirin (tumbuhan) dan cacing (haiwan), menjadikannya omnivor.', 'SK 4.1 Tabiat pemakanan haiwan');
addSn3(1, 12, 'Struktur Paruh Burung', 'Sederhana', 'Paruh burung yang tajam dan melengkung seperti helang berfungsi untuk:', { A: 'Mengoyak daging mangsa', B: 'Menghisap manisan bunga', C: 'Memecahkan biji benih keras', D: 'Menapis lumpur mencari cacing' }, 'A', 'Paruh cangkuk melengkung membantu burung pemangsa mengoyak daging.', 'SK 4.1 Adaptasi pemakanan');
addSn3(1, 13, 'Tabiat Arnab', 'Mudah', 'Arnab makan lobak merah dan sayuran hijau. Arnab ialah haiwan:', { A: 'Herbivor', B: 'Karnivor', C: 'Omnivor', D: 'Pengurai' }, 'A', 'Arnab hanya makan sumber tumbuhan, maka ia herbivor.', 'SK 4.1 Tabiat makan arnab');
addSn3(1, 14, 'Perbandingan Gigi Haiwan', 'Sederhana', 'Antara haiwan berikut, yang manakah TIDAK mempunyai gigi taring?', { A: 'Kambing', B: 'Harimau', C: 'Kucing', D: 'Serigala' }, 'A', 'Kambing ialah herbivor dan tidak mempunyai gigi taring.', 'SK 4.1 Perbandingan kegigian');
addSn3(1, 15, 'Analisis Ekosistem KBAT', 'Sukar', 'Jika semua tumbuhan dalam sebuah padang ragut musnah akibat kemarau, apakah kesan pertama terhadap haiwan herbivor?', { A: 'Populasi herbivor berkurang kerana kekurangan bekalan makanan', B: 'Populasi herbivor bertambah berlipat ganda', C: 'Haiwan herbivor bertukar serta-merta menjadi pemangsa ganas', D: 'Tiada sebarang kesan terhadap rantai makanan' }, 'A', 'Herbivor bergantung secara langsung pada tumbuhan untuk terus hidup.', 'SK 4.1 Kelangsungan hidup haiwan');

// Topic 3: Tumbuhan & Cara Pembiakan
addSn3(2, 1, 'Pembiakan Biji Benih', 'Mudah', 'Pokok rambutan dan pokok mangga membiak melalui:', { A: 'Biji benih', B: 'Spora', C: 'Keratan batang', D: 'Daun' }, 'A', 'Pokok buah berbunga menghasilkan buah dan membiak melalui biji benih.', 'SK 5.1 Cara tumbuhan membiak');
addSn3(2, 2, 'Pembiakan Spora', 'Mudah', 'Tumbuhan tidak berbunga seperti paku pakis dan cendawan membiak melalui:', { A: 'Spora', B: 'Biji benih', C: 'Anak pokok', D: 'Batang bawah tanah' }, 'A', 'Paku pakis membiak melalui spora halus di bawah daunnya.', 'SK 5.1 Pembiakan melalui spora');
addSn3(2, 3, 'Pembiakan Keratan Batang', 'Mudah', 'Tumbuhan manakah yang mudah dibiakkan melalui keratan batang?', { A: 'Pokok bunga raya dan ubi kayu', B: 'Pokok betik', C: 'Pokok kelapa', D: 'Pokok jagung' }, 'A', 'Pokok bunga raya dan ubi kayu membiak subur melalui keratan batang.', 'SK 5.1 Keratan batang');
addSn3(2, 4, 'Pembiakan Daun', 'Mudah', 'Pokok setawar dan pokok begonia membiak melalui:', { A: 'Daun', B: 'Biji benih', C: 'Batang bawah tanah', D: 'Anak pokok' }, 'A', 'Pokok setawar mengeluarkan tunas anak pokok di tepi daunnya.', 'SK 5.1 Pembiakan melalui daun');
addSn3(2, 5, 'Pembiakan Anak Pokok', 'Mudah', 'Pokok pisang dan pokok nanas membiak dengan menghasilkan:', { A: 'Anak pokok di sekeliling pokok induk', B: 'Biji benih kering', C: 'Spora terbang', D: 'Daun terapung' }, 'A', 'Pokok pisang dan nanas tumbuh melalui sulur atau anak pokok.', 'SK 5.1 Pembiakan melalui anak pokok');
addSn3(2, 6, 'Batang Bawah Tanah', 'Sederhana', 'Halia, bawang dan ubi kentang membiak melalui:', { A: 'Batang bawah tanah', B: 'Spora', C: 'Daun', D: 'Keratan akar' }, 'A', 'Bawang dan halia menyimpan makanan dan mengeluarkan tunas dari batang bawah tanah.', 'SK 5.1 Batang bawah tanah');
addSn3(2, 7, 'Kepentingan Pembiakan', 'Mudah', 'Mengapakah pembiakan tumbuhan sangat penting kepada hidupan lain?', { A: 'Mengekalkan sumber makanan dan oksigen bagi manusia dan haiwan', B: 'Supaya hutan menjadi sempit', C: 'Untuk mengurangkan kawasan tanah lapang', D: 'Supaya air hujan tidak turun' }, 'A', 'Tumbuhan membekalkan oksigen dan menjadi asas rantai makanan.', 'SK 5.1 Kepentingan pembiakan tumbuhan');
addSn3(2, 8, 'Tumbuhan Dua Cara Pembiakan', 'Sederhana', 'Antara tumbuhan berikut, yang manakah boleh membiak melalui DUA cara iaitu biji benih dan keratan batang?', { A: 'Pokok kangkung', B: 'Pokok kelapa', C: 'Pokok jagung', D: 'Pokok rambutan' }, 'A', 'Kangkung dan selasih boleh membiak melalui biji benih serta keratan batang.', 'SK 5.1 Tumbuhan membiak lebih dari satu cara');
addSn3(2, 9, 'Tunas Bawang', 'Mudah', 'Bawang merah yang dibiarkan di tempat lembap akan mengeluarkan:', { A: 'Tunas hijau baharu dari umbisi', B: 'Biji benih kering', C: 'Spora hitam', D: 'Bungkus kepompong' }, 'A', 'Bawang mengeluarkan tunas baharu daripada batangnya.', 'SK 5.1 Pembiakan bawang');
addSn3(2, 10, 'Ubi Kentang', 'Sederhana', 'Mata tunas pada ubi kentang yang ditanam dalam tanah akan membesar menjadi:', { A: 'Pokok kentang yang baharu', B: 'Cendawan', C: 'Akar parasit', D: 'Bunga setawar' }, 'A', 'Mata tunas ubi kentang berkembang menjadi pokok kentang baharu.', 'SK 5.1 Batang bawah tanah kentang');
addSn3(2, 11, 'Rumput Membiak', 'Mudah', 'Rumput menjalar dan membiak di atas padang melalui:', { A: 'Batang rayap dan biji benih', B: 'Spora sahaja', C: 'Daun gugur', D: 'Bongkah kayu' }, 'A', 'Rumput membiak melalui batang rayap (stolon) dan biji benih.', 'SK 5.1 Pembiakan rumput');
addSn3(2, 12, 'Teknologi Pertanian Tisu', 'Sederhana', 'Teknologi moden membiakkan tumbuhan dalam makmal menggunakan cebisan tisu tumbuhan dipanggil:', { A: 'Kultur tisu', B: 'Spora buatan', C: 'Pembelahan sel', D: 'Fotosintesis tiruan' }, 'A', 'Kultur tisu menghasilkan beribu anak pokok klon dalam masa singkat.', 'SK 5.1 Teknologi pembiakan tumbuhan');
addSn3(2, 13, 'Ciri Biji Benih Terpilih', 'Mudah', 'Petani memilih biji benih yang bernas dan tidak rosak supaya:', { A: 'Kadar percambahan dan hasil tanaman tinggi', B: 'Tanaman cepat layu', C: 'Pokok tidak berbunga', D: 'Air siraman tidak diserap' }, 'A', 'Biji benih berkualiti menghasilkan tanaman yang sihat dan berbuah lebat.', 'SK 5.1 Kualiti pembiakan');
addSn3(2, 14, 'Paku Pakis di Pokok Kelapa Sawit', 'Sederhana', 'Bagaimanakah paku pakis boleh tumbuh tinggi pada batang kelapa sawit?', { A: 'Sporanya yang sangat ringan diterbangkan oleh angin dan melekat di situ', B: 'Petani menanamnya di atas batang pokok', C: 'Burung menanam anak pokok paku pakis', D: 'Akarnya merayap dari dalam tanah' }, 'A', 'Spora halus dan ringan mudah dibawa angin ke celah pelepah kelapa sawit.', 'SK 5.1 Penyebaran spora');
addSn3(2, 15, 'Aplikasi Harian KBAT', 'Sukar', 'Aiman ingin menanam semula sayur kangkung daripada sisa dapur di rumah. Bahagian manakah yang paling sesuai dicucuk ke dalam tanah basah?', { A: 'Bahagian batang yang mempunyai ruas dan akar', B: 'Hujung daun hijau', C: 'Bunga kangkung layu', D: 'Kulit batang kering' }, 'A', 'Keratan batang kangkung berakar cepat menumbuhkan pucuk dan akar baharu.', 'SK 5.1 Aplikasi pembiakan vegetatif');

// Topic 4: Ketumpatan, Asid & Alkali
addSn3(3, 1, 'Konsep Ketumpatan', 'Mudah', 'Mengapakah sebiji gabus terapung di atas permukaan air?', { A: 'Gabus kurang tumpat daripada air', B: 'Gabus lebih tumpat daripada air', C: 'Gabus menyerap air', D: 'Gabus mempunyai warna cerah' }, 'A', 'Objek yang kurang tumpat daripada air akan timbul di permukaan.', 'SK 6.1 Ketumpatan');
addSn3(3, 2, 'Objek Tenggelam', 'Mudah', 'Seketul batu tenggelam di dasar besen air kerana:', { A: 'Batu lebih tumpat daripada air', B: 'Batu kurang tumpat daripada air', C: 'Batu mengandungi udara', D: 'Batu diperbuat daripada ais' }, 'A', 'Objek yang lebih tumpat daripada cecair akan tenggelam ke dasar.', 'SK 6.1 Objek tenggelam');
addSn3(3, 3, 'Lapisan Cecair Tumpat', 'Sederhana', 'Apabila minyak masak dituang ke dalam cawan berisi air, minyak berada di bahagian atas kerana:', { A: 'Minyak kurang tumpat daripada air', B: 'Minyak lebih tumpat daripada air', C: 'Minyak dan air bercampur sebati', D: 'Minyak membeku dalam air' }, 'A', 'Minyak kurang tumpat berbanding air lalu terapung di atas air.', 'SK 6.1 Perbandingan ketumpatan cecair');
addSn3(3, 4, 'Menjadikan Air Lebih Tumpat', 'Sederhana', 'Bagaimanakah cara untuk membuatkan sebiji telur yang tenggelam terapung dalam air?', { A: 'Larutkan garam ke dalam air sehingga air menjadi lebih tumpat', B: 'Panaskan air sehingga mendidih', C: 'Tambahkan ais batu', D: 'Tapis air menggunakan kain' }, 'A', 'Air garam mempunyai ketumpatan lebih tinggi daripada telur, membolehkan telur timbul.', 'SK 6.1 Mengubah ketumpatan air');
addSn3(3, 5, 'Kertas Litmus', 'Mudah', 'Alat penguji yang digunakan di makmal untuk menguji sifat asid dan alkali ialah:', { A: 'Kertas litmus', B: 'Pembaris', C: 'Termometer', D: 'Kanta pembesar' }, 'A', 'Kertas litmus merah dan biru digunakan untuk menentukan sifat asid atau alkali.', 'SK 7.1 Kertas litmus');
addSn3(3, 6, 'Sifat Bahan Berasid', 'Mudah', 'Bahan berasid seperti jus limau nipis menukarkan warna kertas litmus:', { A: 'Biru kepada merah', B: 'Merah kepada biru', C: 'Kuning kepada hijau', D: 'Tiada perubahan warna' }, 'A', 'Asid menukarkan warna kertas litmus biru kepada merah.', 'SK 7.1 Sifat bahan berasid');
addSn3(3, 7, 'Rasa Bahan Berasid', 'Mudah', 'Bahan yang berasid secara amnya berasa:', { A: 'Masam', B: 'Pahit', C: 'Manis', D: 'Masin' }, 'A', 'Asid semula jadi dalam makanan seperti cuka dan lemon berasa masam.', 'SK 7.1 Sifat asid');
addSn3(3, 8, 'Sifat Bahan Beralkali', 'Mudah', 'Bahan beralkali seperti air sabun menukarkan kertas litmus:', { A: 'Merah kepada biru', B: 'Biru kepada merah', C: 'Putih kepada hitam', D: 'Hijau kepada merah' }, 'A', 'Alkali menukarkan kertas litmus merah kepada biru.', 'SK 7.1 Sifat bahan beralkali');
addSn3(3, 9, 'Sentuhan Bahan Alkali', 'Mudah', 'Apabila disentuh dengan jari, bahan beralkali seperti sabun berasa:', { A: 'Licin', B: 'Kasar', C: 'Melekit', D: 'Berpasir' }, 'A', 'Bahan beralkali lazimnya licin apabila disentuh dengan air.', 'SK 7.1 Sifat sentuhan alkali');
addSn3(3, 10, 'Bahan Neutral', 'Mudah', 'Bahan neutral seperti air mineral dan larutan garam:', { A: 'Tidak mengubah warna kedua-dua kertas litmus merah dan biru', B: 'Menukarkan litmus biru kepada merah', C: 'Menukarkan litmus merah kepada biru', D: 'Melarutkan kertas litmus' }, 'A', 'Bahan neutral tidak mengubah warna kertas litmus merah mahupun biru.', 'SK 7.1 Sifat bahan neutral');
addSn3(3, 11, 'Rasa Bahan Neutral', 'Sederhana', 'Bahan neutral mempunyai rasa seperti berikut KECUALI:', { A: 'Pahit dan berlendir', B: 'Manis', C: 'Masin', D: 'Tawar' }, 'A', 'Bahan neutral boleh berasa manis, masin atau tawar, bukan berasa pahit beralkali.', 'SK 7.1 Rasa bahan neutral');
addSn3(3, 12, 'Ujian Ubat Gigi', 'Sederhana', 'Ubat gigi menukarkan kertas litmus merah kepada biru. Ini membuktikan ubat gigi bersifat:', { A: 'Alkali', B: 'Asid', C: 'Neutral', D: 'Toksik' }, 'A', 'Ubat gigi bersifat alkali untuk meneutralkan asid bakteria di mulut.', 'SK 7.1 Aplikasi alkali');
addSn3(3, 13, 'Ujian Asid Asid Kering', 'Sederhana', 'Mengapakah serbuk asid sitrik kering perlu dilarutkan dalam air sebelum diuji dengan kertas litmus?', { A: 'Kertas litmus hanya bertindak balas dengan kehadiran air', B: 'Serbuk boleh merosakkan kertas', C: 'Air mengurangkan rasa masam', D: 'Supaya warna serbuk hilang' }, 'A', 'Sifat asid dan alkali hanya dapat dikesan apabila terdapat air.', 'SK 7.1 Syarat pengujian litmus');
addSn3(3, 14, 'Aplikasi Pelampung Ketumpatan', 'Mudah', 'Pelampung keselamatan digunakan untuk menyelamatkan mangsa lemas kerana pelampung:', { A: 'Kurang tumpat daripada air dan terapung', B: 'Lebih tumpat daripada batu', C: 'Menyerap berat badan manusia', D: 'Boleh berenang sendiri' }, 'A', 'Pelampung berisi udara mempunyai ketumpatan sangat rendah dan timbul di atas air.', 'SK 6.1 Aplikasi ketumpatan');
addSn3(3, 15, 'Peneutralan Asid KBAT', 'Sukar', 'Tanah kebun Pak Seman terlalu berasid akibat sisa baja kimia. Apakah bahan semula jadi yang sesuai ditabur untuk mengurangkan keasidan tanah?', { A: 'Kapur mati atau abu kayu yang bersifat alkali', B: 'Jus limau kasturi', C: 'Cuka makan', D: 'Air perahan asam jawa' }, 'A', 'Bahan alkali seperti kapur pertanian meneutralkan keasidan tanah pertanian.', 'SK 7.1 Aplikasi sifat asid dan alkali');

// Topic 5: Sistem Suria & Takal
addSn3(4, 1, 'Pusat Sistem Suria', 'Mudah', 'Apakah objek yang menjadi pusat bagi Sistem Suria kita?', { A: 'Matahari', B: 'Bumi', C: 'Bulan', D: 'Musytari' }, 'A', 'Matahari ialah sebuah bintang yang terletak di pusat Sistem Suria.', 'SK 8.1 Sistem Suria');
addSn3(4, 2, 'Bilangan Planet', 'Mudah', 'Berapakah bilangan planet utama yang beredar mengelilingi Matahari?', { A: '8 buah planet', B: '9 buah planet', C: '7 buah planet', D: '10 buah planet' }, 'A', 'Sistem Suria mengandungi 8 buah planet utama.', 'SK 8.1 Ahli Sistem Suria');
addSn3(4, 3, 'Planet Paling Dekat', 'Mudah', 'Planet yang paling hampir dengan Matahari ialah:', { A: 'Utarid', B: 'Zuhrah', C: 'Bumi', D: 'Marikh' }, 'A', 'Utarid ialah planet pertama dan paling hampir dengan Matahari.', 'SK 8.1 Urutan planet');
addSn3(4, 4, 'Planet Tempat Tinggal', 'Mudah', 'Planet ketiga dari Matahari yang mempunyai air, udara dan hidupan ialah:', { A: 'Bumi', B: 'Zuhrah', C: 'Marikh', D: 'Zuhal' }, 'A', 'Bumi ialah satu-satunya planet yang menampung kehidupan.', 'SK 8.1 Planet Bumi');
addSn3(4, 5, 'Planet Paling Panas', 'Sederhana', 'Mengapakah Zuhrah merupakan planet paling panas dalam Sistem Suria walaupun Utarid lebih dekat dengan Matahari?', { A: 'Zuhrah mempunyai atmosfera tebal yang memerangkap haba Matahari', B: 'Zuhrah mengeluarkan api sendiri', C: 'Zuhrah berputar paling pantas', D: 'Zuhrah berada dekat dengan Marikh' }, 'A', 'Atmosfera karbon dioksida tebal Zuhrah memerangkap haba kesan rumah hijau melampau.', 'SK 8.1 Ciri-ciri planet Zuhrah');
addSn3(4, 6, 'Planet Terbesar', 'Mudah', 'Planet yang paling besar saiznya dalam Sistem Suria kita ialah:', { A: 'Musytari', B: 'Zuhal', C: 'Uranus', D: 'Neptun' }, 'A', 'Musytari adalah planet gergasi gas terbesar.', 'SK 8.1 Saiz planet');
addSn3(4, 7, 'Planet Bercincin Cantik', 'Mudah', 'Planet yang terkenal dengan sistem cincin ais dan batuan yang sangat jelas ialah:', { A: 'Zuhal', B: 'Marikh', C: 'Bumi', D: 'Utarid' }, 'A', 'Zuhal mempunyai gelang cincin yang luas dan indah.', 'SK 8.1 Ciri planet Zuhal');
addSn3(4, 8, 'Planet Paling Sejuk dan Jauh', 'Mudah', 'Planet kelapan yang paling jauh dari Matahari ialah:', { A: 'Neptun', B: 'Uranus', C: 'Marikh', D: 'Musytari' }, 'A', 'Neptun ialah planet paling jauh dari Matahari.', 'SK 8.1 Planet Neptun');
addSn3(4, 9, 'Peredaran Planet', 'Sederhana', 'Setiap planet beredar mengelilingi Matahari mengikut laluannya sendiri yang dipanggil:', { A: 'Orbit', B: 'Satah', C: 'Paksa', D: 'Gelung' }, 'A', 'Orbit ialah laluan elips planet mengelilingi Matahari.', 'SK 8.1 Laluan orbit planet');
addSn3(4, 10, 'Masa Peredaran', 'Sederhana', 'Semakin jauh kedudukan sebuah planet dari Matahari, semakin:', { A: 'Lama masa yang diambil untuk melengkapkan satu peredaran', B: 'Cepat masa peredarannya', C: 'Tinggi suhu permukaannya', D: 'Kecil saiz orbitnya' }, 'A', 'Planet yang jauh mempunyai orbit yang lebih besar, maka masa peredarannya lebih panjang.', 'SK 8.1 Tempoh peredaran planet');
addSn3(4, 11, 'Definisi Takal', 'Mudah', 'Apakah yang dimaksudkan dengan takal dalam sains?', { A: 'Mesin ringkas yang mengandungi roda beralur dan tali untuk mengangkat beban', B: 'Tuas panjang yang diletakkan pada fulkrum', C: 'Satah condong untuk menggelongsor objek', D: 'Gigi roda yang bersirat' }, 'A', 'Takal terdiri daripada roda beralur yang dilalui tali untuk memudahkan beban diangkat.', 'SK 9.1 Mesin ringkas takal');
addSn3(4, 12, 'Kegunaan Takal Tiang Bendera', 'Mudah', 'Apakah kegunaan takal pada tiang bendera sekolah?', { A: 'Memudahkan bendera dinaikkan ke puncak tiang dengan menarik tali ke bawah', B: 'Mengikat kain bendera agar tidak terbang', C: 'Membuat bunyi loceng berkumandang', D: 'Menstabilkan tiang bendera daripada tumbang' }, 'A', 'Takal menukar arah daya supaya kita menarik tali ke bawah untuk menaikkan bendera.', 'SK 9.1 Aplikasi takal');
addSn3(4, 13, 'Aplikasi Takal Lain', 'Mudah', 'Antara peralatan berikut, yang manakah menggunakan prinsip takal?', { A: 'Kren pembinaan dan bidai tingkap', B: 'Gunting kertas', C: 'Penyapu lantai', D: 'Penyepit ais' }, 'A', 'Kren mengangkat konkrit berat dan bidai langsir menggunakan takal.', 'SK 9.1 Aplikasi takal harian');
addSn3(4, 14, 'Kebaikan Mesin Takal', 'Mudah', 'Mengapakah penggunaan takal sangat bermanfaat kepada manusia?', { A: 'Menjimatkan masa dan memudahkan kerja mengangkat beban berat', B: 'Menambah berat objek yang diangkat', C: 'Membazirkan tenaga pekerja', D: 'Menjadikan tali lebih mudah putus' }, 'A', 'Takal meringankan usaha dan membolehkan objek berat diangkat dengan mudah.', 'SK 9.1 Faedah takal');
addSn3(4, 15, 'Satelit Semula Jadi KBAT', 'Sukar', 'Bulan merupakan satelit semula jadi bagi Bumi. Apakah yang dimaksudkan dengan satelit semula jadi?', { A: 'Jasad angkasa yang mengelilingi planet secara semula jadi', B: 'Stesen angkasa buatan manusia yang memancarkan isyarat televisyen', C: 'Bintang kecil yang berkelip di langit malam', D: 'Batu meteor yang jatuh ke Bumi' }, 'A', 'Satelit semula jadi ialah objek samawi yang mengorbit sesebuah planet.', 'SK 8.1 Satelit semula jadi');

fs.writeFileSync('src/data/sainsTahun3.ts', `import { QuizQuestion } from '../types';\n\nexport const SAINS_TAHUN_3_QUESTIONS: QuizQuestion[] = ${JSON.stringify(snT3Questions, null, 2)};\n`, 'utf8');
console.log(`Generated ${snT3Questions.length} questions for Sains Tahun 3.`);
