import * as fs from 'fs';
import { QuizQuestion } from '../src/types';
import { MATEMATIK_TAHUN_6_QUESTIONS } from '../src/data/matematikTahun6';
import { SAINS_TAHUN_6_QUESTIONS } from '../src/data/sainsTahun6';

// 1. MATEMATIK TAHUN 6
const existingMat = [...MATEMATIK_TAHUN_6_QUESTIONS];
const mat6Topics = [
  'Nombor hingga 10 Juta & Operasi',
  'Pecahan, Perpuluhan & Peratus',
  'Wang, Untung Rugi & Celik Kewangan',
  'Masa, Zon Waktu & Ruang',
  'Koordinat, Nisbah & Kebolehjadian',
];

const newMat6: QuizQuestion[] = [];
function addM6(topic: string, idSuffix: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newMat6.push({
    id: `m6-mat-${idSuffix}`,
    year: 6,
    subject: 'Matematik',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Nombor hingga 10 Juta & Operasi (currently 3, need 12)
addM6(mat6Topics[0], 't1-04', 'Tukarkan 0.35 juta kepada nombor bulat.', { A: '350,000', B: '35,000', C: '3,500,000', D: '3,500' }, 'A', '0.35 × 1,000,000 = 350,000.', 'SK 1.1 Perpuluhan Juta');
addM6(mat6Topics[0], 't1-05', 'Tukarkan 4,200,000 kepada perpuluhan juta.', { A: '4.2 juta', B: '4.02 juta', C: '0.42 juta', D: '42 juta' }, 'A', '4,200,000 ÷ 1,000,000 = 4.2 juta.', 'SK 1.1 Perpuluhan Juta');
addM6(mat6Topics[0], 't1-06', 'Tukarkan 1,500,000 kepada pecahan juta termudah.', { A: '1 1/2 juta', B: '1 1/4 juta', C: '1 3/4 juta', D: '1 1/5 juta' }, 'A', '1,500,000 = 1 500,000/1,000,000 = 1 1/2 juta.', 'SK 1.1 Pecahan Juta');
addM6(mat6Topics[0], 't1-07', 'Hitung: 1.8 juta + 450,000.', { A: '2,250,000', B: '2,200,000', C: '2,000,000', D: '2,500,000' }, 'A', '1,800,000 + 450,000 = 2,250,000 atau 2.25 juta.', 'SK 1.2 Operasi Nombor Juta');
addM6(mat6Topics[0], 't1-08', 'Hitung: 3 1/4 juta - 800,000.', { A: '2,450,000', B: '2,400,000', C: '2,500,000', D: '2,350,000' }, 'A', '3,250,000 - 800,000 = 2,450,000.', 'SK 1.2 Operasi Nombor Juta');
addM6(mat6Topics[0], 't1-09', 'Hitung: 0.04 juta × 15.', { A: '600,000', B: '60,000', C: '6,000,000', D: '400,000' }, 'A', '40,000 × 15 = 600,000.', 'SK 1.2 Pendaraban Juta');
addM6(mat6Topics[0], 't1-10', 'Hitung: 2.4 juta ÷ 8.', { A: '300,000', B: '30,000', C: '3,000,000', D: '400,000' }, 'A', '2,400,000 ÷ 8 = 300,000.', 'SK 1.2 Pembahagian Juta');
addM6(mat6Topics[0], 't1-11', 'Antara nombor berikut, yang manakah nombor gubahan (composite number)?', { A: '51', B: '43', C: '47', D: '53' }, 'A', '51 ialah nombor gubahan kerana 51 = 3 × 17 (boleh dibahagi dengan selain 1 dan dirinya).', 'SK 1.3 Nombor Perdana dan Gubahan');
addM6(mat6Topics[0], 't1-12', 'Hitung: (1.5 juta - 700,000) ÷ 4.', { A: '200,000', B: '250,000', C: '150,000', D: '300,000' }, 'A', '1,500,000 - 700,000 = 800,000. 800,000 ÷ 4 = 200,000.', 'SK 1.2 Operasi Bergabung');
addM6(mat6Topics[0], 't1-13', 'Sebuah agensi menyumbang 1/4 juta pelitup muka kepada 50 buah hospital secara sama rata. Berapakah pelitup muka bagi setiap hospital?', { A: '5,000', B: '50,000', C: '2,500', D: '10,000' }, 'A', '1/4 juta = 250,000. 250,000 ÷ 50 = 5,000.', 'SK 1.4 Penyelesaian Masalah');
addM6(mat6Topics[0], 't1-14', 'Pola nombor: 1.2 juta, 1.5 juta, 1.8 juta, X. Apakah nilai X?', { A: '2.1 juta', B: '2.0 juta', C: '2.2 juta', D: '2.4 juta' }, 'A', 'Pola bertambah 0.3 juta (300,000) setiap langkah: 1.8 juta + 0.3 juta = 2.1 juta.', 'SK 1.1 Pola Nombor Juta');
addM6(mat6Topics[0], 't1-15', 'Sebuah syarikat telekomunikasi mempunyai 5.85 juta pelanggan. Selepas kempen, bilangan pelanggan meningkat sebanyak 350,000. Berapakah jumlah pelanggan sekarang?', { A: '6.2 juta', B: '6.15 juta', C: '6.0 juta', D: '6.5 juta' }, 'A', '5,850,000 + 350,000 = 6,200,000 = 6.2 juta.', 'SK 1.4 Masalah Harian Juta');

// Topic 2: Pecahan, Perpuluhan & Peratus (currently 2, need 13)
addM6(mat6Topics[1], 't2-03', 'Hitung: 3/4 ÷ 1/8.', { A: '6', B: '4', C: '3/32', D: '8' }, 'A', '3/4 ÷ 1/8 = 3/4 × 8/1 = 24/4 = 6.', 'SK 2.1 Pembahagian Pecahan');
addM6(mat6Topics[1], 't2-04', 'Hitung: 2 1/2 ÷ 1/4.', { A: '10', B: '8', C: '5/8', D: '12' }, 'A', '5/2 ÷ 1/4 = 5/2 × 4/1 = 10.', 'SK 2.1 Pembahagian Pecahan');
addM6(mat6Topics[1], 't2-05', 'Hitung: 4/5 × 15.5.', { A: '12.4', B: '12.0', C: '11.8', D: '13.2' }, 'A', '4/5 × 15.5 = 0.8 × 15.5 = 12.4.', 'SK 2.2 Pecahan dan Perpuluhan');
addM6(mat6Topics[1], 't2-06', 'Hitung: 7.25 × 3.6.', { A: '26.1', B: '25.9', C: '26.25', D: '27.1' }, 'A', '7.25 × 3.6 = 26.10.', 'SK 2.2 Pendaraban Perpuluhan');
addM6(mat6Topics[1], 't2-07', 'Hitung: 15.6 ÷ 0.4.', { A: '39', B: '3.9', C: '390', D: '36' }, 'A', '15.6 ÷ 0.4 = 156 ÷ 4 = 39.', 'SK 2.2 Pembahagian Perpuluhan');
addM6(mat6Topics[1], 't2-08', 'Tukarkan 3/8 kepada bentuk peratusan.', { A: '37.5%', B: '38%', C: '35%', D: '36.5%' }, 'A', '3/8 × 100% = 37.5%.', 'SK 2.3 Peratus');
addM6(mat6Topics[1], 't2-09', 'Hitung 120% daripada 450.', { A: '540', B: '520', C: '500', D: '550' }, 'A', '120/100 × 450 = 540.', 'SK 2.3 Peratus Lebih 100%');
addM6(mat6Topics[1], 't2-10', 'Berapakah peratusan 45 daripada 150?', { A: '30%', B: '25%', C: '35%', D: '40%' }, 'A', '45/150 × 100% = 30%.', 'SK 2.3 Peratusan');
addM6(mat6Topics[1], 't2-11', 'Tukarkan 240% kepada nombor bercampur.', { A: '2 2/5', B: '2 1/4', C: '2 1/2', D: '2 3/5' }, 'A', '240/100 = 24/10 = 2 4/10 = 2 2/5.', 'SK 2.3 Peratus kepada Pecahan');
addM6(mat6Topics[1], 't2-12', 'Sebuah tangki mengandungi 80 liter air. 15% air digunakan untuk mencuci. Berapakah baki air dalam tangki?', { A: '68 liter', B: '65 liter', C: '70 liter', D: '64 liter' }, 'A', 'Air diguna: 15% × 80 = 12 liter. Baki: 80 - 12 = 68 liter.', 'SK 2.3 Penyelesaian Masalah');
addM6(mat6Topics[1], 't2-13', 'Hitung: 5/6 ÷ 2 1/2.', { A: '1/3', B: '2/3', C: '1/2', D: '1/4' }, 'A', '5/6 ÷ 5/2 = 5/6 × 2/5 = 2/6 = 1/3.', 'SK 2.1 Pembahagian Pecahan');
addM6(mat6Topics[1], 't2-14', 'Cari nilai: 4.8 + 2.5 × 1.6.', { A: '8.8', B: '11.68', C: '9.2', D: '10.5' }, 'A', 'Darab dahulu: 2.5 × 1.6 = 4.0. Kemudian 4.8 + 4.0 = 8.8.', 'SK 2.2 Operasi Bergabung Perpuluhan');
addM6(mat6Topics[1], 't2-15', 'Harga asal baju ialah RM80. Semasa jualan murah harganya dinaikkan 10% kemudian diberi diskaun 10%. Berapakah harga akhirnya?', { A: 'RM79.20', B: 'RM80.00', C: 'RM78.50', D: 'RM81.00' }, 'A', 'Naik 10%: RM80 + RM8 = RM88. Diskaun 10%: RM88 - RM8.80 = RM79.20.', 'SK 2.3 Peratus Kompaun');

// Topic 3: Wang, Untung Rugi & Celik Kewangan (currently 2, need 13)
addM6(mat6Topics[2], 't3-03', 'Apakah formula untuk mengira peratus keuntungan?', { A: '(Untung ÷ Harga Kos) × 100%', B: '(Untung ÷ Harga Jual) × 100%', C: '(Harga Kos ÷ Untung) × 100%', D: '(Harga Jual ÷ Harga Kos) × 100%' }, 'A', 'Peratus Untung = (Untung ÷ Harga Kos) × 100%.', 'SK 3.1 Untung dan Rugi');
addM6(mat6Topics[2], 't3-04', 'Sebuah jam tangan dibeli dengan harga RM150 dan dijual dengan harga RM180. Berapakah peratus keuntungannya?', { A: '20%', B: '25%', C: '15%', D: '30%' }, 'A', 'Untung = RM30. Peratus untung = (30/150) × 100% = 20%.', 'SK 3.1 Peratus Untung');
addM6(mat6Topics[2], 't3-05', 'Apakah definisi Cukai Perkhidmatan (SST)?', { A: 'Cukai yang dikenakan oleh kerajaan atas perkhidmatan yang disediakan oleh perniagaan tertentu', B: 'Duit bonus yang diberi oleh majikan', C: 'Kadar keuntungan simpanan bank', D: 'Hutang pinjaman rumah' }, 'A', 'Cukai perkhidmatan ialah cukai kepenggunaan yang dikutip oleh pihak berkuasa atas perkhidmatan tertentu.', 'SK 3.2 Cukai Perkhidmatan');
addM6(mat6Topics[2], 't3-06', 'Bil makanan di sebuah restoran ialah RM120. Cukai perkhidmatan sebanyak 6% dikenakan. Berapakah jumlah yang perlu dibayar?', { A: 'RM127.20', B: 'RM126.00', C: 'RM130.00', D: 'RM125.50' }, 'A', 'Cukai = 6/100 × RM120 = RM7.20. Jumlah = RM120 + RM7.20 = RM127.20.', 'SK 3.2 Pengiraan Cukai');
addM6(mat6Topics[2], 't3-07', 'Apakah perbezaan utama antara insurans dan takaful?', { A: 'Takaful berlandaskan prinsip syariah dan saling membantu (tabarru\'), manakala insurans konvensional berasaskan kontrak pemindahan risiko', B: 'Insurans tidak perlu bayar premium', C: 'Takaful hanya untuk kenderaan sahaja', D: 'Tiada perbezaan sama sekali' }, 'A', 'Takaful berteraskan konsep tolong-menolong mengikut syariah Islam.', 'SK 3.3 Insurans dan Takaful');
addM6(mat6Topics[2], 't3-08', 'Encik Hakimi membeli polisi insurans kenderaan untuk:', { A: 'Mendapat perlindungan kewangan sekiranya berlaku kemalangan atau kecurian kereta', B: 'Mendapat dividen bulanan yang tinggi', C: 'Mengelakkan saman had laju', D: 'Mendapat servis minyak percuma di mana-mana bengkel' }, 'A', 'Insurans memberi perlindungan kewangan terhadap risiko luar jangka.', 'SK 3.3 Faedah Insurans');
addM6(mat6Topics[2], 't3-09', 'Faedah kompaun dikira berdasarkan:', { A: 'Wang prinsipal asal beserta faedah yang terkumpul sebelum itu', B: 'Wang prinsipal sahaja', C: 'Jumlah perbelanjaan harian', D: 'Potongan cukai tahunan' }, 'A', 'Faedah kompaun mengira faedah atas prinsipal serta faedah terdahulu.', 'SK 3.4 Faedah Mudah dan Kompaun');
addM6(mat6Topics[2], 't3-10', 'Simpanan RM10,000 dengan faedah mudah 4% setahun selama 3 tahun akan menghasilkan faedah berjumlah:', { A: 'RM1,200', B: 'RM400', C: 'RM800', D: 'RM1,600' }, 'A', 'Faedah = RM10,000 × 4/100 × 3 = RM1,200.', 'SK 3.4 Faedah Mudah');
addM6(mat6Topics[2], 't3-11', 'Apakah yang dimaksudkan dengan "Harga Kos"?', { A: 'Jumlah wang yang dikeluarkan untuk membeli atau mengeluarkan sesuatu barangan sebelum dijual', B: 'Harga yang dipamerkan di rak jualan', C: 'Keuntungan bersih peniaga', D: 'Nilai diskaun promosi' }, 'A', 'Harga kos ialah kos asal perolehan atau pembuatan sesuatu barangan.', 'SK 3.1 Istilah Celik Wang');
addM6(mat6Topics[2], 't3-12', 'Puan Rohana membeli sehelai tudung pada harga kos RM40 dan menjualnya dengan kerugian 15%. Berapakah harga jualan tudung itu?', { A: 'RM34', B: 'RM36', C: 'RM32', D: 'RM35' }, 'A', 'Rugi = 15/100 × RM40 = RM6. Harga jualan = RM40 - RM6 = RM34.', 'SK 3.1 Pengiraan Kerugian');
addM6(mat6Topics[2], 't3-13', 'Sebuah komputer riba dijual secara ansuran dengan bayaran muka RM500 dan bayaran bulanan RM180 selama 12 bulan. Berapakah jumlah harga ansuran komputer riba tersebut?', { A: 'RM2,660', B: 'RM2,160', C: 'RM2,400', D: 'RM2,500' }, 'A', 'Bayaran bulanan: 12 × RM180 = RM2,160. Jumlah = RM500 + RM2,160 = RM2,660.', 'SK 3.1 Pembelian Ansuran');
addM6(mat6Topics[2], 't3-14', 'Ciri utama pelabur yang bijak dalam merancang kewangan ialah:', { A: 'Mempelbagaikan portfolio pelaburan dan memahami risiko pelaburan', B: 'Melabur dalam skim cepat kaya dengan pulangan luar biasa', C: 'Meminjam wang daripada orang lain untuk membeli saham berisiko tinggi', D: 'Menyimpan semua wang di rumah' }, 'A', 'Pelabur bijak memahami risiko dan mempelbagaikan portfolio pelaburan secara sah.', 'SK 3.4 Pengurusan Kewangan Bijak');
addM6(mat6Topics[2], 't3-15', 'Encik Tan membeli sebuah rumah bernilai RM300,000. Dia membayar 10% wang pendahuluan. Berapakah baki pinjaman perumahan yang diperlukannya?', { A: 'RM270,000', B: 'RM280,000', C: 'RM250,000', D: 'RM290,000' }, 'A', 'Wang pendahuluan: 10% × RM300,000 = RM30,000. Baki pinjaman = RM300,000 - RM30,000 = RM270,000.', 'SK 3.4 Penyelesaian Masalah Kewangan');

// Topic 4: Masa, Zon Waktu & Ruang (currently 2, need 13)
addM6(mat6Topics[3], 't4-03', 'Kuala Lumpur berada pada zon waktu UTC+8 manakala Sydney berada pada UTC+10. Jika waktu di Kuala Lumpur ialah 2:00 petang, waktu di Sydney ialah:', { A: '4:00 petang', B: '12:00 tengah hari', C: '5:00 petang', D: '1:00 petang' }, 'A', 'Sydney 2 jam lebih awal daripada Kuala Lumpur (10 - 8 = +2 jam): 2:00 p.m. + 2 jam = 4:00 p.m.', 'SK 4.1 Zon Waktu Dunia');
addM6(mat6Topics[3], 't4-04', 'Tokyo (UTC+9) berada 1 jam di hadapan Kuala Lumpur (UTC+8). Sebuah penerbangan berlepas dari Kuala Lumpur pada jam 0900 dan mengambil masa 7 jam. Pukul berapakah waktu tempatan di Tokyo ketika pesawat mendarat?', { A: 'Jam 1700', B: 'Jam 1600', C: 'Jam 1800', D: 'Jam 1500' }, 'A', 'Waktu KL ketika tiba: 0900 + 7 jam = 1600. Waktu Tokyo (+1 jam): 1600 + 1 jam = Jam 1700.', 'SK 4.1 Zon Waktu Perjalanan');
addM6(mat6Topics[3], 't4-05', 'Sebuah poligon sekata yang mempunyai 8 sisi yang sama panjang dan 8 bucu dipanggil:', { A: 'Oktagon', B: 'Heptagon', C: 'Heksagon', D: 'Nonagon' }, 'A', 'Oktagon ialah poligon yang mempunyai 8 sisi.', 'SK 6.1 Poligon Sekata');
addM6(mat6Topics[3], 't4-06', 'Apakah nama poligon sekata dengan 7 sisi?', { A: 'Heptagon', B: 'Heksagon', C: 'Oktagon', D: 'Pentagon' }, 'A', 'Heptagon mempunyai 7 sisi yang lurus dan sama panjang.', 'SK 6.1 Poligon Sekata');
addM6(mat6Topics[3], 't4-07', 'Jumlah sudut pedalaman bagi sebuah heksagon (6 sisi) ialah:', { A: '720°', B: '540°', C: '360°', D: '900°' }, 'A', 'Formula: (n - 2) × 180° = (6 - 2) × 180° = 4 × 180° = 720°.', 'SK 6.1 Sudut Pedalaman Poligon');
addM6(mat6Topics[3], 't4-08', 'Cari luas sebuah bulatan dengan jejari 7 cm (gunakan π = 22/7).', { A: '154 cm²', B: '308 cm²', C: '44 cm²', D: '88 cm²' }, 'A', 'Luas bulatan = πr² = 22/7 × 7 × 7 = 154 cm².', 'SK 6.2 Luas Bentuk');
addM6(mat6Topics[3], 't4-09', 'Lilitan sebuah bulatan dengan diameter 14 cm ialah (guna π = 22/7):', { A: '44 cm', B: '88 cm', C: '22 cm', D: '154 cm' }, 'A', 'Lilitan = πd = 22/7 × 14 = 44 cm.', 'SK 6.2 Lilitan Bulatan');
addM6(mat6Topics[3], 't4-10', 'Hitung luas bentuk gabungan sebuah segi empat tepat (8 cm × 5 cm) dan segi tiga bersudut tegak (tapak 6 cm, tinggi 4 cm).', { A: '52 cm²', B: '64 cm²', C: '48 cm²', D: '56 cm²' }, 'A', 'Luas segi empat = 40 cm². Luas segi tiga = 1/2 × 6 × 4 = 12 cm². Jumlah = 40 + 12 = 52 cm².', 'SK 6.3 Luas Bentuk Gabungan');
addM6(mat6Topics[3], 't4-11', 'Isi padu sebuah silinder tegak dengan jejari tapak 7 cm dan tinggi 10 cm ialah (guna π = 22/7):', { A: '1,540 cm³', B: '1,440 cm³', C: '770 cm³', D: '2,200 cm³' }, 'A', 'Isi padu silinder = πr²h = 22/7 × 7 × 7 × 10 = 1,540 cm³.', 'SK 6.4 Isi Padu');
addM6(mat6Topics[3], 't4-12', 'Sebuah tangki air berbentuk kuboid berukuran 2 m × 1.5 m × 1 m diisi separuh penuh dengan air. Berapakah isi padu air dalam tangki?', { A: '1.5 m³', B: '3.0 m³', C: '0.75 m³', D: '2.0 m³' }, 'A', 'Isi padu penuh = 2 × 1.5 × 1 = 3 m³. Separuh penuh = 3 ÷ 2 = 1.5 m³.', 'SK 6.4 Isi Padu Cecair');
addM6(mat6Topics[3], 't4-13', 'Diberi satu garis rentas dalam satah, sudut bertentang bucu sentiasa:', { A: 'Sama saiz', B: 'Berjumlah 180°', C: 'Berjumlah 90°', D: 'Berbeza mengikut panjang garis' }, 'A', 'Sudut bertentang bucu yang terbentuk daripada persilangan dua garis lurus adalah sama nilai nilainya.', 'SK 6.1 Ciri Sudut');
addM6(mat6Topics[3], 't4-14', 'Waktu di Mekah (UTC+3) adalah 5 jam di belakang Kuala Lumpur (UTC+8). Apabila jemaah haji di Mekah solat Zohor pada jam 1230, pukul berapakah di Kuala Lumpur?', { A: 'Jam 1730 (5:30 petang)', B: 'Jam 0730 (7:30 pagi)', C: 'Jam 1630', D: 'Jam 1830' }, 'A', '1230 + 5 jam = Jam 1730.', 'SK 4.1 Aplikasi Zon Waktu');
addM6(mat6Topics[3], 't4-15', 'Sebuah kolam renang mempunyai perimeter 60 meter. Jika lebarnya ialah 10 meter, cari panjang kolam renang itu.', { A: '20 meter', B: '25 meter', C: '15 meter', D: '30 meter' }, 'A', 'Perimeter = 2 × (panjang + lebar) = 60. Maka panjang + lebar = 30. Panjang = 30 - 10 = 20 meter.', 'SK 6.3 Perimeter Masalah');

// Topic 5: Koordinat, Nisbah & Kebolehjadian (currently 2, need 13)
addM6(mat6Topics[4], 't5-03', 'Apakah maksud peristiwa "Mustahil" dalam kebolehjadian?', { A: 'Peristiwa yang tidak mungkin berlaku langsung', B: 'Peristiwa yang pasti akan berlaku', C: 'Peristiwa yang ada peluang berlaku separuh', D: 'Peristiwa yang sukar diramal' }, 'A', 'Peristiwa mustahil mempunyai nilai kebolehjadian sifar (0), iaitu langsung tidak boleh berlaku.', 'SK 8.2 Kebolehjadian');
addM6(mat6Topics[4], 't5-04', 'Sebiji dadu adil dilambung. Kebolehjadian mendapat nombor 7 ialah:', { A: 'Mustahil', B: 'Pasti', C: 'Sama kemungkinan', D: 'Besar kemungkinan' }, 'A', 'Dadu standard hanya mempunyai nombor 1 hingga 6, maka mendapat nombor 7 adalah mustahil.', 'SK 8.2 Kebolehjadian');
addM6(mat6Topics[4], 't5-05', 'Matahari terbit di sebelah timur esok pagi. Kebolehjadian peristiwa ini adalah:', { A: 'Pasti', B: 'Mustahil', C: 'Kecil kemungkinan', D: 'Sama kemungkinan' }, 'A', 'Matahari terbit di timur adalah hukum alam yang pasti berlaku.', 'SK 8.2 Kebolehjadian');
addM6(mat6Topics[4], 't5-06', 'Sekeping syiling adil dilambung. Kebolehjadian mendapat bahagian "gambar" ialah:', { A: 'Sama kemungkinan', B: 'Pasti', C: 'Mustahil', D: 'Kecil kemungkinan' }, 'A', 'Syiling mempunyai 2 muka sama peluang (gambar atau angka), maka ia sama kemungkinan (50-50).', 'SK 8.2 Kebolehjadian');
addM6(mat6Topics[4], 't5-07', 'Dalam sebuah kotak ada 9 biji bola merah dan 1 biji bola biru. Kebolehjadian mencabut bola merah ialah:', { A: 'Besar kemungkinan', B: 'Kecil kemungkinan', C: 'Mustahil', D: 'Sama kemungkinan' }, 'A', 'Bilangan bola merah jauh lebih banyak (9/10), maka besar kemungkinan tercabut bola merah.', 'SK 8.2 Kebolehjadian');
addM6(mat6Topics[4], 't5-08', 'Diberi nisbah murid lelaki kepada murid perempuan di sebuah kelas ialah 3 : 4. Jika jumlah murid lelaki ialah 15 orang, berapakah bilangan murid perempuan?', { A: '20 orang', B: '18 orang', C: '24 orang', D: '16 orang' }, 'A', '3 bahagian = 15 -> 1 bahagian = 5. Murid perempuan = 4 bahagian × 5 = 20 orang.', 'SK 7.2 Nisbah');
addM6(mat6Topics[4], 't5-09', 'Nisbah harga buku A kepada buku B ialah 5 : 2. Beza harga kedua-dua buku itu ialah RM15. Berapakah harga buku A?', { A: 'RM25', B: 'RM20', C: 'RM30', D: 'RM35' }, 'A', 'Beza bahagian = 5 - 2 = 3 bahagian = RM15 -> 1 bahagian = RM5. Harga buku A = 5 × RM5 = RM25.', 'SK 7.2 Aplikasi Nisbah');
addM6(mat6Topics[4], 't5-10', 'Titik K(2, 3) digerakkan 4 unit ke kanan dan 3 unit ke atas. Apakah koordinat baharu bagi titik K?', { A: '(6, 6)', B: '(5, 6)', C: '(6, 5)', D: '(7, 6)' }, 'A', 'x baharu = 2 + 4 = 6. y baharu = 3 + 3 = 6. Koordinat baharu = (6, 6).', 'SK 7.1 Translasi Koordinat');
addM6(mat6Topics[4], 't5-11', 'Jarak mengufuk dari titik A(3, 8) ke titik B(9, 8) ialah:', { A: '6 unit', B: '5 unit', C: '9 unit', D: '8 unit' }, 'A', 'Jarak mengufuk = 9 - 3 = 6 unit.', 'SK 7.1 Jarak Mengufuk');
addM6(mat6Topics[4], 't5-12', 'Sebuah kereta menggunakan 5 liter petrol untuk perjalanan sejauh 75 km. Berapakah liter petrol yang diperlukan untuk perjalanan sejauh 225 km?', { A: '15 liter', B: '12 liter', C: '18 liter', D: '20 liter' }, 'A', 'Kadar = 75 ÷ 5 = 15 km/liter. Petrol diperlukan = 225 ÷ 15 = 15 liter.', 'SK 7.3 Kadaran');
addM6(mat6Topics[4], 't5-13', 'Gaji harian seorang pekerja bagi 6 jam bekerja ialah RM48. Berapakah gajinya jika dia bekerja selama 9 jam pada kadar yang sama?', { A: 'RM72', B: 'RM64', C: 'RM80', D: 'RM70' }, 'A', 'Kadar sejam = RM48 ÷ 6 = RM8. Bagi 9 jam = 9 × RM8 = RM72.', 'SK 7.3 Kadaran Kaedah Unitari');
addM6(mat6Topics[4], 't5-14', 'Nisbah luas segi empat sama X kepada segi empat sama Y ialah 1 : 4. Jika luas segi empat sama X ialah 9 cm², apakah luas segi empat sama Y?', { A: '36 cm²', B: '27 cm²', C: '18 cm²', D: '45 cm²' }, 'A', 'Luas Y = 4 × 9 = 36 cm².', 'SK 7.2 Nisbah Luas');
addM6(mat6Topics[4], 't5-15', 'Seekor ikan berenang keluar dari akuarium lalu terbang di udara seperti burung. Kebolehjadian situasi ini ialah:', { A: 'Mustahil', B: 'Kecil kemungkinan', C: 'Sama kemungkinan', D: 'Pasti' }, 'A', 'Ikan akuarium tidak mempunyai organ adaptasi untuk terbang di udara, menjadikannya mustahil.', 'SK 8.2 Kebolehjadian Logik');

const allMat6 = [...existingMat, ...newMat6];
fs.writeFileSync('src/data/matematikTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const MATEMATIK_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allMat6, null, 2)};\n`, 'utf8');
console.log(`Updated Matematik Tahun 6: total ${allMat6.length} questions.`);

// 2. SAINS TAHUN 6
const existingSn = [...SAINS_TAHUN_6_QUESTIONS];
const sn6Topics = [
  'Pembiakan Manusia & Sistem Saraf',
  'Mikroorganisma & Interaksi Hidupan',
  'Daya, Tekanan & Kelajuan',
  'Pengawetan Makanan & Bahan Buangan',
  'Gerhana & Mesin Kompleks',
];

const newSn6: QuizQuestion[] = [];
function addS6(topic: string, idSuffix: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newSn6.push({
    id: `sn6-sains-${idSuffix}`,
    year: 6,
    subject: 'Sains',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Pembiakan Manusia & Sistem Saraf (currently 2, need 13)
addS6(sn6Topics[0], 't1-03', 'Organ pembiakan lelaki yang menghasilkan sperma dinamakan:', { A: 'Testis', B: 'Ovari', C: 'Uterus', D: 'Faraj' }, 'A', 'Testis ialah organ yang menghasilkan sel pembiakan lelaki (sperma).', 'SK 2.1 Sistem Pembiakan Manusia');
addS6(sn6Topics[0], 't1-04', 'Organ pembiakan perempuan yang menghasilkan ovum dinamakan:', { A: 'Ovari', B: 'Uterus', C: 'Testis', D: 'Tiub Fallopio' }, 'A', 'Ovari menghasilkan sel pembiakan perempuan iaitu ovum (telur).', 'SK 2.1 Sistem Pembiakan Manusia');
addS6(sn6Topics[0], 't1-05', 'Tempat berlakunya persenyawaan antara sperma dan ovum ialah di:', { A: 'Tiub Fallopio', B: 'Uterus', C: 'Ovari', D: 'Faraj' }, 'A', 'Persenyawaan lazimnya berlaku di dalam saluran tiub Fallopio.', 'SK 2.1 Persenyawaan');
addS6(sn6Topics[0], 't1-06', 'Tempat penempelan dan perkembangan embrio menjadi fetus sehingga dilahirkan ialah di:', { A: 'Uterus (rahim)', B: 'Ovari', C: 'Tiub Fallopio', D: 'Pundi kencing' }, 'A', 'Uterus atau rahim melindungi dan membekalkan nutrien kepada fetus yang membesar.', 'SK 2.1 Perkembangan Embrio');
addS6(sn6Topics[0], 't1-07', 'Sistem saraf pusat manusia terdiri daripada dua organ utama iaitu:', { A: 'Otak dan saraf tunjang', B: 'Jantung dan peparu', C: 'Mata dan telinga', D: 'Hati dan ginjal' }, 'A', 'Sistem saraf pusat merangkumi otak dan saraf tunjang yang memproses maklumat.', 'SK 2.2 Sistem Saraf Pusat');
addS6(sn6Topics[0], 't1-08', 'Fungsi utama saraf tunjang dalam sistem saraf manusia ialah:', { A: 'Membawa maklumat dari dan ke otak serta mengawal tindakan refleks', B: 'Mengepam darah ke seluruh badan', C: 'Menghadam makanan', D: 'Menghasilkan sel darah merah' }, 'A', 'Saraf tunjang menghubungkan saraf periferi ke otak dan mengawal tindakan refleks pantas.', 'SK 2.2 Fungsi Saraf Tunjang');
addS6(sn6Topics[0], 't1-09', 'Tindakan mengerdipkan mata apabila ada habuk menghampiri mata dikawal oleh sistem saraf sebagai:', { A: 'Tindakan refleks (luar kawal)', B: 'Tindakan terkawal secara sedar', C: 'Penyakit saraf', D: 'Tindakan terancang' }, 'A', 'Tindakan refleks berlaku spontan tanpa difikirkan terlebih dahulu untuk melindungi mata.', 'SK 2.2 Tindakan Refleks');
addS6(sn6Topics[0], 't1-10', 'Antara berikut, tindakan yang manakah merupakan suatu "tindakan terkawal"?', { A: 'Menulis karangan menggunakan pen', B: 'Denyutan jantung mengepam darah', C: 'Peristalsis makanan di kerongkong', D: 'Sentakan lutut apabila diketuk' }, 'A', 'Menulis ialah tindakan terkawal yang dilakukan mengikut kehendak dan kawalan minda sedar.', 'SK 2.2 Tindakan Terkawal');
addS6(sn6Topics[0], 't1-11', 'Apakah bahaya utama penyalahgunaan dadah dan alkohol terhadap sistem saraf manusia?', { A: 'Merosakkan sel otak dan melambatkan penghantaran impuls saraf', B: 'Menjadikan tulang lebih kuat', C: 'Menurunkan suhu badan secara normal', D: 'Meningkatkan daya ingatan' }, 'A', 'Dadah dan alkohol meracuni sel neuron dan menjejaskan koordinasi serta masa tindak balas.', 'SK 2.2 Penjagaan Sistem Saraf');
addS6(sn6Topics[0], 't1-12', 'Pemakaian topi keledar semasa menunggang motosikal sangat penting bertujuan untuk:', { A: 'Melindungi tengkorak dan otak daripada kecederaan parah jika kemalangan', B: 'Mengelakkan rambut ditiup angin', C: 'Mendengar bunyi hon lebih jelas', D: 'Mengelakkan silau matahari semata-mata' }, 'A', 'Topi keledar mengurangkan impak hentakan kepala bagi menyelamatkan organ otak.', 'SK 2.2 Perlindungan Otak');
addS6(sn6Topics[0], 't1-13', 'Tempoh kehamilan manusia dari persenyawaan hingga kelahiran lazimnya mengambil masa kira-kira:', { A: '9 bulan (sekitar 38-40 minggu)', B: '6 bulan', C: '12 bulan', D: '3 bulan' }, 'A', 'Tempoh purata gestasi manusia adalah sekitar 9 bulan atau 40 minggu.', 'SK 2.1 Tempoh Kehamilan');
addS6(sn6Topics[0], 't1-14', 'Salur yang menyalurkan nutrien dan oksigen dari ibu kepada fetus di dalam rahim dinamakan:', { A: 'Tali pusat', B: 'Tiub Fallopio', C: 'Uretra', D: 'Trakea' }, 'A', 'Tali pusat menghubungkan plasenta ibu dengan fetus untuk pertukaran nutrien dan oksigen.', 'SK 2.1 Fungsi Tali Pusat');
addS6(sn6Topics[0], 't1-15', 'Amalan gaya hidup sihat untuk mengekalkan fungsi sistem saraf yang optimum termasuklah:', { A: 'Tidur yang cukup 7-8 jam sehari dan mengambil makanan bernutrisi seimbang', B: 'Bermain permainan video sepanjang malam tanpa tidur', C: 'Mengambil minuman berkafein berlebihan', D: 'Mengelakkan senaman fizikal' }, 'A', 'Rehat yang mencukupi dan nutrisi menyokong regenerasi dan kesihatan sel neuron saraf.', 'SK 2.2 Penjagaan Sistem Saraf');

// Topic 2: Mikroorganisma & Interaksi Hidupan (currently 2, need 13)
addS6(sn6Topics[1], 't2-03', 'Kumpulan mikroorganisma yang merangkumi hidupan seni seperti mukor dan yis ialah:', { A: 'Fungi', B: 'Protozoa', C: 'Virus', D: 'Bakteria' }, 'A', 'Mukor dan yis dikelaskan dalam kumpulan fungi (kulat seni).', 'SK 3.1 Pengelasan Mikroorganisma');
addS6(sn6Topics[1], 't2-04', 'Mikroorganisma yang paling seni dan hanya boleh dilihat menggunakan mikroskop elektron ialah:', { A: 'Virus', B: 'Bakteria', C: 'Protozoa', D: 'Alga' }, 'A', 'Virus adalah mikroorganisma paling kecil dan hanya hidup di dalam sel perumah.', 'SK 3.1 Kumpulan Virus');
addS6(sn6Topics[1], 't2-05', 'Apakah proses hidup mikroorganisma yang dibuktikan apabila adunan roti mengembang selepas dimasukkan yis?', { A: 'Bernafas dan membebaskan gas karbon dioksida', B: 'Bergerak mencari makanan', C: 'Berkumuh menghasilkan cecair', D: 'Mengecut' }, 'A', 'Yis bernafas membebaskan gas karbon dioksida yang memerangkap buih udara dan menaikkan doh roti.', 'SK 3.1 Proses Hidup Mikroorganisma');
addS6(sn6Topics[1], 't2-06', 'Ameba dan Paramecium bergerak di dalam air kolam membuktikan mikroorganisma menjalani proses:', { A: 'Bergerak', B: 'Bertelur', C: 'Membeku', D: 'Menyejat' }, 'A', 'Protozoa seperti Paramecium bergerak menggunakan silia atau pseudopodium.', 'SK 3.1 Proses Hidup Bergerak');
addS6(sn6Topics[1], 't2-07', 'Contoh mikroorganisma berfaedah yang digunakan dalam penghasilan yogurt dan keju ialah:', { A: 'Bakteria Lactobacillus', B: 'Virus Influenza', C: 'Mukor reput', D: 'Kulat bertoksik' }, 'A', 'Bakteria Lactobacillus memfermentasikan laktosa susu menjadi asid laktik dalam yogurt.', 'SK 3.2 Kegunaan Mikroorganisma');
addS6(sn6Topics[1], 't2-08', 'Vaksin mengandungi mikroorganisma yang telah dilemahkan atau dimatikan berfungsi untuk:', { A: 'Merangsang sistem imun menghasilkan antibodi melawan penyakit', B: 'Membekalkan tenaga segera', C: 'Menurunkan berat badan', D: 'Mencerna makanan di perut' }, 'A', 'Vaksin melatih sel darah putih membina antibodi imuniti khusus.', 'SK 3.2 Mikroorganisma Berfaedah');
addS6(sn6Topics[1], 't2-09', 'Interaksi antara dua organisma berbeza spesies yang mana KEDUA-DUANYA mendapat keuntungan dinamakan:', { A: 'Mutualisme', B: 'Komensalisme', C: 'Parasitisme', D: 'Persaingan' }, 'A', 'Mutualisme ialah simbiosis yang memberi manfaat dua hala kepada kedua-dua pihak.', 'SK 4.1 Interaksi Antara Haiwan');
addS6(sn6Topics[1], 't2-10', 'Hubungan antara burung tiung dan kerbau ialah contoh mutualisme kerana:', { A: 'Tiung memakan kutu di badan kerbau (makanan) manakala kerbau bebas kutu (kebersihan)', B: 'Tiung memakan daging kerbau', C: 'Kerbau memijak tiung', D: 'Tiung membina sarang di tanduk kerbau' }, 'A', 'Burung tiung mendapat makanan manakala kerbau dibersihkan daripada parasit kutu.', 'SK 4.1 Hubungan Simbiosis');
addS6(sn6Topics[1], 't2-11', 'Ikan remora melekat pada badan ikan yu untuk mendapatkan sisa makanan tanpa mencederakan atau merugikan ikan yu. Interaksi ini ialah:', { A: 'Komensalisme', B: 'Parasitisme', C: 'Mutualisme', D: 'Mangsa-pemangsa' }, 'A', 'Komensalisme memberi manfaat kepada satu pihak sementara pihak satu lagi tidak terjejas.', 'SK 4.1 Komensalisme');
addS6(sn6Topics[1], 't2-12', 'Paku pakis langsuir yang tumbuh menumpang di batang pokok sawit untuk mendapat cahaya matahari tanpa menyerap nutrien pokok ialah contoh:', { A: 'Komensalisme tumbuhan', B: 'Parasitisme tumbuhan', C: 'Mutualisme tumbuhan', D: 'Karnivor' }, 'A', 'Paku pakis hanya menumpang ruang sokongan tanpa merugikan pokok perumah.', 'SK 4.2 Interaksi Antara Tumbuhan');
addS6(sn6Topics[1], 't2-13', 'Pokok dedalu menyerap air dan nutrien secara langsung dari batang pokok mangga sehingga pokok mangga menjadi layu. Hubungan ini dinamakan:', { A: 'Parasitisme', B: 'Komensalisme', C: 'Mutualisme', D: 'Persaingan' }, 'A', 'Parasit merugikan dan memudaratkan perumah demi kelangsungan hidupnya sendiri.', 'SK 4.2 Parasitisme Tumbuhan');
addS6(sn6Topics[1], 't2-14', 'Faktor utama yang menyebabkan haiwan spesies sama bersaing sesama mereka di kawasan hutan ialah:', { A: 'Makanan, air, pasangan membiak dan tempat tinggal (wilayah)', B: 'Warna bulu badan', C: 'Kelajuan berlari semata-mata', D: 'Kehadiran manusia' }, 'A', 'Haiwan bersaing untuk sumber terhad seperti makanan, air, wilayah dan pasangan.', 'SK 4.1 Faktor Persaingan Haiwan');
addS6(sn6Topics[1], 't2-15', 'Tumbuhan di lantai hutan hujan tropika bersaing hebat antara satu sama lain terutamanya untuk mendapatkan:', { A: 'Cahaya matahari dan ruang', B: 'Gas oksigen', C: 'Baja kimia buatan', D: 'Angin sejuk' }, 'A', 'Kanopi pokok tinggi menghalang cahaya matahari, menyebabkan tumbuhan bawah bersaing untuk cahaya.', 'SK 4.2 Persaingan Tumbuhan');

// Topic 3: Daya, Tekanan & Kelajuan (currently 2, need 13)
addS6(sn6Topics[2], 't3-03', 'Daya geseran sentiasa bertindak ke arah:', { A: 'Bertentangan dengan arah pergerakan objek', B: 'Sama dengan arah pergerakan objek', C: 'Sentiasa ke bawah', D: 'Sentiasa ke atas' }, 'A', 'Daya geseran menentang arah gelongsoran atau gerakan sesuatu objek.', 'SK 5.1 Daya Geseran');
addS6(sn6Topics[2], 't3-04', 'Kelebihan daya geseran dalam kehidupan harian kita ialah:', { A: 'Membolehkan kita berjalan tanpa tergelincir dan membolehkan brek basikal mencengkam', B: 'Menyebabkan tapak kasut haus', C: 'Menghasilkan haba yang tidak diingini pada enjin', D: 'Memperlahankan kelajuan kereta lumba' }, 'A', 'Geseran membolehkan cengkaman antara tapak kasut dengan lantai untuk berjalan stabil.', 'SK 5.1 Kebaikan Geseran');
addS6(sn6Topics[2], 't3-05', 'Kaedah yang paling berkesan untuk mengurangkan geseran yang tidak diingini pada mesin ialah:', { A: 'Menggunakan minyak pelincir atau gris dan memasang alas bebola', B: 'Membuat permukaan menjadi lebih kasar', C: 'Menambah berat mesin', D: 'Menabur serbuk pasir pada gear' }, 'A', 'Pelincir dan alas bebola mengurangkan sentuhan kasar antara permukaan logam.', 'SK 5.1 Mengurangkan Geseran');
addS6(sn6Topics[2], 't3-06', 'Tekanan udara terhasil disebabkan oleh:', { A: 'Pelanggaran zarah-zarah udara ke atas sesuatu permukaan', B: 'Pancaran cahaya matahari', C: 'Tarikan graviti bulan', D: 'Arus elektrik kilat' }, 'A', 'Zarah-zarah udara yang sentiasa bergerak mengenakan daya per unit luas (tekanan udara).', 'SK 5.2 Tekanan Udara');
addS6(sn6Topics[2], 't3-07', 'Semakin tinggi sesuatu lokasi dari aras laut (seperti di puncak Gunung Kinabalu), tekanan udara akan:', { A: 'Semakin berkurang (rendah)', B: 'Semakin bertambah (tinggi)', C: 'Kekal sama tidak berubah', D: 'Menjadi sifar serta-merta' }, 'A', 'Lapisan atmosfera semakin menipis pada altitud tinggi, menjadikan tekanan udara semakin rendah.', 'SK 5.2 Faktor Tekanan Udara');
addS6(sn6Topics[2], 't3-08', 'Prinsip tekanan udara diaplikasikan dalam alat berikut KECUALI:', { A: 'Penyedut minuman, pam picagari dan pelocok mangkuk tandas', B: 'Termometer merkuri', C: 'Penitis cecair ubat', D: 'Penyedut hampagas' }, 'A', 'Termometer merkuri berfungsi atas prinsip pengembangan dan pengecutan cecair, bukan tekanan udara.', 'SK 5.2 Aplikasi Tekanan Udara');
addS6(sn6Topics[2], 't3-09', 'Formula saintifik untuk mengira kelajuan sesuatu objek ialah:', { A: 'Kelajuan = Jarak ÷ Masa', B: 'Kelajuan = Jarak × Masa', C: 'Kelajuan = Masa ÷ Jarak', D: 'Kelajuan = Jarak + Masa' }, 'A', 'Kelajuan diukur sebagai kadar perubahan jarak mengikut masa (Jarak ÷ Masa).', 'SK 5.3 Formula Kelajuan');
addS6(sn6Topics[2], 't3-10', 'Sebuah kereta bergerak sejauh 180 km dalam masa 2 jam. Berapakah kelajuan purata kereta tersebut?', { A: '90 km/j', B: '80 km/j', C: '100 km/j', D: '360 km/j' }, 'A', 'Kelajuan = 180 km ÷ 2 jam = 90 km/j.', 'SK 5.3 Pengiraan Kelajuan');
addS6(sn6Topics[2], 't3-11', 'Seorang pelari pecut mengambil masa 10 saat untuk menamatkan larian 100 meter. Berapakah kelajuannya dalam m/s?', { A: '10 m/s', B: '15 m/s', C: '1 m/s', D: '100 m/s' }, 'A', 'Kelajuan = 100 m ÷ 10 s = 10 m/s.', 'SK 5.3 Unit Kelajuan');
addS6(sn6Topics[2], 't3-12', 'Objek manakah yang bergerak paling laju berdasarkan data berikut?', { A: 'Objek P: 200 km dalam 2 jam (100 km/j)', B: 'Objek Q: 150 km dalam 2 jam (75 km/j)', C: 'Objek R: 80 km dalam 1 jam (80 km/j)', D: 'Objek S: 240 km dalam 3 jam (80 km/j)' }, 'A', 'Objek P bergerak pada 100 km/j, paling laju berbanding yang lain.', 'SK 5.3 Membanding Kelajuan');
addS6(sn6Topics[2], 't3-13', 'Sebuah lori bergerak dengan kelajuan seragam 80 km/j. Berapakah jarak yang dilalui oleh lori itu dalam masa 3 jam?', { A: '240 km', B: '160 km', C: '200 km', D: '26.7 km' }, 'A', 'Jarak = Kelajuan × Masa = 80 km/j × 3 jam = 240 km.', 'SK 5.3 Mengira Jarak');
addS6(sn6Topics[2], 't3-14', 'Berapakah masa yang diambil oleh sebuah kereta api yang bergerak pada kelajuan 120 km/j untuk sampai ke destinasi sejauh 360 km?', { A: '3 jam', B: '4 jam', C: '2.5 jam', D: '5 jam' }, 'A', 'Masa = Jarak ÷ Kelajuan = 360 km ÷ 120 km/j = 3 jam.', 'SK 5.3 Mengira Masa');
addS6(sn6Topics[2], 't3-15', 'Mengapakah corak bunga tayar pada kenderaan perlu ditukar baharu apabila bunganya telah haus (botak)?', { A: 'Bunga tayar haus mengurangkan cengkaman geseran dan menyebabkan kenderaan mudah tergelincir terutamanya di jalan basah', B: 'Supaya tayar kelihatan berkilat', C: 'Kerana tayar botak bergerak lebih perlahan', D: 'Mengurangkan bunyi enjin' }, 'A', 'Bunga tayar mengalirkan air keluar dan memberi cengkaman geseran yang selamat.', 'SK 5.1 Keselamatan Daya Geseran');

// Topic 4: Pengawetan Makanan & Bahan Buangan (currently 2, need 13)
addS6(sn6Topics[3], 't4-03', 'Tujuan utama kaedah pengawetan makanan dijalankan adalah untuk:', { A: 'Melambatkan atau menghalang pertumbuhan mikroorganisma perosak makanan agar tahan lebih lama', B: 'Menjadikan makanan lebih manis semata-mata', C: 'Menukar warna makanan menjadi hitam', D: 'Menghilangkan semua vitamin' }, 'A', 'Pengawetan mewujudkan keadaan tidak sesuai untuk bakteria dan fungi membiak.', 'SK 6.1 Pengawetan Makanan');
addS6(sn6Topics[3], 't4-04', 'Ciri-ciri makanan yang telah rosak akibat tindakan bakteria dan kulat ialah:', { A: 'Berbau busuk, berubah warna, berlendir dan berkulat', B: 'Rangup dan sedap', C: 'Kering dan wangi', D: 'Beku seperti ais' }, 'A', 'Makanan basi menunjukkan tanda kerosakan seperti lendir, kulat dan bau busuk.', 'SK 6.1 Ciri Kerosakan Makanan');
addS6(sn6Topics[3], 't4-05', 'Kaedah pempasteuran yang diasaskan oleh Louis Pasteur melibatkan pemanasan susu pada suhu sekitar 72°C selama 15 saat diikuti dengan:', { A: 'Penyejukan segera ke suhu bawah 10°C', B: 'Pemanasan berterusan sehingga hangus', C: 'Menjemur susu di bawah matahari', D: 'Menambah cuka pekat' }, 'A', 'Kejutan suhu daripada panas segera disejukkan membunuh bakteria patogen tanpa merosakkan rasa susu.', 'SK 6.1 Pempasteuran');
addS6(sn6Topics[3], 't4-06', 'Kaedah penjerukan buah mangga menggunakan larutan gula dan cuka pekat. Keadaan ini menghalang pertumbuhan mikroorganisma kerana:', { A: 'Keasidan yang tinggi dan ketiadaan air bebas membantutkan bakteria', B: 'Menjadikan mangga panas', C: 'Membekukan mikroorganisma', D: 'Menghapuskan udara di dalam botol' }, 'A', 'Keadaan sangat berasid atau osmosis tinggi mengeluarkan air daripada sel mikroorganisma.', 'SK 6.1 Penjerukan');
addS6(sn6Topics[3], 't4-07', 'Kaedah pengeringan ikan masin di bawah panas matahari menghalang pertumbuhan mikroorganisma melalui penyingkiran:', { A: 'Kandungan air (kelembapan)', B: 'Warna kulit ikan', C: 'Tulang ikan', D: 'Zat protein' }, 'A', 'Bakteria dan kulat memerlukan kelembapan (air) untuk terus hidup dan membiak.', 'SK 6.1 Pengeringan');
addS6(sn6Topics[3], 't4-08', 'Pembungkusan vakum mengeluarkan semua udara dari bungkusan plastik. Ini menghalang bakteria daripada membiak kerana ketiadaan:', { A: 'Gas oksigen (udara)', B: 'Cahaya lampu', C: 'Haba bilik', D: 'Graviti' }, 'A', 'Mikroorganisma aerobik memerlukan oksigen untuk proses pernafasan dan pertumbuhan.', 'SK 6.1 Pembungkusan Vakum');
addS6(sn6Topics[3], 't4-09', 'Apakah perbezaan utama antara bahan buangan terbiodegradasi dan tidak terbiodegradasi?', { A: 'Bahan terbiodegradasi boleh diuraikan oleh mikroorganisma pengurai secara semula jadi, manakala tidak terbiodegradasi tidak boleh mereput', B: 'Bahan terbiodegradasi adalah kaca dan logam', C: 'Bahan tidak terbiodegradasi mereput dalam 2 hari', D: 'Tiada beza antara kedua-duanya' }, 'A', 'Bahan terbiodegradasi (sisa sisa makanan, daun) reput secara biologi di dalam tanah.', 'SK 7.1 Bahan Buangan');
addS6(sn6Topics[3], 't4-10', 'Antara sisa berikut, yang manakah dikategorikan sebagai bahan buangan TERBIODEGRADASI?', { A: 'Sisa makanan, kulit buah-buahan dan daun kering', B: 'Botol plastik minuman', C: 'Tin aluminium minuman', D: 'Kaca tingkap terpakai' }, 'A', 'Bahan organik daripada hidupan mudah diuraikan oleh bakteria dan cacing tanah.', 'SK 7.1 Pengelasan Bahan Buangan');
addS6(sn6Topics[3], 't4-11', 'Pembuangan sisa plastik secara tidak terkawal ke dalam sungai dan laut mengancam hidupan akuatik kerana:', { A: 'Penyu tersalah anggap beg plastik sebagai obor-obor lalu memakannya dan mati tercekik', B: 'Plastik membekalkan oksigen berlebihan', C: 'Plastik menurunkan suhu laut', D: 'Ikan membina sarang menggunakan plastik' }, 'A', 'Sisa plastik tidak mereput dan meracuni rantaian makanan marin.', 'SK 7.1 Kesan Pembuangan Sisa');
addS6(sn6Topics[3], 't4-12', 'Amalan 3R dalam pengurusan sisa pepejal merujuk kepada:', { A: 'Reduce (Kurangkan), Reuse (Guna Semula), Recycle (Kitar Semula)', B: 'Read, Run, Rest', C: 'Repair, Refill, Remove', D: 'Replace, Reject, Return' }, 'A', '3R ialah Reduce (kurangkan sisa), Reuse (guna semula), Recycle (kitar semula).', 'SK 7.1 Amalan Lestari 3R');
addS6(sn6Topics[3], 't4-13', 'Tong kitar semula berwarna BIRU dikhaskan untuk membuang bahan sisa jenis:', { A: 'Kertas, kadbod dan buku', B: 'Kaca dan seramik', C: 'Plastik dan tin aluminium', D: 'Sisa makanan basah' }, 'A', 'Tong biru untuk kertas; tong coklat untuk kaca; tong jingga untuk aluminium/plastik.', 'SK 7.1 Kod Warna Tong Kitar Semula');
addS6(sn6Topics[3], 't4-14', 'Kaedah membuat baja kompos daripada sisa dapur di rumah memberi faedah:', { A: 'Menghasilkan baja organik yang menyuburkan tanah dan mengurangkan sampah di tapak pelupusan', B: 'Menjadikan rumah berbau wangi', C: 'Menghasilkan bahan letupan', D: 'Menarik serangga perosak membiak' }, 'A', 'Pengkomposan menukar sisa organik menjadi nutrien humik semula jadi untuk tumbuhan.', 'SK 7.1 Pengkomposan Sisa Organik');
addS6(sn6Topics[3], 't4-15', 'Kaedah pengetinan makanan memerlukan pemanasan pada suhu tinggi melebihi 100°C di bawah tekanan tinggi bertujuan untuk:', { A: 'Membunuh semua spora bakteria termasuk Clostridium botulinum sebelum tin dimeterai kedap udara', B: 'Mencairkan tin logam', C: 'Menjadikan makanan manis', D: 'Mewarnakan sayur di dalam tin' }, 'A', 'Pengetinan komersial menggunakan autoklaf untuk menghapuskan bakteria anaerobik tahan lasak.', 'SK 6.1 Prinsip Pengetinan Makanan');

// Topic 5: Gerhana & Mesin Kompleks (currently 2, need 13)
addS6(sn6Topics[4], 't5-03', 'Susunan kedudukan jasad samawi semasa fenomena GERHANA BULAN berlaku ialah:', { A: 'Matahari - Bumi - Bulan (dalam satu garis lurus)', B: 'Matahari - Bulan - Bumi', C: 'Bumi - Matahari - Bulan', D: 'Bulan - Bumi - Matahari' }, 'A', 'Gerhana Bulan berlaku apabila Bumi berada di antara Matahari dan Bulan dalam garis lurus.', 'SK 8.1 Gerhana Bulan');
addS6(sn6Topics[4], 't5-04', 'Gerhana Bulan hanya boleh berlaku pada fasa Bulan:', { A: 'Bulan Purnama', B: 'Anak Bulan', C: 'Bulan Sabit', D: 'Bulan Separa' }, 'A', 'Gerhana Bulan terjadi apabila bayang Bumi menutupi Bulan penuh semasa fasa Bulan purnama.', 'SK 8.1 Fasa Gerhana Bulan');
addS6(sn6Topics[4], 't5-05', 'Susunan kedudukan jasad samawi semasa berlakunya GERHANA MATAHARI ialah:', { A: 'Matahari - Bulan - Bumi (dalam satu garis lurus)', B: 'Matahari - Bumi - Bulan', C: 'Bumi - Bulan - Matahari', D: 'Bulan - Matahari - Bumi' }, 'A', 'Gerhana Matahari berlaku apabila Bulan melintas di antara Matahari dan Bumi.', 'SK 8.1 Gerhana Matahari');
addS6(sn6Topics[4], 't5-06', 'Gerhana Matahari lazimnya hanya berlaku pada waktu siang semasa fasa:', { A: 'Anak Bulan', B: 'Bulan Purnama', C: 'Bulan Sabit', D: 'Bulan Bongkok' }, 'A', 'Bulan berada di bahagian siang menghadap Matahari pada fasa anak bulan.', 'SK 8.1 Gerhana Matahari');
addS6(sn6Topics[4], 't5-07', 'Kawasan bayang-bayang yang gelap sepenuhnya semasa gerhana dinamakan:', { A: 'Umbra', B: 'Penumbra', C: 'Korona', D: 'Atmosfera' }, 'A', 'Umbra ialah zon bayang gelap pekat; penumbra ialah kawasan bayang separa gelap.', 'SK 8.1 Zon Bayang-bayang');
addS6(sn6Topics[4], 't5-08', 'Kawasan bayang-bayang separa gelap di sekeliling umbra dinamakan:', { A: 'Penumbra', B: 'Umbra', C: 'Kromosfera', D: 'Aurora' }, 'A', 'Pemerhati di kawasan penumbra menyaksikan gerhana separa.', 'SK 8.1 Bahagian Bayang Gerhana');
addS6(sn6Topics[4], 't5-09', 'Lapisan atmosfera Matahari yang kelihatan seperti gelang cincin cahaya putih semasa gerhana matahari penuh dipanggil:', { A: 'Korona', B: 'Kawah', C: 'Magma', D: 'Solar flar' }, 'A', 'Korona memancarkan cahaya halus di sekeliling cakera gelap Bulan semasa gerhana penuh.', 'SK 8.1 Korona Matahari');
addS6(sn6Topics[4], 't5-10', 'Mengapakah kita DILARANG sama sekali melihat fenomena gerhana matahari secara terus dengan mata kasar tanpa penuras khas?', { A: 'Sinaran ultraungu yang kuat boleh merosakkan retina mata dan menyebabkan buta kekal', B: 'Matahari akan berhenti bersinar', C: 'Bulan akan jatuh ke bumi', D: 'Akan menyebabkan sakit kepala sahaja' }, 'A', 'Keamatan sinaran cahaya inframerah dan UV merosakkan saraf penglihatan retina.', 'SK 8.1 Keselamatan Melihat Gerhana');
addS6(sn6Topics[4], 't5-11', 'Apakah yang dimaksudkan dengan "Mesin Kompleks"?', { A: 'Alat atau peranti yang terdiri daripada gabungan dua atau lebih mesin ringkas', B: 'Alat yang menggunakan elektrik kuasa tinggi sahaja', C: 'Mesin yang tidak boleh dibaiki manusia', D: 'Komputer yang sangat besar' }, 'A', 'Mesin kompleks menggabungkan beberapa mesin ringkas seperti roda, tuas dan gear.', 'SK 9.1 Mesin Kompleks');
addS6(sn6Topics[4], 't5-12', 'Basikal ialah contoh mesin kompleks yang menggabungkan mesin ringkas berikut KECUALI:', { A: 'Tuas (brek), roda dan gandar (roda/pedal), dan gear (rantai)', B: 'Baji dan skru', C: 'Nuklear reaktor', D: 'Roda dan gandar' }, 'A', 'Basikal menggabungkan tuas, roda dan gandar, gear serta skru, bukan kuasa reaktor.', 'SK 9.1 Komponen Mesin Basikal');
addS6(sn6Topics[4], 't5-13', 'Gunting menggabungkan dua jenis mesin ringkas utama iaitu:', { A: 'Tuas dan baji (mata pisau)', B: 'Takal dan gear', C: 'Satah condong dan roda', D: 'Skru dan takal' }, 'A', 'Pemegang gunting bertindak sebagai tuas, manakala bilah tajamnya ialah baji.', 'SK 9.1 Mesin Ringkas pada Gunting');
addS6(sn6Topics[4], 't5-14', 'Gerudi tangan mekanikal menggabungkan mesin ringkas:', { A: 'Roda dan gandar, gear serta skru', B: 'Takal sahaja', C: 'Tuas kelas ketiga', D: 'Satah condong semata-mata' }, 'A', 'Engkol gerudi ialah roda & gandar, pemusing ialah gear dan matanya ialah skru.', 'SK 9.1 Analisis Mesin Kompleks');
addS6(sn6Topics[4], 't5-15', 'Kepentingan mereka bentuk mesin yang lestari dan mesra alam dalam era moden ialah:', { A: 'Menjimatkan penggunaan tenaga fosil, mengurangkan kos operasi dan mengelakkan pencemaran alam sekitar', B: 'Menjadikan alat lebih berat', C: 'Menghapuskan keperluan pekerja kilang', D: 'Menghasilkan bunyi bising' }, 'A', 'Mesin lestari mengoptimumkan kecekapan tenaga dan mengurangkan jejak karbon.', 'SK 9.1 Mereka Bentuk Model Lestari');

const allSn6 = [...existingSn, ...newSn6];
fs.writeFileSync('src/data/sainsTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const SAINS_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allSn6, null, 2)};\n`, 'utf8');
console.log(`Updated Sains Tahun 6: total ${allSn6.length} questions.`);
