import * as fs from 'fs';
import { QuizQuestion } from '../src/types';
import { BAHASA_MELAYU_TAHUN_6_QUESTIONS } from '../src/data/bahasaMelayuTahun6';
import { ENGLISH_TAHUN_6_QUESTIONS } from '../src/data/englishTahun6';

// 1. BAHASA MELAYU TAHUN 6
const existingBM = [...BAHASA_MELAYU_TAHUN_6_QUESTIONS];
const bm6Topics = [
  'Tatabahasa Lanjutan & Morfologi',
  'Sintaksis & Pembinaan Ayat',
  'Peribahasa, Kiasan & Seni Bahasa',
  'Pemahaman Petikan & Kosa Kata Kritis',
];

const newBM6: QuizQuestion[] = [];
function addBM(topic: string, id: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newBM6.push({
    id,
    year: 6,
    subject: 'Bahasa Melayu',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Tatabahasa Lanjutan & Morfologi (need 12 more)
addBM(bm6Topics[0], 'bm6-morf-04', 'Pilih kata majmuk mantap yang betul penggunaannya dalam ayat.', { A: 'Semua warganegara Malaysia bertanggungjawab memelihara perpaduan kaum.', B: 'Dia menandatangani borang itu dengan segera.', C: 'Mereka bekerja secara suka rela.', D: 'Mata hari bersinar terik pada waktu tengah hari.' }, 'A', '"Warganegara" dan "bertanggungjawab" ialah kata majmuk mantap yang dieja bercantum.', 'SK 5.2 Kata Majmuk Mantap');
addBM(bm6Topics[0], 'bm6-morf-05', 'Apakah kata ganda berentak yang sesuai untuk melengkapkan ayat: "Pokok-pokok di tepi pantai bergoyang _______ ditiup angin kencang."', { A: 'liuk-lintuk', B: 'gopoh-gapah', C: 'kayu-kayan', D: 'huru-hara' }, 'A', '"Liuk-lintuk" merujuk kepada pergerakan meliuk ke kiri dan ke kanan.', 'SK 5.2 Kata Ganda Berentak');
addBM(bm6Topics[0], 'bm6-morf-06', 'Kata pinjaman bahasa Sanskrit yang lazim digunakan dalam bahasa Melayu ialah:', { A: 'Syurga, neraka, putera, mahkota', B: 'Komputer, televisyen, radio', C: 'Solat, zakat, ibadah', D: 'Dimsum, mi, tauhu' }, 'A', 'Perkataan syurga, neraka, putera dan mahkota dipinjam daripada bahasa Sanskrit kuno.', 'SK 5.1 Kosa Kata Pinjaman');
addBM(bm6Topics[0], 'bm6-morf-07', 'Kata ganda semu ialah kata ganda yang perkataan dasarnya tidak membawa erti jika tidak digandakan, contohnya:', { A: 'Kanak-kanak, labah-labah, anai-anai', B: 'Rumah-rumah, meja-meja', C: 'Gunung-ganang, bukit-bukau', D: 'Tinggi-tinggi, besar-besar' }, 'A', '"Anai-anai" dan "kanak-kanak" ialah kata ganda semu.', 'SK 5.2 Kata Ganda Semu');
addBM(bm6Topics[0], 'bm6-morf-08', 'Imbuhan pinjaman awalan akhiran yang bermaksud "ahli atau pakar" ialah:', { A: '-wan / -man (contoh: angkasawan, seniman)', B: 'pra- (prasekolah)', C: 'pro- (prokerajaan)', D: 'anti- (antiviral)' }, 'A', 'Akhiran -wan/-man merujuk kepada pelaku atau pakar dalam sesuatu bidang.', 'SK 5.2 Imbuhan Pinjaman');
addBM(bm6Topics[0], 'bm6-morf-09', 'Pilih penggunaan kata pemeri "ialah" yang tepat.', { A: 'Tuan Haji Razak ialah Guru Besar Sekolah Kebangsaan Melor.', B: 'Punca utama banjir ialah daripada hujan lebat.', C: 'Sukan terjun ialah sangat mencabar.', D: 'Tujuan aktiviti gotong-royong ialah untuk memupuk muhibah.' }, 'A', '"Ialah" hadir di hadapan frasa nama (Guru Besar Sekolah...).', 'SK 5.1 Kata Pemeri');
addBM(bm6Topics[0], 'bm6-morf-10', 'Antara perkataan berikut, yang manakah mengandungi imbuhan apitan beR-...-an yang menyatakan perbuatan berulang-ulang atau banyak?', { A: 'Berguguran', B: 'Berpakaian', C: 'Bersalaman', D: 'Bermalam' }, 'A', 'Daun-daun berguguran bermaksud banyak daun gugur secara berturutan.', 'SK 5.2 Imbuhan Apitan');
addBM(bm6Topics[0], 'bm6-morf-11', 'Kata bantu ragam yang menyatakan sesuatu perbuatan yang "mesti dilakukan" ialah:', { A: 'Harus / Wajib', B: 'Boleh', C: 'Sedang', D: 'Pernah' }, 'A', '"Harus" atau "mesti" ialah kata bantu ragam yang menunjukkan kepastian atau kemestian.', 'SK 5.1 Kata Bantu');
addBM(bm6Topics[0], 'bm6-morf-12', 'Pilih penggunaan kata penguat bebas yang gramatis dalam ayat.', { A: 'Pemandangan puncak bukit itu sangat indah / amat indah / indah sekali', B: 'Pemandangan itu sangat indah sekali amat', C: 'Pemandangan itu paling indah sekali', D: 'Pemandangan itu teramat indah sekali' }, 'A', 'Kata penguat bebas seperti "amat" dan "sangat" boleh hadir sebelum atau selepas kata adjektif.', 'SK 5.1 Kata Penguat');
addBM(bm6Topics[0], 'bm6-morf-13', 'Kata hubung komplemen yang menghubungkan klausa utama dengan klausa komplemen ialah:', { A: 'Bahawa / Untuk', B: 'Tetapi', C: 'Kerana', D: 'Lalu' }, 'A', '"Bahawa" dan "untuk" ialah kata hubung komplemen.', 'SK 5.1 Kata Hubung Komplemen');
addBM(bm6Topics[0], 'bm6-morf-14', 'Perkataan "berhempas pulas" tergolong dalam:', { A: 'Kata majmuk kiasan', B: 'Kata ganda berentak', C: 'Kata adjektif sifat', D: 'Kata sendi nama' }, 'A', '"Berhempas pulas" ialah kata majmuk yang bermaksud bekerja keras bermati-matian.', 'SK 5.2 Kata Majmuk Kiasan');
addBM(bm6Topics[0], 'bm6-morf-15', 'Pilih ayat yang mempunyai kata ganti nama diri laras bahasa istana yang betul.', { A: '"Beta berkenan melantik laksamana mengetuai angkatan tentera," titah Sultan Mansur Shah.', B: '"Patik akan berangkat ke istana esok," titah baginda.', C: '"Hamba ialah sultan negeri ini," titah raja.', D: '"Beta menjunjung duli tuanku," sembah bendahara.' }, 'A', '"Beta" ialah kata ganti diri pertama bagi raja atau sultan yang sedang bertitah.', 'SK 5.1 Laras Bahasa Istana');

// Topic 2: Sintaksis & Pembinaan Ayat (need 14 more)
addBM(bm6Topics[1], 'bm6-sint-02', 'Tukarkan ayat aktif berikut kepada ayat pasif: "Cikgu Azman telah mengajar mata pelajaran Sains sejak lima tahun lalu."', { A: 'Mata pelajaran Sains telah diajar oleh Cikgu Azman sejak lima tahun lalu.', B: 'Mata pelajaran Sains mengajar Cikgu Azman.', C: 'Cikgu Azman diajarkan oleh Sains.', D: 'Sejak lima tahun lalu Sains diajar Cikgu Azman.' }, 'A', 'Ayat pasif menukarkan objek (mata pelajaran Sains) ke kedudukan subjek dengan kata kerja pasif "diajar oleh".', 'SK 5.3 Ayat Pasif');
addBM(bm6Topics[1], 'bm6-sint-03', 'Pilih ayat majmuk pancangan keterangan musabab yang betul.', { A: 'Pelari itu pengsan di garisan penamat kerana keletihan melampau.', B: 'Pelari itu berlari sambil mendengar muzik.', C: 'Pelari itu berlari atau berjalan pantas.', D: 'Pelari itu sangat kurus dan tinggi.' }, 'A', '"Kerana" ialah kata hubung pancangan keterangan musabab (sebab-akibat).', 'SK 5.3 Ayat Majmuk Pancangan');
addBM(bm6Topics[1], 'bm6-sint-04', 'Ayat susunan songsang: "Cantik sungguh pemandangan matahari terbit di Pantai Merdeka itu." Apakah subjek bagi ayat ini?', { A: 'Pemandangan matahari terbit di Pantai Merdeka itu', B: 'Cantik sungguh', C: 'Pantai Merdeka', D: 'Matahari terbit' }, 'A', 'Dalam susunan biasa: [Subjek: Pemandangan...] + [Predikat: Cantik sungguh]. Predikat didepankan dalam ayat songsang.', 'SK 5.3 Analisis Ayat Songsang');
addBM(bm6Topics[1], 'bm6-sint-05', 'Pilih ayat yang merupakan "Ayat Tanya Tanpa Kata Tanya" dengan partikel kah.', { A: 'Benarkah berita tentang kemalangan jalan raya itu?', B: 'Di manakah kamu meletakkan buku rujukan itu?', C: 'Siapakah nama jiran baharu kamu?', D: 'Mengapakah kamu tidak hadir ke sekolah?' }, 'A', '"Benarkah..." menggunakan kata dasar adjektif dengan partikel -kah, bukan kata tanya.', 'SK 5.3 Jenis-jenis Ayat');
addBM(bm6Topics[1], 'bm6-sint-06', 'Ayat seruan yang manakah menunjukkan perasaan kagum?', { A: 'Wah, megah sungguh Menara Berkembar Petronas itu!', B: 'Aduh, sakitnya kakiku tersadung batu!', C: 'Cis, berani kamu mencabar aku!', D: 'Eh, bilakah kamu sampai ke sini?' }, 'A', 'Kata seru "Wah" digunakan khusus untuk melahirkan perasaan kagum atau takjub.', 'SK 5.3 Ayat Seruan');
addBM(bm6Topics[1], 'bm6-sint-07', 'Pilih ayat perintah jenis Ayat Silaan yang betul.', { A: 'Sila masuk ke dewan peperiksaan sekarang.', B: 'Tolong senyap ketika guru sedang mengajar.', C: 'Jangan buang sampah di merata-rata tempat.', D: 'Harap kamu dapat memaafkan kesilapan saya.' }, 'A', '"Sila" digunakan untuk mempersilakan seseorang secara hormat (Ayat Silaan).', 'SK 5.3 Ayat Perintah Silaan');
addBM(bm6Topics[1], 'bm6-sint-08', 'Pilih ayat perintah jenis Ayat Larangan yang betul.', { A: 'Usah dikenang lagi peristiwa duka yang telah berlalu.', B: 'Jemputlah makan kuih-muih ini.', C: 'Tolong tutup tingkap bilik itu.', D: 'Bolehkah saya meminjam kamus kamu?' }, 'A', '"Usah" dan "jangan" ialah kata larangan untuk menegah seseorang melakukan sesuatu.', 'SK 5.3 Ayat Larangan');
addBM(bm6Topics[1], 'bm6-sint-09', 'Pilih ayat pasif bagi kata ganti diri pertama (aku/saya/kami) yang gramatis.', { A: 'Buku cerita itu sudah saya baca semalam.', B: 'Buku cerita itu sudah dibaca oleh saya semalam.', C: 'Buku cerita itu saya sudah membacanya.', D: 'Semalam buku cerita dibaca saya.' }, 'A', 'Hukum ayat pasif diri 1 & 2: tidak boleh menggunakan imbuhan "di-...-kan" mahupun kata sendi "oleh" (sudah saya baca, bukan dibaca oleh saya).', 'SK 5.3 Ayat Pasif Diri Pertama');
addBM(bm6Topics[1], 'bm6-sint-10', 'Antara ayat berikut, yang manakah ayat majmuk gabungan?', { A: 'Encik Rosli membaca surat khabar manakala isterinya menyiram pokok bunga.', B: 'Murid yang pintar itu menerima anugerah kecemerlangan.', C: 'Dia memberitahu bahawa dia tidak sihat.', D: 'Rumah di atas bukit itu sangat besar.' }, 'A', '"Manakala" menggabungkan dua klausa yang setara menjadi ayat majmuk gabungan.', 'SK 5.3 Ayat Majmuk Gabungan');
addBM(bm6Topics[1], 'bm6-sint-11', 'Apakah fungsi predikat dalam binaan ayat dasar bahasa Melayu?', { A: 'Menerangkan atau memberi maklumat tentang subjek', B: 'Menjadi kata hubung', C: 'Menjadi tanda baca', D: 'Menentukan bilangan suku kata' }, 'A', 'Predikat ialah bahagian ayat yang menceritakan atau menerangkan perihal subjek.', 'SK 5.3 Binaan Ayat Dasar');
addBM(bm6Topics[1], 'bm6-sint-12', 'Pilih ayat yang menepati pola Frasa Nama + Frasa Sendi Nama (FN + FS).', { A: 'Bapa saudara saya ke Mekah pada minggu hadapan.', B: 'Ibu saya seorang guru sekolah rendah.', C: 'Bangunan menara itu sangat tinggi.', D: 'Adik sedang tidur di bilik.' }, 'A', 'Subjek: "Bapa saudara saya" (FN) + Predikat: "ke Mekah" (FS).', 'SK 5.3 Pola Ayat Dasar');
addBM(bm6Topics[1], 'bm6-sint-13', 'Kenal pasti ayat yang mengandungi kesalahan struktur frasa.', { A: 'Mereka membincangkan tentang isu pencemaran sungai. (Salah)', B: 'Mereka membincangkan isu pencemaran sungai. (Betul)', C: 'Mereka berbincang tentang isu pencemaran sungai. (Betul)', D: 'Isu itu mereka bincangkan bersama. (Betul)' }, 'A', 'Kata kerja transitif "membincangkan" mesti terus diikuti objek tanpa kata sendi "tentang".', 'SK 5.3 Pembetulan Kesalahan Ayat');
addBM(bm6Topics[1], 'bm6-sint-14', 'Pilih ayat majmuk pancangan relatif yang menggunakan kata hubung "yang".', { A: 'Pelukis yang berbakat itu memenangi pertandingan seni antarabangsa.', B: 'Dia melukis pemandangan kampung.', C: 'Pelukis itu letih tetapi gembira.', D: 'Setelah penat melukis, dia berehat.' }, 'A', 'Klausa "yang berbakat itu" memancangkan klausa kecil kepada frasa nama pelukis.', 'SK 5.3 Ayat Relatif');
addBM(bm6Topics[1], 'bm6-sint-15', 'Tukarkan ayat cakap ajuk kepada cakap pindah: "Cikgu Mariam berkata kepada murid-murid, \'Siapkan latihan ini sebelum pulang.\'"', { A: 'Cikgu Mariam mengarahkan murid-murid menyiapkan latihan tersebut sebelum pulang.', B: 'Cikgu Mariam bertanya sama ada latihan sudah siap.', C: 'Murid-murid menyuruh Cikgu Mariam siapkan latihan.', D: 'Cikgu Mariam berkata latihan ini mesti siap esok.' }, 'A', 'Cakap pindah menukar kata perintah dan kata ganti (ini → tersebut) tanpa tanda petik.', 'SK 5.3 Cakap Ajuk dan Cakap Pindah');

// Topic 3: Peribahasa, Kiasan & Seni Bahasa (need 13 more)
addBM(bm6Topics[2], 'bm6-peri-03', 'Peribahasa "Bagai aur dengan tebing" bermaksud:', { A: 'Dua pihak yang saling membantu dan bekerjasama dengan erat', B: 'Orang yang cepat marah', C: 'Seseorang yang tidak boleh dipercayai', D: 'Kehidupan yang sentiasa berpindah-randah' }, 'A', 'Aur dan tebing saling memerlukan untuk mengukuhkan tebing daripada runtuh.', 'SK 4.2 Peribahasa');
addBM(bm6Topics[2], 'bm6-peri-04', 'Orang yang tidak tahu menghargai pemberian atau benda yang bernilai diumpamakan sebagai:', { A: 'Bagai kera mendapat bunga', B: 'Bagai melepaskan batuk di tangga', C: 'Bagai murai dicabut ekor', D: 'Bagai layang-layang putus tali' }, 'A', '"Bagai kera mendapat bunga" merujuk orang yang tidak tahu nilai sesuatu yang berharga.', 'SK 4.2 Peribahasa Kiasan');
addBM(bm6Topics[2], 'bm6-peri-05', 'Apakah peribahasa yang membawa maksud "bersiap sedia sebelum ditimpa kesusahan"?', { A: 'Sediakan payung sebelum hujan', B: 'Nasi sudah menjadi bubur', C: 'Ukur baju di badan sendiri', D: 'Biar lambat asalkan selamat' }, 'A', '"Sediakan payung sebelum hujan" menasihati kita sentiasa berjaga-jaga sebelum kemalangan menimpa.', 'SK 4.2 Peribahasa Nasihat');
addBM(bm6Topics[2], 'bm6-peri-06', 'Peribahasa "Alang-alang menyeluk pekasam, biar sampai ke pangkal lengan" mendidik kita agar:', { A: 'Melakukan sesuatu pekerjaan itu sehingga selesai dan berjaya', B: 'Jangan mencuba perkara yang baharu', C: 'Menyerah kalah jika penat', D: 'Meminta upah sebelum bekerja' }, 'A', 'Peribahasa ini menuntut keazaman gigih melaksanakan tugas hingga ke penghujungnya.', 'SK 4.2 Nilai Ketabahan');
addBM(bm6Topics[2], 'bm6-peri-07', 'Apabila seseorang anak mencontohi kelakuan atau bakat ibu bapanya, keadaan ini diibaratkan seperti:', { A: 'Bagaimana acuan begitulah kuihnya', B: 'Bulan jatuh ke riba', C: 'Kera mendapat bunga', D: 'Menegakkan benang yang basah' }, 'A', '"Bagaimana acuan begitulah kuihnya" bermaksud sifat dan tabiat anak mewarisi ibu bapa.', 'SK 4.2 Peribahasa Warisan');
addBM(bm6Topics[2], 'bm6-peri-08', 'Peribahasa "Ukur baju di badan sendiri" menasihati kita supaya:', { A: 'Berbelanja atau melakukan sesuatu mengikut kemampuan diri sendiri', B: 'Membeli pakaian yang mahal sahaja', C: 'Menjadi tukang jahit yang terkenal', D: 'Mengelakkan memakai pakaian lama' }, 'A', 'Maksudnya setiap tindakan dan perbelanjaan harus bersesuaian dengan kemampuan ekonomi diri.', 'SK 4.2 Berhemat');
addBM(bm6Topics[2], 'bm6-peri-09', 'Peribahasa "Harimau mati meninggalkan belang, manusia mati meninggalkan nama" bermaksud:', { A: 'Orang yang berjasa akan sentiasa diingati dan disebut-sebut walaupun telah meninggal dunia', B: 'Semua hidupan akan mati akhirnya', C: 'Harimau ialah haiwan yang gagah', D: 'Nama manusia mesti ditulis pada batu nisan' }, 'A', 'Jasa dan amalan kebajikan insan yang luhur kekal dikenang zaman berzaman.', 'SK 4.2 Nilai Jasa');
addBM(bm6Topics[2], 'bm6-peri-10', 'Peribahasa yang sama maksud dengan "Di mana bumi dipijak, di situ langit dijunjung" ialah:', { A: 'Masuk kandang kambing mengembek, masuk kandang kerbau menguak', B: 'Gajah sama gajah berjuang, pelanduk mati di tengah-tengah', C: 'Ada ubi ada batas', D: 'Untung sabut timbul, untung batu tenggelam' }, 'A', 'Kedua-dua peribahasa menasihati kita agar menyesuaikan diri dan menghormati adat setempat.', 'SK 4.2 Peribahasa Seerti');
addBM(bm6Topics[2], 'bm6-peri-11', 'Gaya bahasa personifikasi dalam puisi ialah:', { A: 'Memberikan sifat-sifat kemanusiaan kepada benda bukan hidup atau abstrak', B: 'Membandingkan dua benda menggunakan perkataan seperti atau bagai', C: 'Mengulang perkataan di awal baris', D: 'Menggunakan kata-kata kasar' }, 'A', 'Contoh personifikasi: "Angin malam berbisik mesra ke telingaku."', 'SK 4.1 Gaya Bahasa Sastera');
addBM(bm6Topics[2], 'bm6-peri-12', 'Dalam puisi tradisional, rima akhir bagi pantun empat kerat yang piawai ialah bernada:', { A: 'a-b-a-b', B: 'a-a-a-a', C: 'a-b-b-a', D: 'a-a-b-b' }, 'A', 'Pantun empat kerat mempunyai pola rima bersilang a-b-a-b pada hujung setiap baris.', 'SK 4.3 Struktur Pantun');
addBM(bm6Topics[2], 'bm6-peri-13', 'Bentuk puisi tradisional Melayu yang mempunyai rima akhir seragam a-a-a-a pada semua barisnya ialah:', { A: 'Syair', B: 'Pantun', C: 'Gurindam', D: 'Seloka' }, 'A', 'Syair mempunyai struktur rima seragam a-a-a-a di setiap rangkapnya.', 'SK 4.3 Seni Bahasa Syair');
addBM(bm6Topics[2], 'bm6-peri-14', 'Simpulan bahasa "anak emas" membawa erti:', { A: 'Anak yang sangat disayangi oleh ibu bapa atau majikan', B: 'Anak yang dilahirkan dengan kulit kuning', C: 'Anak sulung', D: 'Anak angkat' }, 'A', '"Anak emas" ialah orang atau anak yang sangat dimanjakan dan dikasihi.', 'SK 4.2 Simpulan Bahasa');
addBM(bm6Topics[2], 'bm6-peri-15', 'Simpulan bahasa "makan suap" bermaksud perbuatan keji iaitu:', { A: 'Menerima wang rasuah secara haram', B: 'Menyuap makanan ke dalam mulut', C: 'Makan di restoran mewah', D: 'Meminta sedekah di jalanan' }, 'A', '"Makan suap" ialah perbuatan menerima atau memberi rasuah yang diharamkan di sisi undang-undang dan agama.', 'SK 4.2 Simpulan Bahasa');

// Topic 4: Pemahaman Petikan & Kosa Kata Kritis (need 14 more)
addBM(bm6Topics[3], 'bm6-pema-02', 'Dalam teks berita kemalangan: "Pasukan penyelamat bertindak pantas mengevakuasi mangsa banjir." Perkataan "mengevakuasi" bermaksud:', { A: 'Memindahkan mangsa ke tempat yang lebih selamat', B: 'Memberi makanan kepada mangsa', C: 'Mengubati kecederaan mangsa', D: 'Menemubual mangsa' }, 'A', '"Mengevakuasi" ialah proses pemindahan keluar penduduk dari kawasan bahaya.', 'SK 2.2 Kosa Kata Luas');
addBM(bm6Topics[3], 'bm6-pema-03', 'Maksud rangkai kata "pemanasan global" dalam petikan alam sekitar merujuk kepada:', { A: 'Fenomena peningkatan suhu purata atmosfera bumi akibat kesan rumah hijau', B: 'Cuaca panas pada musim kemarau semata-mata', C: 'Haba daripada api memasak di dapur', D: 'Pancaran lampu jalan pada waktu malam' }, 'A', 'Pemanasan global ialah peningkatan suhu bumi akibat pembebasan gas rumah hijau berlebihan.', 'SK 2.3 Pemahaman Saintifik');
addBM(bm6Topics[3], 'bm6-pema-04', 'Teknik membaca "Skimming" (Luncuran) digunakan oleh murid bertujuan untuk:', { A: 'Mendapatkan gambaran umum atau intipati teks dengan pantas', B: 'Menghafal setiap perkataan dalam petikan', C: 'Mencari ejaan perkataan yang salah', D: 'Menterjemah teks ke bahasa asing' }, 'A', 'Skimming ialah teknik membaca sepintas lalu untuk menangkap gagasan umum teks.', 'SK 2.1 Teknik Membaca Pantas');
addBM(bm6Topics[3], 'bm6-pema-05', 'Teknik membaca "Scanning" (Imbasan) pula diaplikasikan apabila pembaca ingin:', { A: 'Mencari maklumat khusus seperti tarikh, nama tokoh atau nombor tertentu', B: 'Membaca secara santai sebelum tidur', C: 'Menikmati keindahan bahasa puisi', D: 'Mengira bilangan muka surat' }, 'A', 'Scanning memberi tumpuan mencari kata kunci spesifik dalam masa yang singkat.', 'SK 2.1 Teknik Membaca Imbasan');
addBM(bm6Topics[3], 'bm6-pema-06', 'Antara berikut, format yang manakah WAJIB ada dalam surat kiriman rasmi?', { A: 'Alamat pengirim, alamat penerima, tarikh, tajuk surat bergaris dan tandatangan', B: 'Kata alu-aluan mesra seperti "Sahabatku yang diingati"', C: 'Lukisan kartun hiasan', D: 'Tandatangan ibu bapa sahaja' }, 'A', 'Surat rasmi memerlukan alamat berasingan, tarikh rasmi, tajuk bergaris/berhuruf tebal dan pengesahan tandatangan.', 'SK 3.3 Format Penulisan Rasmi');
addBM(bm6Topics[3], 'bm6-pema-07', 'Dalam laporan aktiviti gotong-royong sekolah, perenggan pertama laporan biasanya mengandungi:', { A: 'Tarikh, tempat, penganjur dan objektif penganjuran aktiviti', B: 'Jumlah kutipan derma', C: 'Ucapan terima kasih kepada penaja', D: 'Jadual menu makanan tengah hari' }, 'A', 'Perenggan pendahuluan laporan merangkumi pengenalan aktiviti: apa, bila, di mana dan siapa penganjurnya.', 'SK 3.3 Penulisan Laporan');
addBM(bm6Topics[3], 'bm6-pema-08', 'Dalam sesebuah karangan syarahan, panggilan hormat kepada para penonton dan tetamu kehormat dinamakan:', { A: 'Wacana pengikat / kata panggilan protokol', B: 'Tajuk cerita', C: 'Peribahasa pembuka', D: 'Syair penutup' }, 'A', 'Panggilan protokol seperti "Hadirin yang saya hormati sekalian" mengekalkan interaksi dengan audiens.', 'SK 3.3 Karangan Syarahan');
addBM(bm6Topics[3], 'bm6-pema-09', 'Perkataan "berdaya saing" dalam petikan kemajuan ekonomi bermaksud:', { A: 'Mampu bersaing dan mengekalkan keunggulan dalam pasaran serantau atau global', B: 'Suka bergaduh dengan orang lain', C: 'Kerap kalah dalam pertandingan', D: 'Mengelakkan cabaran baharu' }, 'A', '"Berdaya saing" (kompetitif) ialah keupayaan menunjukkan prestasi tinggi dan bersaing secara sihat.', 'SK 2.2 Kosa Kata Kritis');
addBM(bm6Topics[3], 'bm6-pema-10', 'Pengajaran utama yang diperoleh daripada cerita rakyat Teladan "Bawang Putih Bawang Merah" ialah:', { A: 'Sikap sabar dan berbudi pekerti mulia akan mendapat balasan baik, manakala kejahatan akan menerima padahnya', B: 'Kekayaan boleh membeli kebahagiaan', C: 'Menyimpan dendam adalah perbuatan terpuji', D: 'Bercakap bohong membawa tuah' }, 'A', 'Kisah ini sarat dengan mesej moral bahawa ketulusan budi sentiasa diberkati.', 'SK 2.3 Nilai Murni Karya Sastera');
addBM(bm6Topics[3], 'bm6-pema-11', 'Apakah fungsi tanda noktah bertindih (:) dalam teks karangan?', { A: 'Memperkenalkan senarai atau penjelasan lanjutan', B: 'Mengakhiri ayat penyata', C: 'Menunjukkan seruan terkejut', D: 'Menggantikan koma' }, 'A', 'Tanda noktah bertindih digunakan untuk memperkenalkan pemerian, senarai, atau dialog skrip.', 'SK 3.2 Tanda Bacaan');
addBM(bm6Topics[3], 'bm6-pema-12', 'Maksud istilah "integriti" yang sering ditekankan dalam amalan kehidupan murid ialah:', { A: 'Kejujuran, ketulusan dan keutuhan moral dalam melaksanakan setiap amanah', B: 'Kepantasan berlari di padang', C: 'Kebolehan menghafal sifir', D: 'Kekayaan harta benda' }, 'A', 'Integriti bererti memegang teguh prinsip moral kejujuran walau di mana berada.', 'SK 2.3 Nilai Sivik');
addBM(bm6Topics[3], 'bm6-pema-13', 'Apakah tujuan utama penulis menyelitkan soalan retorik dalam perenggan kesimpulan syarahan?', { A: 'Untuk merangsang pemikiran audiens agar merenung mesej yang disampaikan', B: 'Kerana penulis tidak mengetahui jawapannya', C: 'Untuk menguji murid di barisan hadapan', D: 'Untuk memanjangkan masa syarahan' }, 'A', 'Soalan retorik tidak memerlukan jawapan langsung tetapi meninggalkan impak renungan mendalam.', 'SK 3.3 Seni Berhujah');
addBM(bm6Topics[3], 'bm6-pema-14', 'Dalam petikan biografi tokoh, urutan peristiwa lazimnya disusun mengikut susunan:', { A: 'Kronologi (mengikut urutan masa dari awal kelahiran hingga pencapaian)', B: 'Abjad nama watak', C: 'Nilai wang yang dimiliki', D: 'Rawak tanpa susunan' }, 'A', 'Biografi lazimnya ditulis mengikut garis masa kronologi kehidupan tokoh.', 'SK 2.3 Struktur Teks Biografi');
addBM(bm6Topics[3], 'bm6-pema-15', 'Tindakan seorang murid yang membaca label tarikh luput dan kandungan bahan pada bungkusan makanan sebelum membeli menunjukkan dia seorang:', { A: 'Pengguna yang bijak dan peka terhadap keselamatan kesihatan diri', B: 'Pembeli yang cerewet dan membuang masa', C: 'Peniaga yang kedekut', D: 'Pengutip barang lusuh' }, 'A', 'Membaca label nutrien dan tarikh luput adalah ciri amalan kepenggunaan bijak.', 'SK 2.3 Pendidikan Pengguna Bijak');

const allBM6 = [...existingBM, ...newBM6];
fs.writeFileSync('src/data/bahasaMelayuTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const BAHASA_MELAYU_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allBM6, null, 2)};\n`, 'utf8');
console.log(`Updated Bahasa Melayu Tahun 6: total ${allBM6.length} questions.`);

// 2. ENGLISH TAHUN 6
const existingBI = [...ENGLISH_TAHUN_6_QUESTIONS];
const bi6Topics = [
  'Emergencies & Past Tenses',
  'Passive Voice & Manufacturing',
  'Conditionals & Future Predictions',
  'Space Exploration & Connectors',
];

const newBI6: QuizQuestion[] = [];
function addBI(topic: string, id: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newBI6.push({
    id,
    year: 6,
    subject: 'Bahasa Inggeris',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Emergencies & Past Tenses (need 13 more)
addBI(bi6Topics[0], 'eng6-em-03', 'While the firefighters _______ the blazing flames, the ambulance arrived at the scene.', { A: 'were battling', B: 'battled', C: 'are battling', D: 'battles' }, 'A', 'Use past continuous ("were battling") for an ongoing past action with plural subject "firefighters".', 'CEFR B1 Past Continuous');
addBI(bi6Topics[0], 'eng6-em-04', 'What is the nationwide emergency telephone number in Malaysia for Police, Ambulance, and Fire Brigade?', { A: '999', B: '911', C: '112', D: '100' }, 'A', '999 is the official Malaysian emergency response number (MERS 999).', 'CEFR B1 Emergency Safety');
addBI(bi6Topics[0], 'eng6-em-05', 'Hakim was studying in his bedroom when the fire alarm _______ loudly.', { A: 'rang', B: 'was ringing', C: 'rings', D: 'ring' }, 'A', 'The past simple "rang" interrupts the continuous action "was studying".', 'CEFR B1 Past Simple Interruption');
addBI(bi6Topics[0], 'eng6-em-06', 'If someone suffers a deep cut that is bleeding heavily, what should you do first?', { A: 'Apply firm direct pressure with a clean sterile cloth on the wound', B: 'Wash it with hot boiling water', C: 'Wave your hand in the air', D: 'Rub sand into the cut' }, 'A', 'Direct firm pressure controls bleeding and aids clot formation.', 'CEFR B1 First Aid Procedures');
addBI(bi6Topics[0], 'eng6-em-07', 'The building began shaking violently because an earthquake _______ in the neighbouring region.', { A: 'had occurred', B: 'has occur', C: 'is occurring', D: 'will occur' }, 'A', 'The past perfect "had occurred" explains an action that happened before another past event.', 'CEFR B1 Past Perfect');
addBI(bi6Topics[0], 'eng6-em-08', 'Which phrasal verb means "to extinguish a fire"?', { A: 'Put out', B: 'Put on', C: 'Put off', D: 'Put up' }, 'A', '"Put out" is the standard phrasal verb meaning to extinguish flames.', 'CEFR B1 Phrasal Verbs');
addBI(bi6Topics[0], 'eng6-em-09', 'The brave lifeguard dived into the rough waves and _______ the struggling swimmer.', { A: 'rescued', B: 'rescue', C: 'is rescuing', D: 'rescues' }, 'A', 'Both past actions ("dived" and "rescued") match in past simple narrative tense.', 'CEFR B1 Past Simple');
addBI(bi6Topics[0], 'eng6-em-10', 'When evacuating a multi-storey shopping mall during a fire emergency, you must ALWAYS:', { A: 'Use the designated emergency stairs and never take the elevator', B: 'Take the elevator to be faster', C: 'Go to the roof to take photos', D: 'Hide inside a fitting room' }, 'A', 'Lifts may lose power during fires, so stairs are the only safe escape route.', 'CEFR B1 Fire Safety Evacuation');
addBI(bi6Topics[0], 'eng6-em-11', 'The storm was so fierce that several large tree branches _______ onto the highway.', { A: 'crashed', B: 'crashing', C: 'crash', D: 'crashes' }, 'A', 'Past simple "crashed" fits the narrative context of the severe storm.', 'CEFR B1 Narrative Tenses');
addBI(bi6Topics[0], 'eng6-em-12', 'The doctor gently cleaned the boy\'s grazed knee and wrapped it with a sterile _______:', { A: 'bandage', B: 'blanket', C: 'pillow', D: 'curtain' }, 'A', 'A bandage is used to protect and hold dressings over wounds.', 'CEFR B1 First Aid Kit');
addBI(bi6Topics[0], 'eng6-em-13', 'While my father _______ the car tyre, my sister held the emergency torchlight.', { A: 'was changing', B: 'changed', C: 'is changing', D: 'changes' }, 'A', 'Past continuous "was changing" describes the ongoing manual task.', 'CEFR B1 Past Continuous');
addBI(bi6Topics[0], 'eng6-em-14', 'The word "evacuation" means:', { A: 'Moving people out of a dangerous area to a safe place', B: 'Starting a campfire in the woods', C: 'Cooking a meal for visitors', D: 'Renovating an old house' }, 'A', '"Evacuation" refers to the organized exit of people from peril.', 'CEFR B1 Emergency Vocabulary');
addBI(bi6Topics[0], 'eng6-em-15', 'What should you do if your clothes catch fire according to safety guidelines?', { A: 'Stop, Drop, and Roll on the ground to smother the flames', B: 'Run as fast as possible in the wind', C: 'Fan the fire with paper', D: 'Jump up and down continuously' }, 'A', '"Stop, Drop, and Roll" deprives the fire of oxygen and extinguishes burning clothes.', 'CEFR B1 Fire Survival Protocol');

// Topic 2: Passive Voice & Manufacturing (need 14 more)
addBI(bi6Topics[1], 'eng6-pas-02', 'Rubber gloves and tyres _______ from natural latex harvested in Malaysian plantations.', { A: 'are manufactured', B: 'is manufactured', C: 'manufactures', D: 'manufacturing' }, 'A', 'Plural subject ("Rubber gloves and tyres") requires "are" + past participle "manufactured".', 'CEFR B1 Present Passive');
addBI(bi6Topics[1], 'eng6-pas-03', 'The national car, Proton Saga, _______ locally in Tanjung Malim.', { A: 'is assembled', B: 'are assembled', C: 'assembled', D: 'assembling' }, 'A', 'Singular subject "Proton Saga" takes "is assembled" in the passive voice.', 'CEFR B1 Passive Voice');
addBI(bi6Topics[1], 'eng6-pas-04', 'Paper _______ from wood pulp extracted from fast-growing trees.', { A: 'is produced', B: 'are produced', C: 'produce', D: 'producing' }, 'A', 'Uncountable noun "Paper" uses "is produced".', 'CEFR B1 Passive Voice');
addBI(bi6Topics[1], 'eng6-pas-05', 'Transform to passive: "Workers package the fresh fruits into cardboard boxes."', { A: 'The fresh fruits are packaged into cardboard boxes by workers.', B: 'The fresh fruits is packaged into cardboard boxes.', C: 'Cardboard boxes packages the fresh fruits.', D: 'Workers are packaged by fresh fruits.' }, 'A', 'The direct object "fruits" becomes the plural passive subject + "are packaged".', 'CEFR B1 Active to Passive');
addBI(bi6Topics[1], 'eng6-pas-06', 'Crude palm oil _______ into cooking oil, soaps, and biodiesel fuel.', { A: 'is refined', B: 'are refined', C: 'refines', D: 'refining' }, 'A', 'Singular non-count noun "Crude palm oil" takes "is refined".', 'CEFR B1 Manufacturing Processes');
addBI(bi6Topics[1], 'eng6-pas-07', 'Every single microchip _______ rigorously tested before being installed in smartphones.', { A: 'is', B: 'are', C: 'were', D: 'being' }, 'A', '"Every single microchip" is singular, so it takes "is" tested.', 'CEFR B1 Quality Control Passive');
addBI(bi6Topics[1], 'eng6-pas-08', 'The historical monument _______ by a famous architect in 1910.', { A: 'was designed', B: 'is designed', C: 'were designed', D: 'designs' }, 'A', 'Past passive uses "was designed" for singular subjects in a past year.', 'CEFR B1 Past Passive');
addBI(bi6Topics[1], 'eng6-pas-09', 'Textile fabrics _______ with eco-friendly dyes to prevent water pollution.', { A: 'are coloured', B: 'is coloured', C: 'colours', D: 'coloured' }, 'A', 'Plural subject "Textile fabrics" takes "are coloured".', 'CEFR B1 Manufacturing Vocabulary');
addBI(bi6Topics[1], 'eng6-pas-10', 'Glass bottles _______ melted down and remoulded into new containers during recycling.', { A: 'are', B: 'is', C: 'was', D: 'has' }, 'A', 'Plural "bottles" takes "are melted".', 'CEFR B1 Recycling Processes');
addBI(bi6Topics[1], 'eng6-pas-11', 'Which preposition is used to introduce the agent in a passive sentence (e.g., "The Mona Lisa was painted _______ Leonardo da Vinci")?', { A: 'by', B: 'with', C: 'from', D: 'of' }, 'A', '"By" introduces the person or entity performing the action in passive voice.', 'CEFR B1 Passive Agent');
addBI(bi6Topics[1], 'eng6-pas-12', 'Robotic arms _______ widely used in modern automated assembly lines.', { A: 'are', B: 'is', C: 'was', D: 'been' }, 'A', 'Plural subject "Robotic arms" uses "are widely used".', 'CEFR B1 Industrial Automation');
addBI(bi6Topics[1], 'eng6-pas-13', 'Cocoa beans _______ dried under the tropical sun before being roasted into delicious chocolate.', { A: 'are', B: 'is', C: 'was', D: 'being' }, 'A', 'Plural "Cocoa beans" takes "are dried".', 'CEFR B1 Food Manufacturing');
addBI(bi6Topics[1], 'eng6-pas-14', 'Change into passive: "Alexander Graham Bell invented the first telephone in 1876."', { A: 'The first telephone was invented by Alexander Graham Bell in 1876.', B: 'The first telephone is invented by Bell.', C: 'Alexander Graham Bell was invented telephone.', D: 'Telephones were inventing by Bell.' }, 'A', 'Past passive: Object + was invented + by + subject.', 'CEFR B1 Historical Inventions');
addBI(bi6Topics[1], 'eng6-pas-15', 'Why is passive voice frequently preferred when writing formal scientific and industrial reports?', { A: 'Because the action and end product are more important than who did it', B: 'Because passive voice uses fewer words', C: 'Because active voice is grammatically incorrect', D: 'Because scientists do not know the names of workers' }, 'A', 'Passive voice emphasizes objective processes and results over individual agents.', 'CEFR B1 Formal Register');

// Topic 3: Conditionals & Future Predictions (need 14 more)
addBI(bi6Topics[2], 'eng6-con-02', 'First Conditional: "If it _______ tomorrow morning, our class will postpone the outdoor camping trip."', { A: 'rains', B: 'will rain', C: 'rained', D: 'raining' }, 'A', 'In the First Conditional, the "if" clause uses present simple ("rains") and the main clause uses "will".', 'CEFR B1 First Conditional');
addBI(bi6Topics[2], 'eng6-con-03', 'Zero Conditional for scientific facts: "If you heat water to 100°C, it _______."', { A: 'boils', B: 'will boiled', C: 'boiled', D: 'is boiling' }, 'A', 'Zero conditional uses present simple in both clauses for scientific truths (heat -> boils).', 'CEFR B1 Zero Conditional');
addBI(bi6Topics[2], 'eng6-con-04', 'If you study diligently every day, you _______ your final year examinations with flying colours.', { A: 'will pass', B: 'passed', C: 'would passed', D: 'passing' }, 'A', 'First conditional main clause uses "will + base verb" (will pass).', 'CEFR B1 First Conditional Result');
addBI(bi6Topics[2], 'eng6-con-05', 'Second Conditional for unreal imaginary situations: "If I _______ a superhero, I would fly across the world to protect innocent people."', { A: 'were', B: 'am', C: 'will be', D: 'be' }, 'A', 'Second conditional uses past subjunctive "were" for hypothetical states.', 'CEFR B1 Second Conditional');
addBI(bi6Topics[2], 'eng6-con-06', 'If humans continue cutting down pristine rainforests recklessly, many endangered animals _______ their natural habitats.', { A: 'will lose', B: 'lost', C: 'loses', D: 'losing' }, 'A', 'First conditional prediction: will + lose.', 'CEFR B1 Environmental Prediction');
addBI(bi6Topics[2], 'eng6-con-07', 'Predictions with "Will": Scientists predict that artificial intelligence _______ revolutionize healthcare within the next decade.', { A: 'will', B: 'shall not', C: 'is', D: 'did' }, 'A', '"Will" expresses confident future predictions based on trends.', 'CEFR B1 Future Predictions');
addBI(bi6Topics[2], 'eng6-con-08', '"Unless you wear sunscreen at the beach, you _______ get painful sunburns."', { A: 'will', B: 'wouldn\'t', C: 'did', D: 'are' }, 'A', '"Unless" means "if not", leading to the future consequence "you will get sunburns".', 'CEFR B1 Conjunction Unless');
addBI(bi6Topics[2], 'eng6-con-09', 'If we _______ enough money by December, we might travel to South Korea.', { A: 'save', B: 'saved', C: 'will save', D: 'saving' }, 'A', 'The condition clause requires present simple "save".', 'CEFR B1 First Conditional');
addBI(bi6Topics[2], 'eng6-con-10', 'If plants do not receive adequate sunlight, they _______ produce food through photosynthesis.', { A: 'cannot', B: 'must', C: 'should', D: 'might not be' }, 'A', '"Cannot" describes physical impossibility in conditional statements.', 'CEFR B1 Modals in Conditionals');
addBI(bi6Topics[2], 'eng6-con-11', 'Future intention with evidence: "Look at those dark storm clouds! It _______ rain very soon."', { A: 'is going to', B: 'will', C: 'was going to', D: 'rains' }, 'A', 'Use "be going to" when there is present visual evidence for an immediate event.', 'CEFR B1 Be Going To for Predictions');
addBI(bi6Topics[2], 'eng6-con-12', '"If I won a million ringgit in a youth science grant, I _______ build a solar-powered vehicle."', { A: 'would', B: 'will', C: 'can', D: 'must' }, 'A', 'Second conditional uses "would + base verb" in the main clause following past simple "won".', 'CEFR B1 Second Conditional Main Clause');
addBI(bi6Topics[2], 'eng6-con-13', 'Future continuous: "This time next week, we _______ our final semester school holidays in Langkawi."', { A: 'will be enjoying', B: 'enjoy', C: 'enjoyed', D: 'were enjoying' }, 'A', 'Future continuous "will be enjoying" describes an action that will be ongoing at a specific future time.', 'CEFR B1 Future Continuous');
addBI(bi6Topics[2], 'eng6-con-14', 'If you freeze pure water, it _______ into solid ice.', { A: 'turns', B: 'will turned', C: 'turned', D: 'is turning' }, 'A', 'Zero conditional for physical law uses present simple: turns.', 'CEFR B1 Zero Conditional');
addBI(bi6Topics[2], 'eng6-con-15', 'What is the crucial difference between "will" and "might" when predicting the future?', { A: '"Will" indicates certainty while "might" expresses possibility with uncertainty', B: '"Might" is only used for past events', C: '"Will" can only be used for weather', D: 'There is no grammatical difference' }, 'A', '"Will" signals high certainty (100%), whereas "might" denotes tentative possibility (50%).', 'CEFR B1 Degrees of Certainty');

// Topic 4: Space Exploration & Connectors (need 14 more)
addBI(bi6Topics[3], 'eng6-sp-02', 'Astronauts float weightlessly inside the International Space Station _______ there is microgravity in Earth\'s orbit.', { A: 'because', B: 'although', C: 'unless', D: 'despite' }, 'A', '"Because" introduces the scientific explanation/reason for weightlessness.', 'CEFR B1 Cause and Effect');
addBI(bi6Topics[3], 'eng6-sp-03', 'Space suits are heavily pressurized _______ protect astronauts from extreme temperatures and lethal radiation.', { A: 'in order to', B: 'so that they', C: 'because', D: 'however' }, 'A', '"In order to" + infinitive verb ("protect") indicates clear purpose.', 'CEFR B1 Purpose Connectors');
addBI(bi6Topics[3], 'eng6-sp-04', 'The red planet, Mars, is barren and desolate. _______, scientists believe it once had flowing liquid water.', { A: 'However', B: 'Furthermore', C: 'Therefore', D: 'Consequently' }, 'A', '"However" introduces a contrast between its current state and past conditions.', 'CEFR B1 Contrast Connectors');
addBI(bi6Topics[3], 'eng6-sp-05', 'The Hubble Space Telescope has captured breathtaking images of distant galaxies. _______, the newer James Webb Space Telescope can observe deeper into the early universe.', { A: 'Moreover', B: 'Although', C: 'Unless', D: 'Despite' }, 'A', '"Moreover" adds supporting information highlighting additional advancements.', 'CEFR B1 Connectors of Addition');
addBI(bi6Topics[3], 'eng6-sp-06', 'Dato\' Dr Sheikh Muszaphar Shukor became the first Malaysian astronaut to journey into space on board Soyuz TMA-11 _______ 2007.', { A: 'in', B: 'on', C: 'at', D: 'by' }, 'A', 'Use "in" with calendar years (in 2007).', 'CEFR B1 Prepositions of Time');
addBI(bi6Topics[3], 'eng6-sp-07', 'The massive rocket was launched successfully into orbit _______ the stormy weather earlier that morning.', { A: 'despite', B: 'although', C: 'because of', D: 'since' }, 'A', '"Despite" is followed by a noun phrase ("the stormy weather") to express concession.', 'CEFR B1 Concession Connectors');
addBI(bi6Topics[3], 'eng6-sp-08', 'Satellites orbit high above our atmosphere, _______ providing crucial weather forecasts and GPS navigation data.', { A: 'thereby', B: 'because', C: 'whereas', D: 'instead' }, 'A', '"Thereby" means "by that means / as a result of that".', 'CEFR B1 Advanced Connectors');
addBI(bi6Topics[3], 'eng6-sp-09', 'Which celestial body is at the centre of our Solar System, around which eight planets orbit?', { A: 'The Sun', B: 'The Moon', C: 'Jupiter', D: 'Mars' }, 'A', 'The Sun is the yellow dwarf star at the gravitational heart of our Solar System.', 'CEFR B1 Solar System Facts');
addBI(bi6Topics[3], 'eng6-sp-10', 'Venus is roughly the same physical size as Earth; _______, its atmosphere is intensely hot and toxic.', { A: 'nevertheless', B: 'similarly', C: 'therefore', D: 'because' }, 'A', '"Nevertheless" signals a stark contrast despite the initial physical similarity.', 'CEFR B1 Discourse Markers');
addBI(bi6Topics[3], 'eng6-sp-11', 'Astronauts undergo years of rigorous physical simulation _______ prepare their bodies for the punishing conditions of spaceflight.', { A: 'so as to', B: 'although', C: 'because of', D: 'unless' }, 'A', '"So as to" introduces the reason or purpose before a base verb.', 'CEFR B1 Connectors of Purpose');
addBI(bi6Topics[3], 'eng6-sp-12', 'The rover Perseverance landed safely on Mars _______ transmit geological soil analysis back to NASA researchers.', { A: 'to', B: 'for', C: 'so', D: 'because' }, 'A', '"To transmit" expresses the infinitive of purpose.', 'CEFR B1 Purpose');
addBI(bi6Topics[3], 'eng6-sp-13', 'Light travels at approximately 300,000 kilometres per second. _______, light from the Sun takes roughly eight minutes to reach Earth.', { A: 'Therefore', B: 'Although', C: 'Whereas', D: 'Unless' }, 'A', '"Therefore" indicates the logical consequence or calculation result.', 'CEFR B1 Connectors of Result');
addBI(bi6Topics[3], 'eng6-sp-14', 'Neptune is the _______ planet from the Sun in our Solar System.', { A: 'farthest', B: 'far', C: 'farther', D: 'more far' }, 'A', '"Farthest" is the superlative indicating the maximum physical distance.', 'CEFR B1 Superlative Adjectives');
addBI(bi6Topics[3], 'eng6-sp-15', 'Why are uncrewed robotic probes sent to explore hazardous cosmic environments instead of human crews?', { A: 'Robotic probes can endure extreme radiation and deep-space journeys without risking human lives', B: 'Because robots eat more food than humans', C: 'Because spacecraft cannot carry metal', D: 'To prevent aliens from seeing humans' }, 'A', 'Robotic probes safely gather astronomical data in hostile conditions without human vulnerability.', 'CEFR B1 Space Science Reasoning');

const allBI6 = [...existingBI, ...newBI6];
fs.writeFileSync('src/data/englishTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const ENGLISH_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allBI6, null, 2)};\n`, 'utf8');
console.log(`Updated English Tahun 6: total ${allBI6.length} questions.`);
