import * as fs from 'fs';
import { QuizQuestion } from '../src/types';
import { PENDIDIKAN_ISLAM_TAHUN_6_QUESTIONS } from '../src/data/pendidikanIslamTahun6';
import { BAHASA_ARAB_TAHUN_6_QUESTIONS } from '../src/data/bahasaArabTahun6';
import { BAHASA_CINA_TAHUN_6_QUESTIONS } from '../src/data/bahasaCinaTahun6';

// 1. PENDIDIKAN ISLAM TAHUN 6
const existingPI = [...PENDIDIKAN_ISLAM_TAHUN_6_QUESTIONS];
const pi6Topics = [
  'Al-Quran & Tajwid Lanjutan',
  'Akidah: Rukun Iman Lanjutan',
  'Ibadah: Solat Jenazah & Hari Raya',
  'Sirah & Pembukaan Kota Mekah',
];

const newPI6: QuizQuestion[] = [];
function addPI(topic: string, id: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newPI6.push({
    id,
    year: 6,
    subject: 'Pendidikan Islam',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Al-Quran & Tajwid Lanjutan (need 14 more)
addPI(pi6Topics[0], 'pi6-taj-02', 'Berapakah kadar harakat bacaan bagi Mad Wajib Muttasil?', { A: '4 atau 5 harakat (semasa wasal)', B: '2 harakat sahaja', C: '6 harakat lazim sahaja', D: '1 harakat' }, 'A', 'Mad Wajib Muttasil dibaca 4 atau 5 harakat ketika wasal.', 'SK 1.7 Hukum Tajwid Mad');
addPI(pi6Topics[0], 'pi6-taj-03', 'Hukum tajwid "Mad Silah Tawilah" berlaku apabila ha dhomir (ـه / ـهِ) bertemu dengan huruf:', { A: 'Hamzah (ء) pada awal kalimah seterusnya', B: 'Nun mati (نْ)', C: 'Huruf ro (ر)', D: 'Huruf mim (م)' }, 'A', 'Mad Silah Tawilah berlaku apabila ha dhomir diapit huruf berbaris bertemu huruf hamzah.', 'SK 1.7 Mad Silah');
addPI(pi6Topics[0], 'pi6-taj-04', 'Kadar bacaan bagi Mad Silah Qasirah ialah:', { A: '2 harakat', B: '4 harakat', C: '6 harakat', D: '3 harakat' }, 'A', 'Mad Silah Qasirah (ha dhomir bertemu huruf selain hamzah) dibaca 2 harakat.', 'SK 1.7 Mad Silah Qasirah');
addPI(pi6Topics[0], 'pi6-taj-05', 'Hukum tajwid "Mad Lazim Kalimi Muthaqqal" dibaca dengan kadar panjang:', { A: '6 harakat', B: '2 harakat', C: '4 harakat', D: '3 harakat' }, 'A', 'Mad Lazim Kalimi Muthaqqal (contoh: ولا الضّالّين) wajib dibaca panjang 6 harakat.', 'SK 1.7 Mad Lazim');
addPI(pi6Topics[0], 'pi6-taj-06', 'Tanda waqaf lazim (مـ) dalam mushaf al-Quran bermaksud:', { A: 'Wajib berhenti (Waqaf Lazim)', B: 'Dilarang berhenti', C: 'Harus berhenti atau terus', D: 'Lebih baik teruskan bacaan' }, 'A', 'Tanda mim kecil (مـ) menandakan waqaf lazim yang wajib berhenti agar maksud ayat tidak terpesong.', 'SK 1.8 Tanda-tanda Waqaf');
addPI(pi6Topics[0], 'pi6-taj-07', 'Tanda waqaf (لا) dalam mashaf bermaksud:', { A: 'Dilarang berhenti (Waqaf Mamnu\')', B: 'Wajib berhenti', C: 'Boleh berhenti mana-mana', D: 'Sujud tilawah' }, 'A', 'Tanda "La" (لا) bermaksud tidak boleh berhenti melainkan di hujung ayat.', 'SK 1.8 Tanda Waqaf Mamnu');
addPI(pi6Topics[0], 'pi6-taj-08', 'Tanda waqaf bertitik tiga ( ۛ ... ۛ ) dinamakan Waqaf Mua\'naqah, di mana pembaca perlu:', { A: 'Berhenti pada salah satu daripada dua tempat tanda tersebut sahaja', B: 'Berhenti pada kedua-dua tempat', C: 'Teruskan membaca tanpa berhenti pada kedua-duanya', D: 'Mengulang semula surah' }, 'A', 'Waqaf Mu\'anaqah (tanda peluk) mengharuskan berhenti di salah satu tanda sahaja.', 'SK 1.8 Waqaf Mua\'naqah');
addPI(pi6Topics[0], 'pi6-taj-09', 'Surah Ad-Dhuha mengandungi mesej ketuhanan yang sangat menenangkan iaitu:', { A: 'Allah SWT tidak pernah meninggalkan dan membenci Nabi Muhammad SAW', B: 'Peringatan tentang hari kiamat', C: 'Kisah tentera bergajah', D: 'Kewajipan berpuasa di bulan Ramadan' }, 'A', 'Ayat "Maa wadda\'aka rabbuka wamaa qalaa" menegaskan kasih sayang Allah kepada Rasulullah.', 'SK 1.2 Kefahaman Surah Ad-Dhuha');
addPI(pi6Topics[0], 'pi6-taj-10', 'Pengajaran utama daripada Surah Al-Insyirah (Asy-Syarh) yang menyatakan "Fainna ma\'al \'usri yusra" ialah:', { A: 'Sesungguhnya bersama setiap kesulitan itu pasti ada kemudahan', B: 'Manusia sentiasa dalam kerugian', C: 'Kecelakaan bagi orang yang mengumpat', D: 'Perintah menunaikan solat lima waktu' }, 'A', 'Allah memberi jaminan bahawa di sebalik kepayahan terbentang kelapangan dan kemudahan.', 'SK 1.3 Surah Al-Insyirah');
addPI(pi6Topics[0], 'pi6-taj-11', 'Surah At-Tin menerangkan bahawa Allah SWT telah menciptakan manusia dalam bentuk yang:', { A: 'Sebaik-baik kejadian (Ahsani taqwim)', B: 'Paling lemah', C: 'Paling kuat berbanding malaikat', D: 'Serupa dengan hidupan lain' }, 'A', '"Laqad khalaqnal insaana fee ahsani taqweem" (Sebaik-baik ciptaan dan rupa bentuk).', 'SK 1.4 Surah At-Tin');
addPI(pi6Topics[0], 'pi6-taj-12', 'Hukum membaca basmalah pada awal setiap surah al-Quran kecuali Surah At-Taubah adalah:', { A: 'Sunat muakkad', B: 'Haram', C: 'Makruh', D: 'Mubah biasa' }, 'A', 'Membaca basmalah disunatkan pada permulaan semua surah kecuali Surah At-Taubah.', 'SK 1.1 Adab Membaca Al-Quran');
addPI(pi6Topics[0], 'pi6-taj-13', 'Apakah hukum tajwid apabila huruf mad bertemu sukun asli dalam satu kalimah?', { A: 'Mad Lazim Kalimi Mukhaffaf (contoh: ءآلْـَٰٔنَ)', B: 'Mad Arid Lissukun', C: 'Mad Iwad', D: 'Mad Badal' }, 'A', 'Mad Lazim Kalimi Mukhaffaf dibaca 6 harakat.', 'SK 1.7 Hukum Mad Lazim');
addPI(pi6Topics[0], 'pi6-taj-14', 'Hukum Tajwid "Mad Badal" berlaku apabila:', { A: 'Huruf hamzah mendahului huruf mad dalam satu kalimah (contoh: ءَامَنُوا)', B: 'Huruf mad bertemu hamzah di hujung ayat', C: 'Huruf wau bertemu ya', D: 'Nun sakinah bertemu ba' }, 'A', 'Mad Badal terjadi apabila huruf hamzah berada sebelum huruf mad.', 'SK 1.7 Mad Badal');
addPI(pi6Topics[0], 'pi6-taj-15', 'Kadar bacaan hukum Mad \'Aridh Lissukun ketika berhenti (waqaf) adalah:', { A: 'Boleh dibaca 2, 4, atau 6 harakat', B: 'Mesti 10 harakat', C: '1 harakat sahaja', D: '8 harakat' }, 'A', 'Mad \'Aridh Lissukun mempunyai tiga wajah bacaan: qasar (2), tawassut (4), atau tul (6 harakat).', 'SK 1.7 Mad Aridh Lissukun');

// Topic 2: Akidah: Rukun Iman Lanjutan (need 13 more)
addPI(pi6Topics[1], 'pi6-aki-03', 'Apakah maksud nama Allah "Al-Muntaqim" (الْمُنْتَقِمُ)?', { A: 'Maha Pembalas (menghukum orang yang berbuat zalim dan ingkar)', B: 'Maha Pengasih', C: 'Maha Mengetahui', D: 'Maha Pencipta' }, 'A', 'Al-Muntaqim bermaksud Allah Maha Membalas kejahatan golongan pendosa yang melampaui batas.', 'SK 2.2 Asmaul Husna Al-Muntaqim');
addPI(pi6Topics[1], 'pi6-aki-04', 'Apakah maksud nama Allah "Al-Hasib" (الْحَسِيبُ)?', { A: 'Maha Menghitung segala amalan makhluk dan Maha Mencukupi', B: 'Maha Berkuasa', C: 'Maha Mendengar', D: 'Maha Melihat' }, 'A', 'Al-Hasib bermaksud Allah menghitung setiap amalan hamba-Nya sekecil zarah.', 'SK 2.2 Asmaul Husna Al-Hasib');
addPI(pi6Topics[1], 'pi6-aki-05', 'Apakah maksud konsep "Takdir Mubram" dalam rukun iman kepada Qada\' dan Qadar?', { A: 'Ketentuan Allah yang muktamad dan tidak dapat diubah (contoh: tarikh kematian)', B: 'Ketentuan yang boleh berubah dengan doa dan ikhtiar', C: 'Perbuatan maksiat', D: 'Kesihatan badan' }, 'A', 'Takdir Mubram ialah ketetapan qada\' yang pasti dan mutlak tanpa boleh diubah.', 'SK 2.1 Takdir Mubram dan Muallaq');
addPI(pi6Topics[1], 'pi6-aki-06', 'Apakah contoh bagi "Takdir Mu\'allaq" (ketentuan yang bergantung kepada usaha dan doa)?', { A: 'Kejayaan dalam peperiksaan yang dicapai selepas gigih mengulang kaji dan berdoa', B: 'Matahari terbit dari timur', C: 'Jantina kelahiran bayi', D: 'Hari kiamat' }, 'A', 'Takdir Mu\'allaq bergantung kepada asbab usaha, amalan dan doa hamba.', 'SK 2.1 Takdir Muallaq');
addPI(pi6Topics[1], 'pi6-aki-07', 'Apakah perbezaan antara "Ikhtiar" dan "Tawakal"?', { A: 'Ikhtiar ialah usaha gigih manusia, manakala tawakal ialah berserah kepada Allah setelah berusaha', B: 'Tawakal dahulu kemudian baru ikhtiar', C: 'Ikhtiar hanya untuk orang tua', D: 'Tiada beza antara kedua-duanya' }, 'A', 'Seorang mukmin wajib berikhtiar bersungguh-sungguh kemudian bertawakal redha dengan keputusan Allah.', 'SK 2.1 Konsep Tawakal');
addPI(pi6Topics[1], 'pi6-aki-08', 'Kesan positif mengimani Qada\' dan Qadar dalam kehidupan seorang murid ialah:', { A: 'Sabar apabila ditimpa ujian dan tidak sombong apabila beroleh kejayaan', B: 'Malas berusaha kerana percaya takdir sudah tentu', C: 'Cepat berputus asa', D: 'Menyalahkan takdir apabila gagal' }, 'A', 'Iman kepada takdir melahirkan ketenangan jiwa, sifat sabar dan sentiasa bersyukur.', 'SK 2.1 Hikmah Beriman kepada Takdir');
addPI(pi6Topics[1], 'pi6-aki-09', 'Apakah hukum mempercayai ramalan nasib atau tilik bintang zodiak (astrologi)?', { A: 'Haram dan boleh merosakkan akidah', B: 'Sunat untuk hiburan', C: 'Harus sekiranya percuma', D: 'Makruh sahaja' }, 'A', 'Mempercayai ramalan tukang tilik nasib dilarang keras dan menjejaskan ketauhidan.', 'SK 2.3 Memelihara Akidah');
addPI(pi6Topics[1], 'pi6-aki-10', 'Perkara "Ghaibiyyat" dalam akidah Islam merujuk kepada:', { A: 'Perkara sam\'iyyat yang tidak dapat dicapai oleh pancaindera tetapi wajib diimani seperti alam kubur, titian sirat dan syurga', B: 'Barang yang hilang di rumah', C: 'Fenomena cuaca kilat', D: 'Permainan silap mata' }, 'A', 'Ghaibiyyat ialah hal-hal alam ghaib yang diberitakan oleh wahyu al-Quran dan hadis sahih.', 'SK 2.4 Perkara Ghaibiyyat');
addPI(pi6Topics[1], 'pi6-aki-11', 'Titian yang merentasi api neraka menuju ke syurga pada hari akhirat dinamakan:', { A: 'Titian Sirat (As-Sirat)', B: 'Al-Mizan', C: 'Al-Haudh', D: 'Padang Mahsyar' }, 'A', 'As-Sirat ialah jambatan yang mesti diseberangi oleh semua manusia di akhirat kelak.', 'SK 2.4 Peristiwa Akhirat As-Sirat');
addPI(pi6Topics[1], 'pi6-aki-12', 'Alat neraca timbangan keadilan Allah untuk menimbang amalan baik dan buruk di akhirat dinamakan:', { A: 'Al-Mizan', B: 'As-Sirat', C: 'Al-Kautsar', D: 'Al-Barzakh' }, 'A', 'Al-Mizan ialah timbangan neraca hakiki bagi menimbang pahala dan dosa manusia.', 'SK 2.4 Al-Mizan');
addPI(pi6Topics[1], 'pi6-aki-13', 'Syirik Asghar (syirik kecil) yang paling bahaya dan perlu dijauhi oleh seorang muslim ialah:', { A: 'Riak (menunjuk-nunjuk amalan ibadah demi pujian manusia)', B: 'Makan berlebihan', C: 'Tidur lewat', D: 'Membeli pakaian mahal' }, 'A', 'Nabi SAW memberi amaran tentang bahaya riak sebagai syirik kecil yang menghapuskan pahala.', 'SK 2.3 Menjauhi Syirik');
addPI(pi6Topics[1], 'pi6-aki-14', 'Alam perantaraan antara kematian seseorang sehingga hari kebangkitan dinamakan alam:', { A: 'Barzakh (alam kubur)', B: 'Mahsyar', C: 'Rahim', D: 'Dunia' }, 'A', 'Alam Barzakh ialah fasa pemisah antara kehidupan dunia dengan alam akhirat.', 'SK 2.4 Alam Barzakh');
addPI(pi6Topics[1], 'pi6-aki-15', 'Tanda-tanda kiamat besar (Kubra) menurut hadis sahih antaranya ialah:', { A: 'Keluarnya Dajjal, turunnya Nabi Isa AS dan terbitnya matahari dari sebelah barat', B: 'Hujan lebat di waktu malam', C: 'Musim buah-buahan menjadi banyak', D: 'Kematian orang tua' }, 'A', 'Kemunculan Dajjal dan terbitnya matahari dari barat ialah tanda kiamat besar.', 'SK 2.4 Tanda Kiamat Besar');

// Topic 3: Ibadah: Solat Jenazah & Hari Raya (need 14 more)
addPI(pi6Topics[2], 'pi6-iba-02', 'Berapakah bilangan takbir dalam Solat Jenazah?', { A: '4 kali takbir', B: '2 kali takbir', C: '5 kali takbir', D: '3 kali takbir' }, 'A', 'Solat Jenazah mempunyai 4 kali takbir tanpa rukuk dan tanpa sujud.', 'SK 3.1 Solat Jenazah');
addPI(pi6Topics[2], 'pi6-iba-03', 'Apakah yang dibaca sejurus selepas Takbir Pertama dalam Solat Jenazah?', { A: 'Membaca Surah Al-Fatihah', B: 'Membaca selawat ke atas Nabi', C: 'Membaca doa untuk si mati', D: 'Membaca tahiyyat akhir' }, 'A', 'Selepas takbir pertama (takbiratul ihram), disyariatkan membaca Surah Al-Fatihah.', 'SK 3.1 Rukun Solat Jenazah');
addPI(pi6Topics[2], 'pi6-iba-04', 'Apakah bacaan selepas Takbir Kedua dalam Solat Jenazah?', { A: 'Membaca Selawat ke atas Nabi Muhammad SAW', B: 'Membaca Surah Al-Ikhlas', C: 'Membaca doa qunut', D: 'Membaca doa untuk jenazah' }, 'A', 'Selepas takbir kedua, wajib berselawat ke atas junjungan besar Nabi Muhammad SAW.', 'SK 3.1 Selawat Solat Jenazah');
addPI(pi6Topics[2], 'pi6-iba-05', 'Apakah yang dibaca selepas Takbir Ketiga dalam Solat Jenazah?', { A: 'Mendoakan keampunan dan rahmat khusus untuk jenazah', B: 'Membaca Surah Al-Fatihah', C: 'Membaca ayat Kursi', D: 'Memberi salam' }, 'A', 'Selepas takbir ketiga, dibacakan doa khusus memohon keampunan bagi jenazah (Allahummaghfir lahu...).', 'SK 3.1 Doa Solat Jenazah');
addPI(pi6Topics[2], 'pi6-iba-06', 'Kedudukan imam semasa mengimamkan solat jenazah LELAKI yang sunnah ialah berdiri bertentangan dengan:', { A: 'Kepala jenazah', B: 'Pinggang jenazah', C: 'Kaki jenazah', D: 'Lutut jenazah' }, 'A', 'Bagi jenazah lelaki, imam sunat berdiri bertentangan dengan bahagian kepala jenazah.', 'SK 3.1 Kaifiat Solat Jenazah');
addPI(pi6Topics[2], 'pi6-iba-07', 'Bagi jenazah PEREMPUAN, kedudukan imam yang disunatkan adalah berdiri bertentangan dengan:', { A: 'Bahagian pinggang (tengah badan) jenazah', B: 'Kepala jenazah', C: 'Kaki jenazah', D: 'Bahu jenazah' }, 'A', 'Bagi jenazah perempuan, sunnah imam berdiri bertentangan dengan bahagian pinggang/tengah jenazah.', 'SK 3.1 Kaifiat Solat Jenazah');
addPI(pi6Topics[2], 'pi6-iba-08', 'Apakah hukum menunaikan Solat Hari Raya Aidilfitri dan Aidiladha bagi umat Islam?', { A: 'Sunat Muakkad', B: 'Fardu Ain', C: 'Fardu Kifayah', D: 'Harus' }, 'A', 'Solat sunat dua hari raya berstatus Sunat Muakkad (sangat dituntut).', 'SK 3.2 Solat Hari Raya');
addPI(pi6Topics[2], 'pi6-iba-09', 'Berapakah bilangan takbir zawaid (tambahan) pada rakaat PERTAMA Solat Sunat Hari Raya (selepas takbiratul ihram)?', { A: '7 kali takbir', B: '5 kali takbir', C: '3 kali takbir', D: '4 kali takbir' }, 'A', 'Pada rakaat pertama, disunatkan bertakbir sebanyak 7 kali sebelum membaca Al-Fatihah.', 'SK 3.2 Kaifiat Solat Hari Raya');
addPI(pi6Topics[2], 'pi6-iba-10', 'Berapakah bilangan takbir zawaid pada rakaat KEDUA Solat Sunat Hari Raya?', { A: '5 kali takbir', B: '7 kali takbir', C: '3 kali takbir', D: '4 kali takbir' }, 'A', 'Pada rakaat kedua disunatkan bertakbir 5 kali sebelum membaca Al-Fatihah.', 'SK 3.2 Kaifiat Solat Hari Raya');
addPI(pi6Topics[2], 'pi6-iba-11', 'Khutbah Solat Hari Raya disampaikan:', { A: 'Selepas selesai mendirikan solat dua rakaat', B: 'Sebelum solat bermula (seperti solat Jumaat)', C: 'Di tengah-tengah solat', D: 'Pada malam hari raya' }, 'A', 'Berbeza dengan solat Jumaat, khutbah hari raya disampaikan selepas solat selesai didirikan.', 'SK 3.2 Khutbah Hari Raya');
addPI(pi6Topics[2], 'pi6-iba-12', 'Amalan sunat sebelum keluar menunaikan Solat Hari Raya Aidilfitri ialah:', { A: 'Mandi sunat hari raya, memakai pakaian bersih dan menjamah sedikit makanan (seperti kurma)', B: 'Berpuasa hingga solat selesai', C: 'Tidur sehingga tengah hari', D: 'Memakai pakaian kerja berlumpur' }, 'A', 'Sunnah Aidilfitri memakan sedikit tamar sebelum solat sebagai lambang tamatnya puasa Ramadan.', 'SK 3.2 Adab Hari Raya');
addPI(pi6Topics[2], 'pi6-iba-13', 'Hari Tasyrik yang diharamkan berpuasa ialah pada tarikh:', { A: '11, 12, dan 13 Zulhijjah', B: '1, 2, dan 3 Syawal', C: '10 Zulhijjah sahaja', D: '15 Syaaban' }, 'A', 'Hari Tasyrik (11-13 Zulhijjah) ialah hari makan minum dan menyembelih binatang korban.', 'SK 3.2 Hari Tasyrik');
addPI(pi6Topics[2], 'pi6-iba-14', 'Ibadah menyembelih binatang ternakan (an\'am) pada Hari Raya Aidiladha dan hari Tasyrik dinamakan:', { A: 'Ibadah Korban (Udhiyyah)', B: 'Aqiqah', C: 'Nazar', D: 'Dam' }, 'A', 'Ibadah korban disyariatkan sempena Aidiladha untuk mendekatkan diri kepada Allah.', 'SK 3.3 Ibadah Korban');
addPI(pi6Topics[2], 'pi6-iba-15', 'Syarat sah binatang ternakan untuk ibadah korban antaranya mestilah:', { A: 'Cukup umur, sihat dan tidak cacat anggota badan (seperti buta atau tempang)', B: 'Mempunyai tanduk paling panjang', C: 'Berwarna putih semata-mata', D: 'Binatang liar dari hutan' }, 'A', 'Haiwan korban wajib bebas daripada kecacatan ketara dan cukup umur syarak.', 'SK 3.3 Syarat Haiwan Korban');

// Topic 4: Sirah & Pembukaan Kota Mekah (need 13 more)
addPI(pi6Topics[3], 'pi6-sir-03', 'Peristiwa Pembukaan Kota Mekah (Fathu Makkah) berlaku pada tahun ke berapa Hijrah?', { A: 'Tahun ke-8 Hijrah', B: 'Tahun ke-2 Hijrah', C: 'Tahun ke-6 Hijrah', D: 'Tahun ke-10 Hijrah' }, 'A', 'Fathu Makkah berlaku pada bulan Ramadan tahun ke-8 Hijrah.', 'SK 5.1 Peristiwa Fathu Makkah');
addPI(pi6Topics[3], 'pi6-sir-04', 'Faktor utama yang menyebabkan berlakunya Pembukaan Kota Mekah ialah:', { A: 'Musyrikin Mekah dan Bani Bakr telah mencabuli syarat Perjanjian Hudaibiyah dengan menyerang Bani Khuza\'ah', B: 'Umat Islam kehabisan makanan di Madinah', C: 'Orang Mekah menjemput Nabi Muhammad berpindah', D: 'Banjir besar di Mekah' }, 'A', 'Pengkhianatan Quraisy terhadap sekutu Islam (Bani Khuza\'ah) membatalkan perjanjian damai.', 'SK 5.1 Sebab Pembukaan Kota Mekah');
addPI(pi6Topics[3], 'pi6-sir-05', 'Berapakah bilangan tentera Islam yang mara bersama Rasulullah SAW menuju ke Kota Mekah semasa Fathu Makkah?', { A: '10,000 orang tentera', B: '313 orang', C: '1,000 orang', D: '3,000 orang' }, 'A', 'Nabi SAW memimpin angkatan 10,000 tentera Islam yang berdisiplin tinggi.', 'SK 5.1 Angkatan Tentera Fathu Makkah');
addPI(pi6Topics[3], 'pi6-sir-06', 'Pemimpin Quraisy yang memeluk Islam sejurus sebelum pembukaan Kota Mekah ialah:', { A: 'Abu Sufyan bin Harb', B: 'Abu Jahal', C: 'Abu Lahab', D: 'Umayyah bin Khalaf' }, 'A', 'Abu Sufyan menyatakan keislamannya di hadapan Rasulullah SAW di Marr az-Zahran.', 'SK 5.1 Tokoh Quraisy Memeluk Islam');
addPI(pi6Topics[3], 'pi6-sir-07', 'Rasulullah SAW mengisytiharkan jaminan keselamatan kepada penduduk Mekah yang memasuki:', { A: 'Rumah Abu Sufyan, Masjidil Haram atau menutup pintu rumah mereka sendiri', B: 'Gua Hira\'', C: 'Kandang unta', D: 'Lembah Taif' }, 'A', 'Nabi SAW menjamin kesejahteraan sesiapa yang berlindung di Kaabah, rumah Abu Sufyan atau rumah sendiri.', 'SK 5.1 Jaminan Keselamatan');
addPI(pi6Topics[3], 'pi6-sir-08', 'Tindakan pertama yang dilakukan oleh Rasulullah SAW sejurus memasuki Masjidil Haram ialah:', { A: 'Memusnahkan 360 buah berhala di sekeliling Kaabah sambil membaca ayat al-Haq', B: 'Membakar rumah pembesar Mekah', C: 'Meminta wang tebusan perang', D: 'Membina benteng pertahanan' }, 'A', 'Baginda menyucikan Kaabah daripada berhala syirik sambil membaca Surah Al-Isra\' ayat 81.', 'SK 5.1 Pembersihan Kaabah');
addPI(pi6Topics[3], 'pi6-sir-09', 'Apakah kalimah agung yang dibaca oleh Nabi SAW ketika meruntuhkan berhala-berhala di Kaabah?', { A: '"Telah datang kebenaran dan lenyaplah kebatilan, sesungguhnya kebatilan itu pasti lenyap"', B: '"Tiada daya dan tiada kekuatan melainkan Allah"', C: '"Maha Suci Allah"', D: '"Segala puji bagi Allah"' }, 'A', 'Firman Allah: "Jaa-al haqqu waza-haqal baatil, innal baatila kaana zahuuqaa".', 'SK 5.1 Ayat Pemusnahan Berhala');
addPI(pi6Topics[3], 'pi6-sir-10', 'Siapakah sahabat nabi yang diperintahkan oleh Rasulullah SAW untuk melaungkan azan pertama di atas bumbung Kaabah?', { A: 'Bilal bin Rabah RA', B: 'Abu Bakar As-Siddiq RA', C: 'Umar bin Al-Khattab RA', D: 'Ali bin Abi Talib RA', }, 'A', 'Bilal bin Rabah diberi penghormatan melaungkan azan tauhid dari atas bumbung Kaabah.', 'SK 5.1 Azan di Bumbung Kaabah');
addPI(pi6Topics[3], 'pi6-sir-11', 'Sikap mulia dan luar biasa yang ditunjukkan oleh Nabi Muhammad SAW kepada musuh-musuh Quraisy yang pernah menyakiti baginda ialah:', { A: 'Memaafkan dan membebaskan mereka semua tanpa sebarang dendam ("Pergilah, kamu semua bebas")', B: 'Memenjarakan semua pembesar kafir', C: 'Merampas harta benda mereka', D: 'Menghalau mereka keluar dari Semenanjung Arab' }, 'A', 'Akhlak agung pemaaf baginda menawan sanubari penduduk Mekah sehingga mereka berbondong-bondong memeluk Islam.', 'SK 5.1 Akhlak Pemaaf Nabi');
addPI(pi6Topics[3], 'pi6-sir-12', 'Haji terakhir yang ditunaikan oleh Rasulullah SAW sebelum baginda wafat dinamakan:', { A: 'Haji Wada\' (Haji Perpisahan)', B: 'Haji Ifrad', C: 'Haji Tamattu\'', D: 'Haji Qiran' }, 'A', 'Haji Wada\' berlangsung pada tahun ke-10 Hijrah yang menandakan kesempurnaan syariat Islam.', 'SK 5.2 Haji Wada');
addPI(pi6Topics[3], 'pi6-sir-13', 'Pesanan terpenting Rasulullah SAW dalam Khutbah Terakhir (Khutbah Wada\') di Padang Arafah ialah:', { A: 'Berpegang teguh kepada Kitabullah (Al-Quran) dan Sunnah Nabi agar tidak sesat selamanya', B: 'Mengumpul harta sebanyak mungkin', C: 'Berhenti berniaga', D: 'Mendirikan istana yang megah' }, 'A', 'Baginda meninggalkan dua pusaka agung: Al-Quran dan As-Sunnah sebagai panduan hidup.', 'SK 5.2 Khutbah Wada');
addPI(pi6Topics[3], 'pi6-sir-14', 'Peristiwa kewafatan Rasulullah SAW berlaku pada:', { A: '12 Rabiulawal tahun ke-11 Hijrah', B: '1 Syawal tahun ke-10 Hijrah', C: '10 Muharam tahun ke-8 Hijrah', D: '27 Rejab tahun ke-9 Hijrah' }, 'A', 'Nabi SAW wafat di Madinah pada hari Isnin, 12 Rabiulawal 11 Hijrah.', 'SK 5.3 Kewafatan Rasulullah SAW');
addPI(pi6Topics[3], 'pi6-sir-15', 'Iktibar utama daripada peristiwa Pembukaan Kota Mekah yang boleh diamalkan oleh murid ialah:', { A: 'Menjaga janji, mengamalkan sikap pemaaf dan tidak menyimpan sifat berdendam', B: 'Membeli senjata perang', C: 'Membalas kejahatan rakan dengan kejahatan', D: 'Menunjuk kuasa apabila menjadi ketua' }, 'A', 'Kemenangan sejati adalah dengan merendah diri, memaafkan kesalahan orang dan menegakkan kebenaran.', 'SK 5.1 Iktibar Fathu Makkah');

const allPI6 = [...existingPI, ...newPI6];
fs.writeFileSync('src/data/pendidikanIslamTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const PENDIDIKAN_ISLAM_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allPI6, null, 2)};\n`, 'utf8');
console.log(`Updated Pendidikan Islam Tahun 6: total ${allPI6.length} questions.`);

// 2. BAHASA ARAB TAHUN 6
const existingBA = [...BAHASA_ARAB_TAHUN_6_QUESTIONS];
const ba6Topics = [
  'يَوْمُ الرِّيَاضَةِ الْمَدْرَسِيَّةُ (Hari Sukan)',
  'فِي مَطْبَخِ أُمِّي (Di Dapur Ibu)',
  'مِهْنَتِي فِي الْمُسْتَقْبَلِ (Kerjaya Saya)',
];

const newBA6: QuizQuestion[] = [];
function addBA(topic: string, id: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newBA6.push({
    id,
    year: 6,
    subject: 'Bahasa Arab',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: Hari Sukan (need 13 more)
addBA(ba6Topics[0], 'ba6-riy-03', 'Apakah bahasa Arab bagi permainan "Bola jaring"?', { A: 'كُرَةُ الشَّبَكَةِ (Kuratus Syabakah)', B: 'كُرَةُ الْيَدِ (Kuratu al-yad)', C: 'كُرَةُ الرِّيشَةِ (Kuratur Risyah)', D: 'كُرَةُ السَّلَّةِ (Kuratus Sallah)' }, 'A', 'كُرَةُ الشَّبَكَةِ bermaksud bola jaring.', 'SK 1.1 Kosa Kata Sukan');
addBA(ba6Topics[0], 'ba6-riy-04', 'Apakah sukan yang dimaksudkan dengan "كُرَةُ الرِّيشَةِ" (Kuratu ar-risyāti)?', { A: 'Badminton', B: 'Tenis', C: 'Bola baling', D: 'Squasy' }, 'A', 'كُرَةُ الرِّيشَةِ merujuk kepada bulu tangkis / badminton.', 'SK 1.1 Kosa Kata Badminton');
addBA(ba6Topics[0], 'ba6-riy-05', 'Apakah perkataan Arab bagi "Padang sekolah"?', { A: 'مَلْعَبُ الْمَدْرَسَةِ (Mal\'abul Madrasah)', B: 'فَصْلُ الْمَدْرَسَةِ (Faslul Madrasah)', C: 'مَكْتَبَةُ الْمَدْرَسَةِ (Maktabatul Madrasah)', D: 'مَقْصَفُ الْمَدْرَسَةِ (Maqsaf)' }, 'A', 'مَلْعَبٌ ialah perkataan Arab bagi padang atau stadium.', 'SK 1.2 Tempat Sukan');
addBA(ba6Topics[0], 'ba6-riy-06', 'Acara sukan "الْقَفْزُ الْعَالِي" (Al-Qafzul \'Aali) merujuk kepada:', { A: 'Lompat tinggi', B: 'Lompat jauh', C: 'Lari berganti-ganti', D: 'Lontar peluru' }, 'A', 'الْقَفْزُ الْعَالِي bermaksud acara lompat tinggi.', 'SK 1.1 Acara Olahraga');
addBA(ba6Topics[0], 'ba6-riy-07', 'Acara sukan "الْقَفْزُ الطَّوِيلُ" (Al-Qafzut Tawil) bermaksud:', { A: 'Lompat jauh', B: 'Lompat tinggi', C: 'Lari berpagar', D: 'Lumba basikal' }, 'A', 'الْقَفْزُ الطَّوِيلُ bermaksud acara lompat jauh.', 'SK 1.1 Acara Lompat');
addBA(ba6Topics[0], 'ba6-riy-08', 'Apakah maksud "مِيدَالِيَّةٌ ذَهَبِيَّةٌ" (Mīdāliyyatun Dhahabiyyah)?', { A: 'Pingat emas', B: 'Pingat perak', C: 'Pingat gangsa', D: 'Piala pusingan' }, 'A', 'ذَهَبٌ bermaksud emas (Pingat emas).', 'SK 1.3 Anugerah Sukan');
addBA(ba6Topics[0], 'ba6-riy-09', '"مِيدَالِيَّةٌ فِضِّيَّةٌ" (Mīdāliyyatun Fiddiyyah) merujuk kepada:', { A: 'Pingat perak', B: 'Pingat emas', C: 'Pingat gangsa', D: 'Sijil penghargaan' }, 'A', 'فِضَّةٌ bermaksud perak.', 'SK 1.3 Pingat Sukan');
addBA(ba6Topics[0], 'ba6-riy-10', 'Perkataan Arab bagi "Pemenang / Juara lelaki" ialah:', { A: 'فَائِزٌ (Fā\'izun)', B: 'خَاسِرٌ (Khāsirun)', C: 'حَكَمٌ (Hakamun)', D: 'مُدَرِّبٌ (Mudarribun)' }, 'A', 'فَائِزٌ bermaksud pemenang / juara.', 'SK 1.2 Tokoh Sukan');
addBA(ba6Topics[0], 'ba6-riy-11', 'Apakah perkataan Arab bagi "Pengadil perlawanan"?', { A: 'حَكَمٌ (Hakamun)', B: 'حَارِسٌ (Hārisun)', C: 'لَاعِبٌ (Lā\'ibun)', D: 'طَبِيبٌ (Tabībun)' }, 'A', 'حَكَمٌ merujuk kepada pengadil yang mengadili perlawanan.', 'SK 1.2 Istilah Perlawanan');
addBA(ba6Topics[0], 'ba6-riy-12', 'Pilih terjemahan yang betul bagi: "أَنَا أَلْعَبُ كُرَةَ الْقَدَمِ فِي الْمَلْعَبِ"', { A: 'Saya bermain bola sepak di padang', B: 'Saya menonton bola sepak di televisyen', C: 'Saya membeli bola di kedai', D: 'Saya membersihkan padang' }, 'A', 'أَلْعَبُ (saya bermain) + كُرَةَ الْقَدَمِ (bola sepak) + فِي الْمَلْعَبِ (di padang).', 'SK 1.4 Membina Ayat Sukan');
addBA(ba6Topics[0], 'ba6-riy-13', 'Apakah maksud "كُرَةُ الطَّائِرَةِ" (Kuratu at-tā\'irah)?', { A: 'Bola tampar', B: 'Bola lisut', C: 'Bola baling', D: 'Polo air' }, 'A', 'كُرَةُ الطَّائِرَةِ bermaksud sukan bola tampar (volleyball).', 'SK 1.1 Kosa Kata Sukan');
addBA(ba6Topics[0], 'ba6-riy-14', 'Perkataan Arab bagi "Pasukan / Kumpulan sukan" ialah:', { A: 'فَرِيقٌ (Farīqun)', B: 'فَصْلٌ (Faslun)', C: 'طَرِيقٌ (Tarīqun)', D: 'سُوقٌ (Sūqun)' }, 'A', 'فَرِيقٌ bermaksud pasukan atau regu sukan.', 'SK 1.1 Pasukan Sukan');
addBA(ba6Topics[0], 'ba6-riy-15', 'Lengkapkan ayat: "الْفَرِيقُ الْأَحْمَرُ [ _____ ] فِي الْمُسَابَقَةِ" (Pasukan Merah menang dalam pertandingan):', { A: 'فَازَ (Fāza)', B: 'نَامَ (Nāma)', C: 'أَكَلَ (Akala)', D: 'كَتَبَ (Kataba)' }, 'A', 'فَازَ ialah kata kerja masa lampau bermaksud "telah menang/berjaya".', 'SK 1.4 Kata Kerja Sukan');

// Topic 2: Di Dapur Ibu (need 13 more)
addBA(ba6Topics[1], 'ba6-mat-03', 'Apakah bahasa Arab bagi "Dapur masakan / Kompor gas"?', { A: 'مَوْقِدٌ (Mawqidun)', B: 'ثَلَّاجَةٌ (Thallajatun)', C: 'مَائِدَةٌ (Mā\'idatun)', D: 'صَحْنٌ (Sahnun)' }, 'A', 'مَوْقِدٌ bermaksud tempat memasak / dapur / stove.', 'SK 2.1 Peralatan Dapur');
addBA(ba6Topics[1], 'ba6-mat-04', 'Apakah maksud perkataan "صَحْنٌ" (Sahnun)?', { A: 'Pinggan', B: 'Cawan', C: 'Kuali', D: 'Sudu' }, 'A', 'صَحْنٌ bermaksud pinggan makan.', 'SK 2.1 Peralatan Makan');
addBA(ba6Topics[1], 'ba6-mat-05', 'Apakah perkataan Arab bagi "Sudu"?', { A: 'مِلْعَقَةٌ (Mil\'aqatun)', B: 'شَوْكَةٌ (Syawkatun)', C: 'سِكِّينٌ (Sikkinun)', D: 'كُوبٌ (Kūbun)' }, 'A', 'مِلْعَقَةٌ bermaksud sudu makan.', 'SK 2.1 Peralatan Dapur');
addBA(ba6Topics[1], 'ba6-mat-06', 'Apakah maksud perkataan "شَوْكَةٌ" (Syawkatun)?', { A: 'Garpu', B: 'Sudu', C: 'Pisau', D: 'Mangkuk' }, 'A', 'شَوْكَةٌ bermaksud garpu makan.', 'SK 2.1 Kosa Kata Peralatan');
addBA(ba6Topics[1], 'ba6-mat-07', 'Apakah perkataan Arab bagi "Pisau pemotong"?', { A: 'سِكِّينٌ (Sikkīnun)', B: 'مِقْلَاةٌ (Miqlātun)', C: 'إِبْرِيقٌ (Ibrīqun)', D: 'قِدْرٌ (Qidrun)' }, 'A', 'سِكِّينٌ bermaksud pisau.', 'SK 2.1 Peralatan Dapur');
addBA(ba6Topics[1], 'ba6-mat-08', 'Apakah bahasa Arab bagi "Kuali goreng"?', { A: 'مِقْلَاةٌ (Miqlātun)', B: 'قِدْرٌ (Qidrun)', C: 'كُوبٌ (Kūbun)', D: 'فُنْجَانٌ (Funjānun)' }, 'A', 'مِقْلَاةٌ (daripada kata kerja qala = menggoreng) bermaksud kuali.', 'SK 2.1 Perkakas Memasak');
addBA(ba6Topics[1], 'ba6-mat-09', 'Perkataan "قِدْرٌ" (Qidrun) dalam bahasa Melayu bermaksud:', { A: 'Periuk memasak', B: 'Sudu sup', C: 'Peti sejuk', D: 'Gelas air' }, 'A', 'قِدْرٌ bermaksud periuk.', 'SK 2.1 Kosa Kata Dapur');
addBA(ba6Topics[1], 'ba6-mat-10', 'Apakah maksud kata kerja "تَطْبُخُ أُمِّي" (Tatbukhu ummi)?', { A: 'Ibu saya sedang memasak', B: 'Ibu saya sedang membasuh', C: 'Ibu saya sedang makan', D: 'Ibu saya sedang berehat' }, 'A', 'تَطْبُخُ ialah perbuatan memasak bagi fa\'il muannas (ibu).', 'SK 2.2 Kata Kerja Masakan');
addBA(ba6Topics[1], 'ba6-mat-11', 'Apakah perkataan Arab bagi "Beras / Nasi"?', { A: 'أُرْزٌ (Arzun / Ruzzun)', B: 'خُبْزٌ (Khubzun)', C: 'حَلِيبٌ (Halībun)', D: 'شَايٌ (Syāyun)' }, 'A', 'أُرْزٌ bermaksud beras atau nasi.', 'SK 2.3 Bahan Makanan');
addBA(ba6Topics[1], 'ba6-mat-12', 'Apakah maksud "زَيْتٌ" (Zaytun) dalam bahan masakan?', { A: 'Minyak masak', B: 'Garam', C: 'Gula', D: 'Kicap' }, 'A', 'زَيْتٌ bermaksud minyak masak.', 'SK 2.3 Bahan Dapur');
addBA(ba6Topics[1], 'ba6-mat-13', 'Bahan perasa "مِلْحٌ" (Milhun) dan "سُكَّرٌ" (Sukkarun) bermaksud:', { A: 'Garam dan gula', B: 'Cili dan lada', C: 'Bawang dan halia', D: 'Cuka dan kicap' }, 'A', 'مِلْحٌ = garam, manakala سُكَّرٌ = gula.', 'SK 2.3 Perasa Makanan');
addBA(ba6Topics[1], 'ba6-mat-14', 'Perkataan Arab bagi "Cawan kopi" ialah:', { A: 'فُنْجَانٌ (Funjānun)', B: 'صَحْنٌ (Sahnun)', C: 'مِلْعَقَةٌ (Mil\'aqatun)', D: 'سِكِّينٌ (Sikkinun)' }, 'A', 'فُنْجَانٌ bermaksud cawan kecil untuk teh atau kopi.', 'SK 2.1 Cawan');
addBA(ba6Topics[1], 'ba6-mat-15', 'Lengkapkan ayat masakan: "أُمِّي تَغْسِلُ [ _____ ] فِي الْمَغْسَلَةِ" (Ibu membasuh pinggan di sinki):', { A: 'الصُّحُونَ (As-suhūna)', B: 'الْكِتَابَ (Al-kitaba)', C: 'الْقَلَمَ (Al-qalama)', D: 'السَّيَّارَةَ (As-sayyarah)' }, 'A', 'الصُّحُونَ ialah kata jamak bagi perkataan pinggan-pinggan.', 'SK 2.4 Membina Ayat');

// Topic 3: Kerjaya Saya (need 14 more)
addBA(ba6Topics[2], 'ba6-meh-02', 'Apakah perkataan Arab bagi cita-cita seorang "Doktor lelaki"?', { A: 'طَبِيبٌ (Tabībun)', B: 'مُهَنْدِسٌ (Muhandisun)', C: 'شُرْطِيٌّ (Syurtiyyun)', D: 'طَيَّارٌ (Tayyārun)' }, 'A', 'طَبِيبٌ bermaksud doktor perubatan lelaki.', 'SK 3.1 Pekerjaan');
addBA(ba6Topics[2], 'ba6-meh-03', 'Apakah kerjaya yang dimaksudkan dengan perkataan "مُهَنْدِسٌ" (Muhandisun)?', { A: 'Jurutera', B: 'Peguam', C: 'Wartawan', D: 'Bomba' }, 'A', 'مُهَنْدِسٌ bermaksud jurutera atau engineer.', 'SK 3.1 Kerjaya');
addBA(ba6Topics[2], 'ba6-meh-04', 'Apakah bahasa Arab bagi "Juruterbang"?', { A: 'طَيَّارٌ (Tayyārun)', B: 'سَائِقٌ (Sā\'iqun)', C: 'بَحَّارٌ (Bahhārun)', D: 'طَبَّاخٌ (Tabbākhun)' }, 'A', 'طَيَّارٌ (daripada kata thara = terbang) bermaksud juruterbang kapal terbang.', 'SK 3.1 Pekerjaan Penerbangan');
addBA(ba6Topics[2], 'ba6-meh-05', 'Apakah maksud kerjaya "شُرْطِيٌّ" (Syurtiyyun)?', { A: 'Anggota Polis', B: 'Anggota Tentera', C: 'Pengawal Keselamatan', D: 'Penyelamat Pantai' }, 'A', 'شُرْطِيٌّ bermaksud anggota polis.', 'SK 3.1 Pekerjaan Keselamatan');
addBA(ba6Topics[2], 'ba6-meh-06', 'Pekerjaan "رَجُلُ الْإِطْفَاءِ" (Rajulul Itfā\') merujuk kepada:', { A: 'Ahli Bomba dan Penyelamat', B: 'Tukang kayu', C: 'Penyelam', D: 'Tukang kebun' }, 'A', 'رَجُلُ الْإِطْفَاءِ bermaksud pegawai bomba pemadam kebakaran.', 'SK 3.1 Ahli Bomba');
addBA(ba6Topics[2], 'ba6-meh-07', 'Apakah perkataan Arab bagi "Guru perempuan"?', { A: 'مُعَلِّمَةٌ (Mu\'allimatun) / مُدَرِّسَةٌ', B: 'مُعَلِّمٌ (Mu\'allimun)', C: 'مُمَرِّضٌ (Mumarridun)', D: 'طَالِبٌ (Talibun)' }, 'A', 'مُعَلِّمَةٌ ialah guru perempuan dengan penambahan ta marbutah.', 'SK 3.1 Profesion Perguruan');
addBA(ba6Topics[2], 'ba6-meh-08', 'Apakah kerjaya yang dimaksudkan dengan "مُمَرِّضَةٌ" (Mumarridatun)?', { A: 'Jururawat perempuan', B: 'Doktor gigi', C: 'Ahli farmasi', D: 'Tukang masak' }, 'A', 'مُمَرِّضَةٌ bermaksud jururawat / nurse perempuan.', 'SK 3.1 Kerjaya Kesihatan');
addBA(ba6Topics[2], 'ba6-meh-09', 'Perkataan Arab bagi "Tentera / Askar" ialah:', { A: 'جُنْدِيٌّ (Jundiyyun)', B: 'تَاجِرٌ (Tājirun)', C: 'فَلَّاحٌ (Fallāhun)', D: 'رَسَّامٌ (Rassāmun)' }, 'A', 'جُنْدِيٌّ bermaksud tentera atau perajurit negara.', 'SK 3.1 Angkatan Tentera');
addBA(ba6Topics[2], 'ba6-meh-10', 'Pekerjaan "تَاجِرٌ" (Tājirun) bermaksud:', { A: 'Peniaga / Pedagang', B: 'Nelayan', C: 'Pemandu teksi', D: 'Posmen' }, 'A', 'تَاجِرٌ bermaksud ahli perniagaan atau pedagang.', 'SK 3.1 Perniagaan');
addBA(ba6Topics[2], 'ba6-meh-11', 'Apakah bahasa Arab bagi "Petani / Peladang"?', { A: 'فَلَّاحٌ (Fallāhun) / مُزَارِعٌ', B: 'صَيَّادٌ (Sayyādun)', C: 'خَيَّاطٌ (Khayyātun)', D: 'حَلَّاقٌ (Hallāqun)' }, 'A', 'فَلَّاحٌ bermaksud petani yang bercucuk tanam.', 'SK 3.1 Pertanian');
addBA(ba6Topics[2], 'ba6-meh-12', 'Pekerjaan "صَيَّادُ السَّمَكِ" (Sayyādus Samak) membawa erti:', { A: 'Nelayan penangkap ikan', B: 'Pemburu burung', C: 'Penternak lembu', D: 'Tukang emas' }, 'A', 'صَيَّادُ السَّمَكِ bermaksud nelayan.', 'SK 3.1 Nelayan');
addBA(ba6Topics[2], 'ba6-meh-13', 'Apakah ungkapan Arab untuk menyatakan: "Cita-cita saya ingin menjadi seorang peguam"?', { A: 'أَمَلِي أَنْ أَكُونَ مُحَامِيًا (Amali an akuna muhamiyan)', B: 'أَنَا أُحِبُّ الطَّعَامَ', C: 'أَنَا ذَاهِبٌ إِلَى الْمَدْرَسَةِ', D: 'كِتَابِي جَدِيدٌ' }, 'A', 'أَمَلِي (cita-cita saya) + أَنْ أَكُونَ (untuk menjadi) + مُحَامِيًا (peguam).', 'SK 3.2 Ungkapan Cita-cita');
addBA(ba6Topics[2], 'ba6-meh-14', 'Tempat bertugas bagi seorang pegawai polis ialah:', { A: 'مَرْكَزُ الشُّرْطَةِ (Markazus Syurtah)', B: 'الْمُسْتَشْفَى (Al-Mustasyfa)', C: 'الْمَطَارُ (Al-Matar)', D: 'الْمَحْكَمَةُ (Al-Mahkamah)' }, 'A', 'مَرْكَزُ الشُّرْطَةِ bermaksud balai polis.', 'SK 3.3 Tempat Kerja');
addBA(ba6Topics[2], 'ba6-meh-15', 'Tempat bertugas bagi seorang doktor dan jururawat ialah:', { A: 'الْمُسْتَشْفَى (Al-Mustasyfa)', B: 'الْمَدْرَسَةُ (Al-Madrasah)', C: 'الْمَلْعَبُ (Al-Mal\'ab)', D: 'السُّوقُ (As-Suq)' }, 'A', 'الْمُسْتَشْفَى bermaksud hospital.', 'SK 3.3 Hospital');

const allBA6 = [...existingBA, ...newBA6];
fs.writeFileSync('src/data/bahasaArabTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const BAHASA_ARAB_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allBA6, null, 2)};\n`, 'utf8');
console.log(`Updated Bahasa Arab Tahun 6: total ${allBA6.length} questions.`);

// 3. BAHASA CINA TAHUN 6
const existingBC = [...BAHASA_CINA_TAHUN_6_QUESTIONS];
const bc6Topics = [
  '成长与理想 (Pembesaran & Impian)',
  '科技与环保 (Sains & Alam Sekitar)',
  '文学修辞与成语 (Tatabahasa & Peribahasa)',
];

const newBC6: QuizQuestion[] = [];
function addBC(topic: string, id: string, q: string, opts: any, ans: 'A' | 'B' | 'C' | 'D', exp: string, ls: string) {
  newBC6.push({
    id,
    year: 6,
    subject: 'Bahasa Cina',
    topic,
    difficulty: 'Sederhana',
    question: q,
    options: opts,
    correctAnswer: ans,
    explanation: exp,
    learningStandard: ls,
  });
}

// Topic 1: 成长与理想 (need 14 more)
addBC(bc6Topics[0], 'bc6-lix-02', 'Peribahasa "少壮不努力，老大徒伤悲" memberi peringatan kepada murid supaya:', { A: 'Menghargai usia muda untuk belajar bersungguh-sungguh agar tidak menyesal di hari tua', B: 'Cepat bekerja untuk mencari wang', C: 'Menjaga pemakanan sejak kecil', D: 'Bermain sepanjang masa' }, 'A', 'Maksud peribahasa: Jika semasa muda tidak rajin berusaha, kelak di usia tua hanya penyesalan yang tinggal.', 'SK 1.1 Nilai Rajin Belajar');
addBC(bc6Topics[0], 'bc6-lix-03', 'Apakah maksud cita-cita "当一名宇航员" (dāng yī míng yǔ háng yuán)?', { A: 'Menjadi seorang angkasawan', B: 'Menjadi seorang arkitek', C: 'Menjadi seorang doktor haiwan', D: 'Menjadi seorang juruterbang jet' }, 'A', '宇航员 (yǔ háng yuán) bermaksud angkasawan.', 'SK 1.2 Kosa Kata Kerjaya');
addBC(bc6Topics[0], 'bc6-lix-04', 'Simpulan bahasa "胸怀大志" (xiōng huái dà zhì) menggambarkan seseorang yang:', { A: 'Mempunyai cita-cita dan wawasan yang sangat tinggi dan mulia', B: 'Suka berlagak pandai', C: 'Sering berasa takut', D: 'Berbadan tegap dan sihat' }, 'A', '胸怀大志 merujuk kepada individu yang berjiwa besar dan bercita-cita tinggi.', 'SK 1.3 Simpulan Bahasa');
addBC(bc6Topics[0], 'bc6-lix-05', 'Apakah erti perkataan "坚持不懈" (jiān chí bù xiè) dalam mengejar impian?', { A: 'Berterusan berusaha dengan gigih tanpa mudah berputus asa', B: 'Cepat menyerah kalah', C: 'Menunggu pertolongan orang lain', D: 'Bekerja secara terburu-buru' }, 'A', '坚持不懈 bermaksud kecekalan tekad yang tidak mengenal erti putus asa.', 'SK 1.3 Nilai Murni Kegigihan');
addBC(bc6Topics[0], 'bc6-lix-06', 'Pilih padanan perkataan seerti (同义词) bagi "理想" (lǐ xiǎng - impian/cita-cita):', { A: '志愿 (zhì yuàn)', B: '现实 (xiàn shí)', C: '困难 (kùn nan)', D: '习惯 (xí guàn)' }, 'A', '理想 dan 志愿 kedua-duanya bermaksud aspirasi atau cita-cita masa depan.', 'SK 1.2 Kosa Kata Seerti');
addBC(bc6Topics[0], 'bc6-lix-07', 'Apabila menghadapi kegagalan dalam pertandingan, sikap yang wajar ditunjukkan ialah "胜不骄，败不馁", iaitu:', { A: 'Tidak sombong apabila menang, dan tidak putus asa apabila kalah', B: 'Menyalahkan juri pertandingan', C: 'Berhenti menyertai aktiviti sekolah', D: 'Menangis berterusan' }, 'A', '胜不骄，败不馁 ialah semangat kesukanan dan kedewasaan emosi yang tinggi.', 'SK 1.1 Semangat Kesukanan');
addBC(bc6Topics[0], 'bc6-lix-08', 'Apakah maksud ungkapan "自强不息" (zì qiáng bù xī)?', { A: 'Sentiasa memajukan diri sendiri tanpa henti untuk menjadi lebih cemerlang', B: 'Tidur lena tanpa gangguan', C: 'Bergantung kepada keluarga', D: 'Berdiam diri' }, 'A', '自强不息 mendidik manusia agar terus berusaha memperkasakan potensi diri secara mandiri.', 'SK 1.3 Falsafah Nilai');
addBC(bc6Topics[0], 'bc6-lix-09', 'Perkataan "责任感" (zé rèn gǎn) membawa maksud:', { A: 'Sikap bertanggungjawab terhadap tugas yang diamanahkan', B: 'Rasa cemas dan gementar', C: 'Perasaan gembira yang melampau', D: 'Keinginan untuk dipuji' }, 'A', '责任感 ialah nilai murni kebertanggungjawaban dalam diri.', 'SK 1.2 Pembentukan Sahsiah');
addBC(bc6Topics[0], 'bc6-lix-10', 'Pilih kata lawan (反义词) bagi perkataan "勤劳" (qín láo - rajin):', { A: '懒惰 (lǎn duò - malas)', B: '骄傲 (jiāo ào)', C: '勇敢 (yǒng gǎn)', D: '谦虚 (qiān xū)' }, 'A', 'Lawan bagi rajin (勤劳) ialah malas (懒惰).', 'SK 1.2 Kata Lawan');
addBC(bc6Topics[0], 'bc6-lix-11', 'Peribahasa "温故而知新" (wēn gù ér zhī xīn) menggalakkan murid supaya:', { A: 'Mengulang kaji pelajaran yang telah dipelajari untuk memperoleh kefahaman baharu', B: 'Hanya membaca buku baharu', C: 'Menghafal tanpa memahami maksud', D: 'Membuang nota lama' }, 'A', 'Mengulang kaji ilmu lama membina kefahaman dan idea-idea segar yang baharu.', 'SK 1.1 Amalan Mengulang Kaji');
addBC(bc6Topics[0], 'bc6-lix-12', 'Maksud ungkapan "珍惜光阴" (zhēn xī guāng yīn) ialah:', { A: 'Menghargai setiap detik masa yang ada', B: 'Menikmati pancaran cahaya lampu', C: 'Membeli jam tangan mewah', D: 'Mengelakkan matahari terik' }, 'A', '光阴 bermaksud masa; 珍惜 bermaksud menghargai.', 'SK 1.2 Pengurusan Masa');
addBC(bc6Topics[0], 'bc6-lix-13', 'Apakah kerjaya yang sepadan dengan frasa "教书育人，默默奉献"?', { A: '教师 (jiào shī - guru)', B: '商人 (shāng rén)', C: '演员 (yǎn yuán)', D: '司机 (sī jī)' }, 'A', 'Pendidik dan guru mendidik anak bangsa dengan penuh dedikasi.', 'SK 1.2 Profesion Perguruan');
addBC(bc6Topics[0], 'bc6-lix-14', 'Peribahasa "千里之行，始于足下" membawa erti:', { A: 'Perjalanan sejauh seribu batu bermula dengan langkah pertama yang berani', B: 'Jalan raya yang sangat panjang', C: 'Kasut sukan yang tahan lasak', D: 'Berjalan kaki menyehatkan badan' }, 'A', 'Setiap kejayaan besar bermula daripada langkah kecil permulaan.', 'SK 1.1 Falsafah Kejayaan');
addBC(bc6Topics[0], 'bc6-lix-15', 'Kunci utama dalam mencapai kecemerlangan diri menurut kata bijak pandai ialah:', { A: '拥有坚定的信念与持之以恒的毅力 (Keyakinan teguh dan kecekalan berterusan)', B: '等待运气的降临 (Menunggu nasib tuah)', C: '走捷径投机取巧 (Mengambil jalan pintas tipu muslihat)', D: '轻易放弃目标 (Mudah mengalah)' }, 'A', 'Kejayaan hakiki lahir daripada tekad yang teguh dan usaha istiqamah.', 'SK 1.1 Refleksi Diri');

// Topic 2: 科技与环保 (need 13 more)
addBC(bc6Topics[1], 'bc6-kej-03', 'Istilah teknologi "人工智能" (rén gōng zhì néng) dalam bahasa Melayu ialah:', { A: 'Kecerdasan Buatan (Artificial Intelligence / AI)', B: 'Tenaga solar', C: 'Telefon bimbit pintar', D: 'Rangkaian internet' }, 'A', '人工智能 ialah terjemahan tepat bagi Artificial Intelligence.', 'SK 2.1 Istilah Sains & Teknologi');
addBC(bc6Topics[1], 'bc6-kej-04', 'Apakah faedah penggunaan "太阳能" (tài yáng néng - tenaga solar)?', { A: 'Merupakan sumber tenaga boleh baharu yang bersih dan tidak mencemarkan udara', B: 'Menghasilkan asap tebal', C: 'Menghabiskan bekalan arang batu', D: 'Menyebabkan hujan asid' }, 'A', 'Tenaga suria adalah tenaga hijau mesra alam tanpa pelepasan gas karbon.', 'SK 2.2 Tenaga Boleh Baharu');
addBC(bc6Topics[1], 'bc6-kej-05', 'Kempen alam sekitar "低碳生活" (dī tàn shēng huó) mengajak masyarakat mengamalkan gaya hidup:', { A: 'Rendah pelepasan karbon dengan menjimatkan elektrik dan berbasikal', B: 'Membakar sampah di kawasan lapang', C: 'Kerap memandu kereta bersendirian', D: 'Menggunakan beg plastik sekali guna' }, 'A', '低碳生活 mempromosikan pengurangan jejak karbon demi membendung pemanasan global.', 'SK 2.2 Gaya Hidup Lestari');
addBC(bc6Topics[1], 'bc6-kej-06', 'Kesan buruk fenomena "全球变暖" (quán qiú biàn nuǎn - pemanasan global) termasuklah:', { A: 'Ais di kutub mencair dan paras air laut meningkat', B: 'Bumi menjadi semakin sejuk', C: 'Hutan menjadi lebih luas', D: 'Banjir tidak akan berlaku lagi' }, 'A', 'Pencairan glasier kutub akibat kenaikan suhu mengancam kawasan persisiran pantai.', 'SK 2.2 Kesan Pemanasan Global');
addBC(bc6Topics[1], 'bc6-kej-07', 'Apakah maksud amalan "植树造林" (zhí shù zào lín)?', { A: 'Penanaman semula pokok untuk memelihara kawasan hutan', B: 'Penebangan hutan secara haram', C: 'Membina kilang di hutan', D: 'Memburu hidupan liar' }, 'A', 'Penanaman pokok menyerap karbon dioksida dan memulihkan habitat hidupan liar.', 'SK 2.2 Pemuliharaan Hutan');
addBC(bc6Topics[1], 'bc6-kej-08', 'Alat komunikasi moden "智能手机" (zhì néng shǒu jī) membawa erti:', { A: 'Telefon pintar (Smartphone)', B: 'Komputer meja lama', C: 'Televisyen skrin cembung', D: 'Pemain kaset' }, 'A', '智能手机 merujuk kepada telefon pintar pelbagai fungsi.', 'SK 2.1 Peranti Moden');
addBC(bc6Topics[1], 'bc6-kej-09', 'Sikap bijak menggunakan internet "文明上网" (wén míng shàng wǎng) mendidik murid agar:', { A: 'Bersopan santun di media sosial dan tidak menyebarkan berita palsu', B: 'Bermain permainan dalam talian sepanjang malam', C: 'Membuli rakan di ruang sembang', D: 'Mendedahkan maklumat peribadi kepada orang asing' }, 'A', 'Etika digital dan literasi siber melindungi keharmonian masyarakat.', 'SK 2.3 Etika Siber');
addBC(bc6Topics[1], 'bc6-kej-10', 'Penggunaan "可降解塑料袋" (kě jiàng jiě sù liào dài) digalakkan kerana ia:', { A: 'Mudah terbiodegradasi secara semula jadi dan mengurangkan pencemaran tanah', B: 'Sangat mahal harganya', C: 'Tidak boleh dicuci', D: 'Boleh dimakan manusia' }, 'A', 'Plastik mesra alam terbiodegradasi reput lebih pantas tanpa meracuni alam sekitar.', 'SK 2.2 Inovasi Hijau');
addBC(bc6Topics[1], 'bc6-kej-11', 'Apakah maksud "节能减排" (jié néng jiǎn pái)?', { A: 'Menjimatkan tenaga dan mengurangkan pembebasan sisa pencemar', B: 'Membeli banyak bateri terpakai', C: 'Membiarkan paip air terbuka', D: 'Membazirkan elektrik di rumah' }, 'A', 'Menjimatkan penggunaan sumber tenaga dan mengurangkan emisi gas rumah hijau.', 'SK 2.2 Penjimatan Tenaga');
addBC(bc6Topics[1], 'bc6-kej-12', 'Kemajuan "电子商务" (diàn zǐ shāng wù - e-dagang) membolehkan pengguna:', { A: 'Membeli-belah dan melakukan transaksi secara selamat dalam talian', B: 'Menanam sayur di komputer', C: 'Menangkap ikan di skrin telefon', D: 'Menukar wang kertas lama' }, 'A', 'E-dagang memudahkan urusan jual beli menerusi platform digital.', 'SK 2.1 Ekonomi Digital');
addBC(bc6Topics[1], 'bc6-kej-13', 'Mengapakah bateri terpakai tidak boleh dibuang bersama sisa domestik biasa?', { A: 'Kerana mengandungi bahan kimia logam berat bertoksik yang mencemarkan air bawah tanah', B: 'Kerana bateri boleh dijadikan makanan ayam', C: 'Kerana bateri mudah cair ditiup angin', D: 'Kerana bateri boleh ditanam menjadi pokok bateri' }, 'A', 'Sisa elektronik dan bateri mengandungi merkuri serta plumbum yang berbahaya.', 'SK 2.2 Pengurusan E-Sisa');
addBC(bc6Topics[1], 'bc6-kej-14', 'Kenderaan hijau "电动汽车" (diàn dòng qì chē) menggunakan punca kuasa:', { A: 'Bateri motor elektrik tanpa menghasilkan asap ekzos fosil', B: 'Arang batu', C: 'Minyak diesel pekat', D: 'Kayu api' }, 'A', 'Kereta elektrik (EV) sifar emisi ekzos mengurangkan pencemaran udara bandar.', 'SK 2.1 Pengangkutan Hijau');
addBC(bc6Topics[1], 'bc6-kej-15', 'Slogan alam sekitar "保护地球，人人有责" bermaksud:', { A: 'Melindungi planet Bumi adalah tanggungjawab setiap individu bersama', B: 'Bumi adalah planet yang paling besar', C: 'Manusia tidak perlu peduli tentang alam', D: 'Hanya kerajaan sahaja yang perlu menjaga pokok' }, 'A', 'Setiap warga bumi memikul amanah menjaga kelestarian alam semula jadi.', 'SK 2.2 Tanggungjawab Kolektif');

// Topic 3: 文学修辞与成语 (need 14 more)
addBC(bc6Topics[2], 'bc6-wen-02', 'Gaya bahasa 比喻 (simile / metafora) dapat dilihat dalam ayat:', { A: '天上的星星像无数闪闪发光的钻石。 (Bintang di langit umpama berlian berkilauan)', B: '风儿在森林里快乐地跳舞。', C: '这碗饭少得连小鸟都吃不饱。', D: '你今天去图书馆了吗？' }, 'A', 'Perkataan 像 (umpama / seperti) membandingkan bintang dengan kilauan berlian (gaya bahasa 比喻).', 'SK 3.1 Gaya Bahasa 修辞手法');
addBC(bc6Topics[2], 'bc6-wen-03', 'Ayat "花儿向太阳露出了甜美的笑脸" menggunakan gaya bahasa:', { A: '拟人 (Personifikasi)', B: '夸张 (Hiperbola)', C: '排比 (Repetisi struktur)', D: '设问 (Soalan retorik)' }, 'A', 'Memberikan sifat manusia (senyuman manis) kepada bunga ialah gaya bahasa 拟人 (personifikasi).', 'SK 3.1 Gaya Bahasa 拟人');
addBC(bc6Topics[2], 'bc6-wen-04', 'Ayat "这声音大得连十里外的人都听得清清楚楚" menggunakan gaya bahasa:', { A: '夸张 (Hiperbola / Keterlaluan)', B: '比喻 (Metafora)', C: '拟人 (Personifikasi)', D: '对偶 (Keseimbangan)' }, 'A', 'Melebih-lebihkan bunyi kuat hingga sepuluh batu ialah gaya bahasa 夸张 (hiperbola).', 'SK 3.1 Gaya Bahasa 夸张');
addBC(bc6Topics[2], 'bc6-wen-05', 'Gaya bahasa 排比 (struktur ayat bersiri selari tiga kali atau lebih) bertujuan untuk:', { A: 'Memperhebat nada dan memperkukuh hujah penulisan', B: 'Menjadikan ayat tidak difahami', C: 'Mengurangkan perenggan karangan', D: 'Memendekkan ayat' }, 'A', 'Susunan struktur selari (排比) mempertingkatkan daya puitis dan irama bahasa.', 'SK 3.1 Gaya Bahasa 排比');
addBC(bc6Topics[2], 'bc6-wen-06', 'Peribahasa "井底之蛙" (jǐng dǐ zhī wā - katak di bawah tempurung) menggambarkan:', { A: 'Seseorang yang berpandangan sempit dan cetek pengetahuannya', B: 'Orang yang mahir berenang', C: 'Orang yang tinggal di tepi telaga', D: 'Orang yang suka melompat' }, 'A', 'Sama seperti peribahasa Melayu "katak di bawah tempurung" yang tidak luas pandangannya.', 'SK 3.2 Peribahasa Seerti');
addBC(bc6Topics[2], 'bc6-wen-07', 'Peribahasa "画蛇添足" (huà shé tiān zú - melukis ular menambah kaki) memberi pengajaran supaya:', { A: 'Jangan melakukan perkara yang tidak perlu yang akhirnya merosakkan keadaan asal', B: 'Sentiasa melukis dengan cepat', C: 'Menjaga haiwan reptilia', D: 'Memakai kasut semasa melukis' }, 'A', 'Tindakan berlebihan yang sia-sia dan merosakkan kerja asal.', 'SK 3.2 Kiasan Bahasa');
addBC(bc6Topics[2], 'bc6-wen-08', 'Peribahasa "亡羊补牢" (wáng yáng bǔ láo - membaiki kandang selepas biri-biri hilang) membawa nasihat:', { A: 'Belum terlambat untuk membaiki kesilapan bagi mengelakkan kerugian yang lebih besar', B: 'Menternak kambing biri-biri di ladang', C: 'Menjual pagar yang rosak', D: 'Membeli kandang baharu' }, 'A', 'Segera mengambil tindakan pembetulan walaupun berlaku kesilapan awal.', 'SK 3.2 Peribahasa Teladan');
addBC(bc6Topics[2], 'bc6-wen-09', 'Peribahasa "对牛弹琴" (duì niú tán qín - bermain alat muzik di hadapan lembu) bermaksud:', { A: 'Bercakap perkara bernilai kepada orang yang tidak tahu menghargai atau memahaminya', B: 'Mengajar haiwan bermain piano', C: 'Menyanyi di padang ragut', D: 'Membeli alat muzik tradisional' }, 'A', 'Sama maksud dengan peribahasa "mencurah air ke daun keladi" / bercakap sia-sia.', 'SK 3.2 Peribahasa Pengajaran');
addBC(bc6Topics[2], 'bc6-wen-10', 'Peribahasa "助人为乐" (zhù rén wéi lè) menggambarkan amalan mulia iaitu:', { A: 'Gembira dan ikhlas dalam membantu orang lain yang berada dalam kesusahan', B: 'Suka berhibur di taman permainan', C: 'Membeli mainan baharu', D: 'Menerima hadiah hari jadi' }, 'A', 'Membantu orang lain mendatangkan kebahagiaan hakiki dalam sanubari.', 'SK 3.2 Nilai Bantu-membantu');
addBC(bc6Topics[2], 'bc6-wen-11', 'Apakah fungsi tanda baca "省略号" (......) dalam teks?', { A: 'Menunjukkan kata-kata yang ditinggalkan atau pemikiran yang masih berlanjutan', B: 'Mengakhiri soalan', C: 'Menunjukkan seruan kagum', D: 'Memisahkan subjek dan predikat' }, 'A', 'Tanda elipsis (......) menandakan pengguguran teks atau henti bicara beremosi.', 'SK 3.3 Tanda Bacaan');
addBC(bc6Topics[2], 'bc6-wen-12', 'Peribahasa "同心协力" (tóng xīn xié lì) membawa maksud yang sama dengan simpulan Melayu:', { A: 'Berganding bahu dan bekerjasama seia sekata', B: 'Hati tikus', C: 'Makan angin', D: 'Telinga kuali' }, 'A', '同心协力 bermaksud bersatu hati dan berganding tenaga melaksanakan tugas bersama.', 'SK 3.2 Kerjasama');
addBC(bc6Topics[2], 'bc6-wen-13', 'Gaya bahasa 反问 (soalan retorik yang jawapannya sudah tersirat) contohnya:', { A: '难道我们不应该孝顺父母吗？ (Bukankah kita wajib berbakti kepada ibu bapa?)', B: '今天星期几？', C: '你住在哪里？', D: '这本书多少钱？' }, 'A', 'Soalan retorik 反问 mengukuhkan ketegasan hujah moral.', 'SK 3.1 Gaya Bahasa 反问');
addBC(bc6Topics[2], 'bc6-wen-14', 'Peribahasa "守望相助" (shǒu wàng xiāng zhù) merujuk kepada semangat:', { A: 'Kejiranan yang saling menjaga keselamatan dan membantu sesama tetangga', B: 'Berjaga malam sendirian', C: 'Melihat pemandangan dari atas bukit', D: 'Memerhati bintang di langit' }, 'A', 'Semangat muhibah dan kejiranan yang harmoni saling menyokong.', 'SK 3.2 Semangat Kejiranan');
addBC(bc6Topics[2], 'bc6-wen-15', 'Dalam sajak dan puisi klasik Cina, unsur "韵脚" (yùn jiǎo) merujuk kepada:', { A: 'Rima bunyi akhir perkataan yang berirama merdu', B: 'Jumlah muka surat buku', C: 'Warna dakwat penulisan', D: 'Gambar ilustrasi sajak' }, 'A', 'Rima akhir (韵脚) memberikan melodi puitis yang harmonis ketika dibacakan.', 'SK 3.1 Estetika Puisi');

const allBC6 = [...existingBC, ...newBC6];
fs.writeFileSync('src/data/bahasaCinaTahun6.ts', `import { QuizQuestion } from '../types';\n\nexport const BAHASA_CINA_TAHUN_6_QUESTIONS: QuizQuestion[] = ${JSON.stringify(allBC6, null, 2)};\n`, 'utf8');
console.log(`Updated Bahasa Cina Tahun 6: total ${allBC6.length} questions.`);
